### ISSUE TITLE
how to change salt Prefix revision ($2a$10$ or $2y$10$)

### ISSUE THREAD

**Issue by mazyar1128** [delight-im/PHP-Auth#101]
In order to compatible this library , I need to be able to choose between different revisions ($2a$10$ or $2y$10$).
I want to authenticate the users through .Net libraries , So the issue here is most of the libraries for .Net make the hash with prefix of "$2a$" , thus the verification process returns "False" on the application.

Is there any way to make that compatible or choose that revision?

**Comment by ocram** [comment]
This library is able to verify multiple versions of password hashes, i.e. it accepts different algorithms and different settings (such as the cost factor). As long as your password hashes are compatible with [crypt(3) from the Unix C library](https://en.wikipedia.org/wiki/Crypt_(C)), it should work fine.

Separate from this library, you could call [`password_get_info`](http://php.net/manual/en/function.password-get-info.php) on your password hashes from .NET for testing. If that works and returns meaningful information, you can also check [`password_verify`](http://php.net/manual/en/function.password-verify.php) directly.

Or is it that you *generate* the password hashes in *PHP* but want to *verify* them in *.NET*?

Does that help?

**Comment by mazyar1128** [comment]
Thanks @ocram, that was helpful, but I just have an issue you asked below 

> Or is it that you generate the password hashes in PHP but want to verify them in .NET?

I just generate the password hashes in PHP, and then wants to Verify it in PHP and .Net. 
PHP verifies the hashes correctly without any issue, but the verification process in .Net returns false or returns "Invalid salt revision". 
I know one of the solution is to change the Hash algorithm in PHP from DEFAULT to other algorithms, I did it and works fine for most of the algorithms. But I want to use the Bcrypt (blowfish algo) and verify it on .Net. 
As I know the PHP just uses the new version of Bcrypt to hash the password. 
Do you know how I can make the PHP hash to use the older version "$2a$" hash?

**Comment by ocram** [comment]
Well, `$2$` has been the original prefix for bcrypt. After having added handling of non-ASCII characters to the specification, that revivision got the prefix `$2a$`. Unfortunately, in the implementation that PHP used, `crypt_blowfish`, [a bug was discovered](http://php.net/security/crypt_blowfish.php). So it was advised to mark all existing and affected hashes with `$2x$` instead for compatibility. Those were the hashes resulting from the bug. And `$2y$` was introduced to mark new and unaffected hashes. But there’s also a fixed version of `$2a$` that produces correct hashes, too. You just can’t be sure whether `$2a$` is the fixed or the broken version.

Anyway, if you have been using a correct version of the implementation all the time, or if your passwords were not affected (e.g. pure ASCII), all these revisions work the same way.

Since you’re using an implementation in another language (.NET), you should first try to simply change the prefix manually from PHP’s output to something that your .NET implementation understands, e.g. from `$2y$` back to `$2a$`. That might work fine. Otherwise, I’d recommend to look for a different implementation in .NET.
