### ISSUE TITLE
password encryption and table names

### ISSUE THREAD

**Issue by mhmd1983** [delight-im/PHP-Auth#102]
Hello,
I think it'll be nice feature if we can change tables names and fields also the password encryption type
I've a working website with different db structure and password encryption type and want to use this library 
so choosing the users table and password field encryption type would be very helpful

**Comment by ocram** [comment]
We understand your wish to have this customized as well, but unfortunately, that is not going to happen. At some point, too much customization becomes too much of a burden on development. Sorry!

**Comment by ocram** [comment]
As the previous comment alone may not have been that helpful, let me add the following options for things you could do:

 * Adjust your existing application to the database schema of this library and import data from your old tables into the ones for this library.
 * or
 * Manually change the code of this library in your private fork so that it works with your existing application. You should accept, then, that you’ll have a much harder time upgrading to any new releases.
 * or
 * Pick some other library that is a better fit with *existing* applications. This library here isn’t. It’s mostly for new applications or those that can be adapted.

Hope that helps!
