### ISSUE TITLE
Possible workaround to allow Signup/Login by Phonenumber

### ISSUE THREAD

**Issue by nenad007** [delight-im/PHP-Auth#106]
I would like to allow the user to signup by email or phone number or email together with phone number.

Would this be a way to go:
if user signup with phone number 012345678 I will generate a email like: 012345678@phone.number store it in users.email and in new table store phone number related to users.id
later when user try to login with numeric "email" add "@phone.number" to it and try to authenticate.

In case user signup with email and his phone number together, store email as email and phone number into new table. 
Later when user try to login with phone number lookup in new table for users.id then get email from users table and authenticate togoether with entered password.

OR is there a better solution with PHP-Auth OR should i skip completely PHP-Auth for such case?

**Comment by ocram** [comment]
This is a very good question, thanks!

What you describe is a perfectly valid and reasonable workaround that we would indeed recommend you to use. The only downside is that you would always have to remember that what you’re getting from the email field or its accessor methods may not actually be a valid email address but a phone number.

So if you display the email address to the user, you may want to wrap that in an extra check, ensuring that you don’t display your internal phone-based “email address” to the user. Of course, you can abstract all that away and write your own wrapper methods around this library’s methods that handle these checks for email versus phone.

If you only need phone numbers but *no* email addresses, you can even reduce the setup and drop the extra table. Just use the “email address” derived from the phone number then.

By the way, if you use something like `012345678@phone.localhost` instead of `012345678@phone.number`, you can be sure that the domains in your identifiers will never be a publicly registrable domain name and thus your identifiers will never be a valid email address.

Hope that helps!
