### ISSUE TITLE
Extending the class

### ISSUE THREAD

**Issue by sportfogadas** [delight-im/PHP-Auth#11]
Hi,

Wouldn't it be better for the methods to be protected in case you want to extend the Auth class? For example, if I want a login method with user name instead of e-mail.

**Comment by ocram** [comment]
Thanks for your feedback!

This has definitely been thought about. But in general, we're following the principle of *designing* for inheritance, instead of just opening up every single method and allowing for it to be overridden:

> Design and document for inheritance or else prohibit it
>
> -- Joshua Bloch, *Effective Java*.

That being said, you're welcome to open a new issue whenever you feel that some method needs to be opened up. We can then discuss it, design for inheritance as needed and document it properly, and then ship the change in a new release.

Let's discuss your specific idea of having a login by username in a separate issue as well: https://github.com/delight-im/PHP-Auth/issues/12
