### ISSUE TITLE
One login per user at a time?

### ISSUE THREAD

**Issue by truewx** [delight-im/PHP-Auth#110]
Is there anyway to only allow one login per user at a time so there is no account sharing?

**Comment by ocram** [comment]
This would certainly be a useful feature in some cases, but it’s not anything that had come up so far, and there had not been any demand for this. So, unfortunately, it’s not part of this library, yet.

What you could do, though, is call `Auth#logOutEverywhereElse` whenever a user successfully signs in. That way, the other sessions for that account will be logged out.

A few things you’d need to keep in mind with this solution:

 * Users may sign in upon confirming their email, if you opted to use `Auth#confirmEmailAndSignIn` instead of `Auth#confirmEmail`.
 * Users may be signed in via a “remember” cookie, if they chose to enable this during their last manual login and if you chose to support this feature.
 * There is a parameter of the `Auth` constructor that controls the interval for forced (remote) logouts.

Hope that helps!
