### ISSUE TITLE
Use PHP-Auth without Composer

### ISSUE THREAD

**Issue by binoculars88** [delight-im/PHP-Auth#112]
Is there a way to use this without Composer? So by just putting the files in a directory and using something like include(...) in PHP?

I don't have the required server access to install composer on it.

**Comment by ocram** [comment]
Thanks!

Although you’ve already figured it out, let me explain it again, nevertheless:

We’ve had people asking to use this library without Composer several times already, e.g. in https://github.com/delight-im/PHP-Auth/issues/90, https://github.com/delight-im/PHP-Auth/issues/31 and https://github.com/delight-im/PHP-Auth/issues/14. But every single time, it was simply because they were unfamiliar with Composer to that point.

Common misconceptions are that Composer isn’t available everywhere, is hard to install, or difficult to use. Fortunately, all that is wrong.

The most important thing to know is that Composer does *not* need to be installed on your server. You can simply imagine Composer as a download manager that you install on your local development machine. It just does what you otherwise need to do manually: download all source files and dependencies and sort them into a useful directory structure.

Again, you only need to install Composer on your local machine where you develop the application. When deploying the application, you simply include the `vendor` directory created by Composer and that’s all – no need to install Composer on the server again.

Later, you’ll find out how useful Composer actually is, beyond just downloading your dependencies (in which it is also way faster than a human).
