### ISSUE TITLE
Confirmation mail not sent

### ISSUE THREAD

**Issue by binoculars88** [delight-im/PHP-Auth#113]
I'm trying out the included test page, and everything works fine, except... New registrations don't get a confirmation email, even when I click "Require email confirmation -- Yes". The "Resend confirmation" doesn't work too. Any tips? Does it require an extra setup or something to enable mail sending? Checked my spam folder too of course, nothing...

A basic `mail("email@something.com","My subject",$msg);` test works, so my server is able to send mails...

**Comment by ocram** [comment]
Thanks!

Sending email is simply not implemented for compatibility reasons. Everyone may have a different mail setup, or may not actually want to have emails sent during tests. So that’s why it’s not included.

Instead, the information needed for verification is simply displayed at the top of the page.

In `tests/index.php`, you will find five occurrences of `function ($selector, $token)`. Inside those closures, you would have to replace the code that displays the information with code that actually sends the email, if you really wanted to do that.

But instead of using the `tests/index.php` file for one’s own implementation, one should create an implementation from scratch following the README.

**Comment by binoculars88** [comment]
I see, thanks for the info, I works now!

A bit off topic, but still: while I'm definitely planning on starting from scratch (I'm just looking into the plugin's possibilities via the `tests` page), I don't quite understand why you clearly strongly discourage people to use the `tests` page as a boilerplate. It seems like a solid piece of code with all the necessary functionalities to me. I ask this purely out of curiosity... and because I might learn something too.

**Comment by ocram** [comment]
Yes, including both values in the URL is also what the README suggests. This is fine and common practice. The values must be sent to the user in some form, there’s no way around that. So putting them into a URL does not make them any more visible. URLs with their query strings (as part of a GET request) may be logged on the server and saved in browser histories, but these tokens are short-lived and can be used once only, so that’s acceptable as well. Finally, if you are afraid such links may be prefetched by browsers or clicked unintentionally by users, you may require another affirmative action (e.g. clicking a button) on the resulting page.

The README contains most of the code that you’d want to use from the `tests/index.php` file, anyway. Moreover, the README drops all those parts that are specific to the tests and which you would rather not want to include. And, most importantly, the README explains everything in detail so you really understand what each call and parameter does and how to tweak settings.

**Comment by binoculars88** [comment]
Thanks for taking the time to give high quality support. Really appreciate it!
