### ISSUE TITLE
Delight-IM PHP-Auth not setting role

### ISSUE THREAD

**Issue by MB34** [delight-im/PHP-Auth#117]
In trying to use the Auth library, I'm logging the user in using the `$auth-login` method with an email and password. Then I'm retrieving the userid and setting their Role to Admin. However, getting nothing returned when I QUERY the userId and roles and if the user is an admin, see below. Am I doing this wrong?

    require __DIR__ . '/vendor/autoload.php';

    include '/var/config.php'; // contains DB connection info, outside webroot

    $auth = new \Delight\Auth\Auth($db);

    try {
        $auth->login($_REQUEST['email'], $_REQUEST['password']);
    }
    catch (\Delight\Auth\InvalidEmailException $e) {
        // wrong email address
    }
    catch (\Delight\Auth\InvalidPasswordException $e) {
        // wrong password
    }
    catch (\Delight\Auth\EmailNotVerifiedException $e) {
        // email not verified
    }
    catch (\Delight\Auth\TooManyRequestsException $e) {
        // too many requests
    }

    $userId = $auth->getUserId();

    try {
        $auth->admin()->addRoleForUserById($userId, \Delight\Auth\Role::ADMIN);
    }
    catch (\Delight\Auth\UnknownIdException $e) {
        // unknown user ID
    }
    
    echo "" ."\r\n";

This is the result:

    
        
Database shows `roles_mask` = 0

**config.php**

    require __DIR__ . '/vendor/autoload.php';
    
    use Delight\Db\PdoDataSource;

    $dataSource = new PdoDataSource('pgsql');

    $dataSource->setHostname('127.0.0.1');
    $dataSource->setPort(5432);
    $dataSource->setDatabaseName('dbname');
    $dataSource->setCharset('UTF8');
    $dataSource->setUsername('dbUser');
    $dataSource->setPassword('dbPassword');

    $db = \Delight\Db\PdoDatabase::fromDataSource($dataSource);

**Comment by frankieeedeee** [comment]
Hey there! First of all, with the catch statements (ie, EmailNotValidException), you don’t have anything to tell the script that the login failed for some reason. Under each one of those cases, put a die(“Email was not valid”); or die(“Password was incorrect”); etc etc to see if $auth->login(...) actually worked or not. (I suspect the $_REQUEST[“email”] etc may not have any data, so you’re not giving any data to $auth->login(), and so $auth->getUserId() is not producing anything because no one is logged in!)

Of course in production, you would implement some appropriate aplication logic, ie a redirect to an error page, to show them that their login failed for the given reason.

Hope that helps! :)

**Comment by MB34** [comment]
Yeah, you're right. I had the email address wrong and I also had a `#` in the password and needed to encode it. Geez, sometimes developers can be such idiots...

**Comment by ocram** [comment]
@frankieeedeee Thanks a lot for helping out (with great advice that did indeed lead to the solution)!

Glad to hear that this worked out in the end and everything seems to be working correctly here.

@MB34 I’m sure that what you posted is only an excerpt that is missing parts of your application logic. But you may want to wrap the call to `Administration#addRoleForUserById` in a conditional or even move it to another file (or function) so that you don’t set the role on every log in by that user. Moreover, you should generally guard calls to `Auth#admin` with your own access controls so that you don’t perform any operations with full administrator privileges for *any* user.
