### ISSUE TITLE
Can't dynamically access roles

### ISSUE THREAD

**Issue by Abraham-Tourdex** [delight-im/PHP-Auth#122]
Hey I'm trying to write a loop that removes all the current users roles, like so:

    $roles = $auth->admin()->getRolesForUserById( $userid );
    foreach( $roles as $key => $val ){
        $auth->admin()->removeRoleForUserById( $this->DBid, \Delight\Auth\Role::$val);
    }

The issue here is that I can't dynamically name the role using `\Delight\Auth\Role::$val`, PHP is telling me: 

     Access to undeclared static property: Delight\Auth\Role::$val

So I tried to use a variable variable as such: `\Delight\Auth\Role::$$val` (two `$`s) and the error changes to:

     Access to undeclared static property: Delight\Auth\Role::$ADMIN

So as you can see the variable is resolved, but there is a `$` inserted in there still.

I think this must be a PHP language thing (I'm on `5.6.37`) but if there's another way I can remove all roles from a user then that would work tooooo.

cheers

**Comment by Abraham-Tourdex** [comment]
Nevermind, I was barking up the wrong tree, here's how it's done, for posterity:

     $auth->admin()->removeRoleForUserById( $this->DBid, constant( '\Delight\Auth\Role::' . $role ) );

**Comment by ocram** [comment]
Well, actually, there should even be a simpler solution.

Can you inspect `$roles`, which is the result of `Administration#getRolesForUserById`, using something like `var_dump` in order for you to actually see what it contains?

It should be a mapping of the numeric identifiers (which you need) to the readable names (which you used).

Thus, instead of passing `\Delight\Auth\Role::$val` or `constant('\Delight\Auth\Role::' . $role)`, you should be able to just use `$key`. Does that work?
