### ISSUE TITLE
Support multi-site Accounts (like SaaS)

### ISSUE THREAD

**Issue by nenad007** [delight-im/PHP-Auth#126]
I have a project where I need to be able to handle multiple sites (every site has own site_id) with one Database and one codebase and every site uses **own** User accounts which means one email can hane a account of multiple of them, therefore I'm looking for the best solution to use PHP-Auth.

So far I found this way:
I need to add to users table the value "site_id" and add it to the unique Key together with email. 

add to Auth constructor as 2nd paramter site_id
Create Instance with \Delight\Auth\Auth($db, $site_id);

change following function to use site_id:
createUserInternal
getUserDataByUsername
changeEmail 
getUserDataByEmailAddress

Is there any better solution with extend/abstract the classes of PHP-Auth to reach this without to change PHP-Auth?

**Comment by ocram** [comment]
I’d say this is quite a fundamental change and currently out of scope of this library.

In general, the most efficient and cleanest solution would be to have a separate set of tables for each site, distinguished via a site-specific prefix, such as `site_4_`. That’s still one database and one code base. But it seems you don’t want that. And with an unlimited number of sites, you probably need something more dynamic.

So what you suggested, i.e. modifying the code to use (`site ID, email address)` everywhere instead of just `email address`, is indeed a proper solution.

**Comment by ocram** [comment]
By the way, you could also have *one* central authentication provider and then, instead of signing up to every site individually, sign in to individual sites using single sign-on (SSO), see https://github.com/delight-im/PHP-Auth/issues/76.
