### ISSUE TITLE
Adapting the library to an existing user structure

### ISSUE THREAD

**Issue by jemediacorp** [delight-im/PHP-Auth#130]
I came across your authentication library yesterday and can say without a doubt it's the most feature-rich library I've ever seen for handling user authentication and session management tasks. However, as someone who's already written a rudimentary yet secure authentication and session system as part of the PHP framework I've built from scratch, and who has already set up a few sites on this framework with users and groups, I have a few questions on how I might integrate your library with my existing user setup.

In particular, I'd like to replace all of my authentication functions with your library but keep my existing user accounts so I don't have to start fresh or import or etc. In my current setup, users sign in with an e-mail address and password, and the e-mail address acts as their username, with no separate username being available. The users table contains fields for an e-mail address, password (hashed the same way your library hashes them), registration date/time, last login date/time, and API key and secret key attached to API key (for making calls to my framework's REST API).

One of the biggest differences between my existing setup and your library is that my setup uses globally-unique version 4 UUIDs for the user ID whereas your library uses integers. How can I modify your library to use the user IDs so I don't have to make any changes to my existing user set?

Also, my setup allows for the dynamic addition and removal of user roles. Each role has a number and a corresponding short code (like short name) and display name. I saw that your library allows for custom role mapping/aliasing, but I'm wondering how I might get this to work when the roles are specified dynamically and stored in a roles table in the database?

Thank you in advance for any assistance/advice/insight provided!

**Comment by ocram** [comment]
Thank you for your appreciation!

> However, as someone who's already written a rudimentary yet secure authentication and session system as part of the PHP framework I've built from scratch, and who has already set up a few sites on this framework with users and groups, I have a few questions on how I might integrate your library with my existing user setup.

This library here is obviously most suitable for new projects, since designing a general-purpose library that works for a multitude of *existing* projects with different concepts and designs is quite hard.

On the other hand, adjusting this library to work with an existing project is not possible, of course. In general, you have two options:

 * Change your database structure (while keeping your database contents) so that it is compatible with this library. The advantage is that you keep compatibility with this library and can easily apply future updates.
 * Change this library so that it is compatible with your database structure. The advantage is that you need minimal changes in your own application.

> In particular, I'd like to replace all of my authentication functions with your library but keep my existing user accounts so I don't have to start fresh or import or etc.

It seems that would work with both approaches described above.

> In my current setup, users sign in with an e-mail address and password, and the e-mail address acts as their username, with no separate username being available. The users table contains fields for an e-mail address, password (hashed the same way your library hashes them)

Sounds like a perfect match for this library.

> One of the biggest differences between my existing setup and your library is that my setup uses globally-unique version 4 UUIDs for the user ID whereas your library uses integers. How can I modify your library to use the user IDs so I don't have to make any changes to my existing user set?

Again two possible solutions: Either you could create an additional table that maps your UUIDs to this library’s integer IDs. Or you could adjust this library to use UUIDs as well. (It seems you don’t want to change your application to use integer IDs instead.)

The user IDs for this library are generated by the database using `AUTO_INCREMENT` or `SERIAL` and thus are generated (implicitly) in a single place when creating the accounts. So you could change the database schema to use UUIDs instead and whenever inserting a user from code, you specify the new UUID column as well and provide a value. There are other database tables that reference user IDs. You’d have to modify those columns as well.

> Also, my setup allows for the dynamic addition and removal of user roles. Each role has a number and a corresponding short code (like short name) and display name. I saw that your library allows for custom role mapping/aliasing, but I'm wondering how I might get this to work when the roles are specified dynamically and stored in a roles table in the database?

This library doesn’t care if your roles are stored in constants (as it is now) or variables in code or in your database. But right now, the library only supports roles with integer IDs that are powers of two. We have currently no plans to change that. But with some work, you can change this library to use your concept of roles, of course. Or you just don’t use this library’s concept of roles and use your own roles along with this library.

Hope that helps!

**Comment by jemediacorp** [comment]
Thank you for your prompt feedback! I was considering modifying the library to fit the specific needs of my framework for users by switching to using user IDs, modifying roles, etc. but would those changes still allow me to update the library when new versions become available? I'm new to Composer and unsure as to how it determines which files to override, whether it saves files that have been changed manually across software updates, etc.

Out of curiosity, what was your reasoning behind using integers for user IDs rather than UUIDs? I was always taught to use UUIDs with any rows of data that may contain sensitive information because UUIDs, unlike integers, aren't easily guessed so users would not be able to glean information about users or etc. just by guessing the next or previous ID in a sequence.

One question I forgot to ask, if e-mail addresses are used in this library as "usernames" to sign in, why is it that the additional parameter that can be passed to the registration method, rather than the e-mail address itself, the parameter that can be checked for uniqueness? IN other words, how would I prevent someone from creating an account with an e-mail address that already exists in the database without using the optional username parameter?

**Comment by ocram** [comment]
> but would those changes still allow me to update the library when new versions become available?

Well, any change that you make to *this library* makes updating harder. If you make changes to *your application* instead, that allows for easier updating. But you’ll have to decide what you need and want here. One may be (a lot) more work than the other, depending on your setup and code.

> I'm new to Composer and unsure as to how it determines which files to override, whether it saves files that have been changed manually across software updates, etc.

Composer is really simple and easy to understand in that regard: When it comes to the `vendor` directory created and used by Composer, that is really intended to be for Composer only. So Composer treats everything in that directory as its own property and will update, delete and create files as needed. So it will overwrite everything. That makes sense because the directory is for Composer to store the dependencies it manages.

That is not a problem if you just keep a copy of your modifications somewhere else. But after an update, you have to re-apply all changes, of course. That’s not Composer’s fault, though. There’s no way around that.

> what was your reasoning behind using integers for user IDs rather than UUIDs?

Integer IDs are actually quite a common choice. I don’t think you have to justify either integer IDs or UUIDs. Both are fine and commonly used.

> I was always taught to use UUIDs with any rows of data that may contain sensitive information because UUIDs, unlike integers, aren't easily guessed so users would not be able to glean information about users or etc. just by guessing the next or previous ID in a sequence.

That is a reasonable point and user enumation is something you should pay attention to and try to avoid. But using integer IDs internally does not mean you have to be vulnerable to user enumeration. For example, in the extreme case, you may use integer IDs *internally* but don’t publicly expose access to users or profiles *anywhere*.

> One question I forgot to ask, if e-mail addresses are used in this library as "usernames" to sign in, why is it that the additional parameter that can be passed to the registration method, rather than the e-mail address itself, the parameter that can be checked for uniqueness? IN other words, how would I prevent someone from creating an account with an e-mail address that already exists in the database without using the optional username parameter?

Email addresses are the primary identifier used by this library and are always verified to be unique. *Additionally*, you can allow users to sign up and sign in with usernames, if you want, and it will then be up to you to decide whether usernames must be unique as well.

**Comment by jemediacorp** [comment]
Thanks for your detailed reply; I’m still debating if I want to change my application’s code or modify the library to get the changes I’d like to see. The problem with modifying my application’s code is that the “application” is actually a PHP framework I developed three years ago and have been updating ever since, and it’s used on a few Websites I’ve built so I’m trying not to introduce many breaking changes when I implement this new user authentication and management solution.

Turning to the library’s database connection for just a minute, I already use a MySQLi-based database connection library, located on Github at https://github.com/ThingEngineer/PHP-MySQLi-Database-Class <https://github.com/ThingEngineer/PHP-MySQLi-Database-Class> but this doesn’t use PDO. It does, however, provide an object-oriented method for interacting with database tables that I’ve found to be very convenient and easy to understand, thus why I’ve been using it. Could I keep this database connection active but also start a new one in PDO for your authentication library when needed, having 2 active connections at once? Or do I have to rethink things some more?

I’m glad e-mail addresses are always verified to be unique; this wasn’t mentioned very well in the README so I assumed, based on what I read, that only the usernames given in the third parameter of the register function could be verified as unique if coded correctly.

--

Logan Merrill
System Administrator
J&E Business Consulting LLC
Office: (585) 554-8300 extension 308
E-mail: logan.merrill@jemediacorp.com

**Comment by ocram** [comment]
> I’m still debating if I want to change my application’s code or modify the library to get the changes I’d like to see.

That’s really up to you, and depends on what you find more important and what means less work for you (both now and in the future).

> The problem with modifying my application’s code is that the “application” is actually a PHP framework I developed three years ago and have been updating ever since, and it’s used on a few Websites I’ve built so I’m trying not to introduce many breaking changes when I implement this new user authentication and management solution.

It seems you might actually want to work on your copy of this library and adjust it to your needs. Just be aware that you cannot expect support in the future then and you have to port any changes and updates back to your custom version if you need them.

> Could I keep this database connection active but also start a new one in PDO for your authentication library when needed, having 2 active connections at once? Or do I have to rethink things some more?

Sure, that should be possible, but obviously inefficient in resource usage.
