### ISSUE TITLE
crypted password for rest api

### ISSUE THREAD

**Issue by lsantaniello** [delight-im/PHP-Auth#138]
Hi guys,
I need to expose a login rest api for my app. I want to encrypt my password in the http request but login method want the correct password.

As is
`$auth = new \Delight\Auth\Auth($db);
    $auth->login($email, $password);`

To be
`$auth = new \Delight\Auth\Auth($db);
    $auth->login($email, $cryptedPassword);`

I'd like to add a new login method with crypted password with md5 alghoritm.

Could you please support me?

Thanks
Luca

**Comment by ocram** [comment]
It seems you want to have *both* the *actual* password and an encrypted (technically: *hashed*) version of granting access and being accepted as valid. Is that correct?

Technically, that would simply mean you’d have *two* passwords. That’s all.

Internally, the passwords are hashed as well, so the library cannot simply restore a cleartext version of it and just apply a different hashing algorithm (e.g. MD5, which is weak, by the way).

So the only solution for that would really be to have two separate passwords. And this library doesn’t support that.

What you can do, however, is always accepting *only* the password pre-hashed with your custom hashing function. So with the REST API, you’ll receive the hashed password from the user and just pass this to the library. And in other places, where you receive the cleartext password from the user, you just hash it in your application code and then pass *this* to the library.

That way, you’d have only *one* password again, but it’s the one hashed with your custom hashing function, not the cleartext version.

Does that help?

Apart from all that, is hashing with MD5 really necessary? Is HTTPS (TLS) for your REST API not sufficient? Is it because clients must store the password somewhere in order to connect to your API, and you don’t want them to store their actual password in cleartext? (Anyway, MD5 is a weak solution there.)

If your clients support cookies, you could make use of the “remember me” cookies as well. Or you could even just “emulate” these cookies by extracting the token and sending it back in a HTTP “Cookie” header.

**Comment by lsantaniello** [comment]
Thanks @ocram for your feedback.

**Comment by ocram** [comment]
No problem!
