### ISSUE TITLE
Installation instruction not sufficient

### ISSUE THREAD

**Issue by DaibaCity** [delight-im/PHP-Auth#14]
Dear Delight-Im,

When following the instructions I keep getting an error.
I copied the files (Auth.php, Base64.php and Exceptions.php) to a subfolder.
When I run the following script however, I get the following errors, no matter what I tried.
I feel like there might be an error using the namespaces?

I run the following (I tried both instances of $db uncommented)
```
require 'subfolder/Auth.php';
// $db = new PDO('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');
// or
// $db = new \Delight\Db\PdoDsn('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');

$auth = new \Delight\Auth\Auth($db);
```

But I get the following errors:
**Uncaught Error: Class 'Delight\Db\PdoDatabase' not found in ... Stack trace: #0 ...: Delight\Auth\Auth->__construct(Object(PDO)) #1 {main}** 

OR

**Fatal error: Uncaught Error: Class 'Delight\Auth\PdoDsn' not found in ...
 Stack trace: #0 {main}**

I tried to install everything using composer but I got the some errors......

I am really looking forward to start using this package!

Cheers

**Comment by ocram** [comment]
Thanks a lot for pointing this out!

Technically, importing the library manually is still possible. But since you have Composer already, anyway, this is definitely the recommended approach.

The manual way of including the library used to be possible in a convenient way. But two external dependencies have been introduced over the time, as can be seen [here](https://github.com/delight-im/PHP-Auth/blob/4dcf491ad9bb670dd5892e749504136c8bc1da72/composer.json#L4). We forgot to update the installation instructions with language that reflects this.

The README has thus been updated now in https://github.com/delight-im/PHP-Auth/commit/4f5ff151ef490deefd4af28467c82959e6e3e50b

We'd like to ask you to try the setup with Composer again. Please see the updated installation instructions in the README. The setup with Composer has been tested time and again and works. Please make sure that you really included the Composer autoloader (and not the classes from this library directly).

**Comment by DaibaCity** [comment]
Thanks! It is working now! Looking forward to get started with this package!

**Comment by LimpEmu** [comment]
Is it possible to please include more detailed instructions that are not dependent on Composer? For several reasons, I cannot use Composer and am struggling with the same issue.

**Comment by LimpEmu** [comment]
I got the tests/index.php file to work after I included all of the following:
```
require 'src/Database.php';
require 'src/DataSource.php';
require 'src/Dsn.php';
require 'src/ErrorHandler.php';
require 'src/Measurement.php';
require 'src/PdoDatabase.php';
require 'src/PdoDataSource.php';
require 'src/PdoDsn.php';
require 'src/Profiler.php';
require 'src/SimpleMeasurement.php';
require 'src/SimpleProfiler.php';
require 'src/ResponseHeader.php';
require 'src/Cookie.php';
require 'src/Session.php';
require "src/UserManager.php";
require "src/Administration.php";
require "src/Auth.php";
require "src/Base64.php";
require_once "src/Exceptions.php";
require "src/Status.php";
```
Maybe this helps others ...

**Comment by rgvy** [comment]
@LimpEmu, I feel your pain. Like yourself, I don't like using composer.

It's not too difficult to do the setup that composer does manually. But first, you must understand what it does and how it works:
1) First composer recursively downloads any dependencies (you can check for these in projects' `composer.json` files)
2) Then it places the source files in specific places (often based on namespace/class name) to be used in the next step
3) It creates an 'autoload' script that tells php where to find any classes it needs if they are not already loaded at runtime

You can learn more about autoloading here: http://php.net/manual/en/language.oop5.autoload.php

Because php passes the namespace and class to the autoloader, it makes sense to layout your file structure using that format. Here is an example autoloading function:
```php
spl_autoload_register(function($class_name)
{
	$folder = 'lib';
	$path = str_replace('\\', '/', $class_name);
	$file = __DIR__."/$folder/$path.php";
	if (is_readable($file))
		require $file;
});
```
You can see how it locates the `.php` file based on namespace and class.

You might have to modify this function for some libraries (for example ones that use _ instead of \ in namespaces).

Autoloading is basically necessary with medium and larger projects. It is wasteful to load every single dependency on every single type of request, so the autoloader only loads them when needed. But the main benefit is not having to write out any `require` statements ever again -- the autoloader will find them automatically (if you've set up the autoload function properly).

**Comment by LimpEmu** [comment]
Thank you for your note.

I was able to write an autoloader function, and I was also able to get all
the features to work for the project I am working on. This is a very nice
package. I have problem remaining that I cannot figure out. It seems to
have something to do with dual factor authentication which I will not
support (not necessary for this project). For some logon attempts I get the
result "attempt cancelled." If I keep trying to logon, at some point, it
works, but I am clueless why this issue occurs. What situation triggers
this $result, and how can I avoid it?

I have not much experience with PHP, so I apologize if this is a dumb
question, I do much appreciate your work and help. Thank you,
Beate

--
Beate Danielsen, Director, Health Information Solutions
Voice: 916-435-4676   e-mail: beate@health-info-solutions.com   web:
www.health-info-solutions.com

**Comment by LimpEmu** [comment]
Hello again:

I am not sure this is going anywhere, but in case it is, I would like to
express my gratitude for the PHP AUTH library. I have very little
experience with PHP, but was able to integrate your authentication
mechanism in a website for the California Society of Thoracic Surgeons that
reports on outcomes after various types of heart surgeries. The time on my
end was entirely donated, so I was thrilled to find your gem. Also, I was
also able to resolve the problem from yesterday's message.

Thank you!
Beate

**Comment by ocram** [comment]
Sorry for the problems that you had with the setup, @LimpEmu, but glad that you were able to make everything work! Your list of `require` statements, after having imported the source files for this library *and* the [cookie library](https://github.com/delight-im/PHP-Cookie) and the [database helper](https://github.com/delight-im/PHP-DB), is exactly how to do the setup manually.

Then, @rgvy, thanks a lot for helping and for providing an explanation of how Composer works and what it does – this was spot-on. But as your explanation shows, and the last paragraph about how autoloading becomes crucial as your project grows is really important, Composer really is something that helps you simplify and speed up development. If you were using Composer, @LimpEmu, all this trouble would have been the few seconds of typing

```bash
$ composer require delight-im/auth
```

only. But just as @rgvy does, I can definitely relate to the reluctance to use Composer. But all this is just out of convenience, because Composer is yet another unfamiliar part in the course of the development process where we seek the familiar whenever possible.

As questions about Composer – or often, how to avoid Composer – come up time and again, there's now an introduction to Composer which is also linked in the README:

https://github.com/delight-im/Knowledge/blob/master/Composer%20(PHP).md

I definitely recommend reading it, since it (or rather Composer) is worth the very small (!) effort of becoming familiar with it.

> I have problem remaining that I cannot figure out. It seems to have something to do with dual factor authentication which I will not support (not necessary for this project). For some logon attempts I get the result "attempt cancelled." If I keep trying to logon, at some point, it works, but I am clueless why this issue occurs.

The support for two-factor authentication, which is a recent addition, is definitely something that a lot of projects won't need. But from your description of the problem, @LimpEmu, it seems that you started working with the `tests/index.php` file instead of putting the things that you need together yourself while following the README.

Is that correct? If so, the reason for your problem is that the tests include a [random decision](https://github.com/delight-im/PHP-Auth/blob/6e3728a9187093b73a23600294b8be5f52acf8d8/tests/index.php#L53) of whether "two-factor authentication" should succeed or not. This is not meant for actual use, but only for these internal tests. You just have to remove that part.

> I am not sure this is going anywhere, but in case it is, I would like to express my gratitude for the PHP AUTH library. I have very little experience with PHP, but was able to integrate your authentication mechanism in a website for the California Society of Thoracic Surgeons that reports on outcomes after various types of heart surgeries.

It *is* going somewhere! Thank you so much for letting us know and for showing your appreciation, @LimpEmu – very happy to hear that this library has been helpful to you and for a good cause.

> Also, I was also able to resolve the problem from yesterday's message.

That's great. I assume you've removed that random part, if that was the cause.

**Comment by LimpEmu** [comment]
You are absolutely right in that I used the functions that you provided in
the tests/index.php file as the basis for generating my php files. I did
generate separate php files to cover all the components you had listed in
the read me, that was a very useful check list!
And yes, I realized that you were just randomly deciding to set true or
false for the success of the two-factor authentication, so - as you
indicated - I got rid of that.
So far all is working well, very happy!

Thank you again!
Beate

**Comment by flatsiedatsie** [comment]
> I definitely recommend reading it, since it (or rather Composer) is worth the very small (!) effort of becoming familiar with it.

composer simply isn't always available.

**Comment by ocram** [comment]
@flatsiedatsie It is! Virtually everywhere, at least. Let’s keep this discussion in https://github.com/delight-im/PHP-Auth/issues/90.

**Comment by pixobit** [comment]
Actually it is very easy to write your own autoloader.
First of all what is an autoloader:
Let's say our project consists of 1000+ php files. So in order to have access to all those classes, we would need to include all these files in our project. Well, that doesn't seem too practical... It would be a huge waste to always load everything, even when we don't need it.

So autoloaders basically solve this issue. We don't have to include anything. When we want to use something, and it can't find it, it will trigger the autoloader, and we can tell the autoloader to load the specific file from the specified destination. So it's basically a load on demand mechanism.

In order to write one for this, you would need to separately download all the dependencies:
/Delight/Auth
/Delight/Base64
/Delight/Cookie
/Delight/Db
/Delight/Http

Then just do something like this:
```
spl_autoload_register(function($class_name) {
    $class_name = str_replace('\\', '/', $class_name);
    if(file_exists($path_where_delight_is . $class_name . '.php')) {
        require_once $path_where_delight_is . $class_name . '.php';
    }
});
```
