### ISSUE TITLE
Admin List Users

### ISSUE THREAD

**Issue by marcos-guerrero** [delight-im/PHP-Auth#140]
Hi!
Is it possible to list users? 
With Administration we can create, delete, modify users ... but cannot see how to get a list of users

**Comment by ocram** [comment]
Good question!

This has not been included yet because in most situations, you don’t want only the data from the `users` table of this library, but also some other data that you may have stored in related tables. In addition to that, you may want to sort by different fields, in varying direction, filter by certain criteria, and limit the number of results (while providing an offset).

So a method that would provide the list would have to do a lot and offer many options.

In most cases, it’s easier to just write a single SQL query selecting from your database tables as desired.

**Comment by ocram** [comment]
This is now documented: https://github.com/delight-im/PHP-Auth/issues/201
