### ISSUE TITLE
$auth->logOut(); kills page

### ISSUE THREAD

**Issue by chamster** [delight-im/PHP-Auth#143]
I'm just learning to use PHP-Auth. I'm trying to implement $auth->logOut();

But even if I just add the function call to a simple page, everything after the function calls doesn't get run. Here's an example:

```
<?php
echo"test 1<br /><br />";
require __DIR__ . '/vendor/autoload.php';
$db = new \PDO('mysql:dbname=my_db;host=localhost;charset=utf8mb4', 'root', 'root');
$auth = new \Delight\Auth\Auth($db);
echo"test 2<br /><br />";
if ($auth->isLoggedIn()) 
	{
	$email = $auth->getEmail();
	echo '<h3>You are signed in as '.$email.'.</h3>';
	}
else 
	{
	echo '<h3>You are not signed in.<br />Please sign in.</h3>';
	}		
$auth->logOut();
echo"test 3<br /><br />";
?>
```
This code renders:
Test 1
Test 2
You are not signed in. Please sign in.

Nothing after that. No matter what I do, everything after $auth->logOut(); doesn't happen.

Or if I am logged in, it will show "You are signed in..." but nothing after. And the user stays logged in.

Thanks for any help.

**Comment by ocram** [comment]
That looks like there’s some error that is silently suppressed, so you don’t see it, but it still kills your page.

Could you *temporarily* turn on full error reporting in the browser, e.g. with something like this?

```php
\error_reporting(\E_ALL);
\ini_set('display_errors', 'stdout');
```

You may want to use something like this *anytime* during development, testing or debugging. But of course, it should not be enabled in production.

After that, I guess you’ll see some error message that was previously suppressed. It could be the following, which is a common problem:

“Headers already sent”

In that case, it’s because you must not execute that operation when you have already sent output to the client. So you must either remove any `echo` statement that is before that operation, or you must use something like [`\ob_start()`](http://php.net/manual/en/function.ob-start.php) at the beginning of your script.

Does that help?

**Comment by chamster** [comment]
Thank you for the prompt and informative reply. Yes, of course that was the problem: Headers already sent.

So I'm wondering, what is the preferred practice for implementing the logOut function? Let's say there's a link that says, "Log out." The user clicks on it, then what? Should the link go to a page like logout.php that just logs them out and says, "You're logged out," or should it go to the home page, with a GET variable set like $action = 'logOut', then they get logged out and the home page is displayed instead of some page that just says, You're logged out?

Thanks.
