### ISSUE TITLE
please change storage engine  myisam

### ISSUE THREAD

**Issue by vahidalvandi** [delight-im/PHP-Auth#144]
Myisam to InnoDB
because not work in foreign key

**Comment by ocram** [comment]
Thanks!

We definitely intend to have full InnoDB support *already today*. [This other issue](https://github.com/delight-im/PHP-Auth/issues/137) is about which modifications you’ll need in order to use InnoDB instead.

So with these small changes, feel free to change `MyISAM` to `InnoDB` everywhere.

As for the *default* storage engine, we’ll reconsider in the future whether we should switch from `MyISAM` to `InnoDB`.

**Comment by tmblog** [comment]
I think you should do switch to InnoDB because MyISAM locks full tables as opposed to row level, which can be a bit of a pain? Or is that all taken care of here? Cheers.

**Comment by ocram** [comment]
This library uses MyISAM databases as usual if you have set them up with that storage engine, and this will come with the usual advantages and problems.

As noted in the other issue referenced above, you don’t need many changes to use InnoDB instead, and we will support this.

When it comes to the *default* engine, as noted above, we’ll see if and when we may switch. But, again, you don’t need *us* to switch, you can easily do this already today.
