### ISSUE TITLE
Sign up new users

### ISSUE THREAD

**Issue by tomnuss** [delight-im/PHP-Auth#149]
I have been using PHP-Auth for quite a bit, and it's working great, thanks!

I have a question regarding creating users. My application only allows admins to sign up users (and password recovery is disabled). When a user is created (through $auth->admin()->createUser), the password is set with a randomly generated 15 character string. The username (e-mail) and password are sent to the new user per e-mail. 'confirmEmail' is not used.

When the user logs in for the first time, it is forced to change its password.

The above works fine, but I'm wondering whether this is the recommended way in my use case? 

Sending a 'verify-email'-link for example would still require the user to know its password. And I don't want to use the option to be signed in after verifying the user, and allowing the user to change its password without providing the old password.

**Edit**: While reading the readme again, perhaps the following is more robust: 
- Admin creates a new user with the user's email address, in the background:
1. a random password is chosen (only for the sake of creating the user),
2. password recovery is initiated (through $auth->forgotPassword), 
3. welcome e-mail is sent to the new user, with the recovery $selector and $token
- User chooses password, and signs in

**Comment by ocram** [comment]
The latter solution, which you added in the edit, looks totally fine, doesn’t use any library functions for unintended purposes, and seems to be superior to the one proposed at the beginning.

It doesn’t require you to send the (temporary and random) password to the user, doesn’t require the user to type or copy that password, and doesn’t need a “force password change” function, which you would have to implement with checks throughout your application and UI.

Does that solve the problem for you?

**Comment by tomnuss** [comment]
Great, thanks for confirming!

**Comment by tomnuss** [comment]
Just have an additional question while implementing the 'latter solution', with 'password recovery'.

It seems the rate limit of 'password recovery' is more strict than creating a user. As a result, the user is successfully created, but when subsequently $auth->forgotPassword is initiated the rate limit kicks in after creating a few users. 

I'm aware of the option to disable rate limiting, but I don't want to disable throughout my whole application. Is there any way to disable rate limit only for $auth->forgotPassword? Or increasing the limit only for forgotPassword?

As an alternative I could truncate 'user_throtteling' each time a new user is created. Since users are not created too often, the security disadvantages of this should be acceptable.

**Comment by tomnuss** [comment]
Sorry, I guess I can also just set $auth again (although set before in the code as well), and then create the user and initiate password recovery. In that case with the false parameter as fourth argument ($auth= new \Delight\Auth\Auth($db_auth, NULL, NULL, false)).

**Comment by ocram** [comment]
Thanks, very good point.

We hadn’t thought about the rate limits for password recovery, as that feature had obviously not been intended for this purpose, although it works quite well, as we have discussed.

Another thing that this library has not been designed for or tested with is multiple instances being used side-by-side (or in sequence).

We would recommend the following three solutions in that order, depending on which one is technically possible for you:

 1. Even before creating the first (and only) `Auth` instance, detect whether throttling or rate limiting should be enabled based on the type of the request. Example: If you are in `admin/createUser.php`, when it comes to creating the instance, you know that rate limiting should be turned off. This does not introduce any risk because that entry point does not allow for any other actions, e.g. logging in, and can only be used by admins who are already authenticated.
 2. Execute `TRUNCATE TABLE users_throttling` whenever you create an account as an administrator, if that’s really something you do rarely (e.g. not more than once every few hours).
 3. Create two instances, one with rate limiting enabled for normal usage and one with rate limiting disabled in order to create users as an admin.

**Comment by tomnuss** [comment]
Thank you. Option 2 then seems the best workaround in my case.

And fully understood that it is not intended for this purpose. For that same reason, I will manually update the expiry value in the 'users_resets'-table, since it now set to 6 hours - which makes sense if a user requests for a password change, but not so much if a new user doesn't necessarily expects a welcome email with an invitation to confirm.

**Comment by ocram** [comment]
You should be able to specify the expiry in the third parameter of `forgotPassword`. Can you try `60 * 60 * 24 * 7` or something like this? Again, that would be something you’d only want to have in the version for admins creating accounts. So it would require the detection of the request type again, as described in (1) of my previous comment. Are you sure that is not possible?

**Comment by tomnuss** [comment]
Setting the third parameter works! Thank you. Only admins are allowed to create accounts, and there is no password recovery option for users themselves, so this is a great solution.

**Comment by ocram** [comment]
That’s great, glad it works. That option was not documented before, so this has just [been added](https://github.com/delight-im/PHP-Auth/commit/4b3f2ab91c52958d1ae21651679372c3d3b2a0b3).
