### ISSUE TITLE
DB agnostic? Requires mysql...

### ISSUE THREAD

**Issue by dougcassidy** [delight-im/PHP-Auth#15]
Hi there, I'm not sure what you mean by db agnostic, if there is a requirement for mysql.  I see that you pass a pdo instance to the class; can i use a pdo instance of sqlserver?

**Comment by ocram** [comment]
Thanks for your feedback on this!

> if there is a requirement for mysql

There is none! Yet MySQL is *currently* the only system that the library is continuously tested against, where full support is ensured and where the SQL file for creating the schema is published in this repository.

> I see that you pass a pdo instance to the class; can i use a pdo instance of sqlserver?

In theory, yes, absolutely! In practice, there may be some things that don't work since the library is not tested against SQL Server.

The first step that is required for SQL Server support is converting the `Database/MySQL.sql` file (which contains the schema) to a variation that works for SQL Server, due to the small differences in features and syntax. If you could do this for yourself, or if you are willing to contribute this here, that would be awesome.

If you encounter any bugs then, we're definitely willing to fix them so that SQL Server can be used instead of MySQL by simply switching the PDO instance.

**Comment by ocram** [comment]
An explanation has now been added to the README as well: https://github.com/delight-im/PHP-Auth/commit/0e2279ecdae53f12fd251659e46eb03228e633b0

Sorry for the confusion!
