### ISSUE TITLE
Multiple same emails registration

### ISSUE THREAD

**Issue by Lagily** [delight-im/PHP-Auth#152]
Hello

I am able to register multiple users with the same email that already exists, how come that is possible? Is it because of Email activation being active?

When a registered user activates his email however it seems like the wrong user gets logged in (the first user in the table with that email)

**Comment by Lagily** [comment]
Also how can we check if a user is currently confirming his email? As in so we can show that he needs to confirm his email still. e.g after calling changeEmail().

**Comment by ocram** [comment]
What database software are you using? And what schema did you import? Did you create one yourself? Or modify an existing schema?

All included schemas have a `UNIQUE` constraint on the `users.email` column, so what you describe really shouldn’t be possible with a correct setup.

Your second issue, i.e. the wrong user being logged in, is a direct result of the first issue.

And with regard to your question (from the second comment), there are two types of pending confirmations. One after sign up, and one after an email change. In the first case, you will know because you get `EmailNotVerifiedException`. As for the second case, there has not been a need for this and no requests for such a feature so far, so that feature does not exist.

**Comment by Lagily** [comment]
But that being UNIQUE means that if someone TRIES to sign up with an email, but does not actually activate it will still give all other users no more option to sign up with this email... how is that secure in any way?

**Comment by ocram** [comment]
You did not answer the questions. So did you remove that `UNIQUE` constraint?

The problem you describe has many possible solutions. The legitimate owner of the address can just request a new confirmation and “take over” the account, you could delete accounts that have not been activated after a certain period of time, etc.
