### ISSUE TITLE
session_regenerate_id()

### ISSUE THREAD

**Issue by crysan** [delight-im/PHP-Auth#153]
Hi!
If after sending data to login execute code
`app()->auth->login($_POST['email'], $_POST['password']);`
then, the login is executed, but immediately leaves the login.

If you run the code
`app()->auth->login($_POST['email'], $_POST['password'], true);`
then login is performed, but an error immediately appears
`Warning: session_regenerate_id(): Session object destruction failed. ID: files (path: c:/ospanel/userdata/temp/) in C:\OSPanel\domains\test2\vendor\delight-im\cookie\src\Session.php on line 66`

Was reading
https://github.com/delight-im/PHP-Auth/issues/77
https://github.com/delight-im/PHP-Auth/issues/4
did not help

PHP Version 7.2.10
System | Windows NT HOMEPC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64
Architecture | x64

I ask for your help!
Thank!

**Comment by ocram** [comment]
Did you perhaps set a custom session handler via the `session.save_handler` configuration option or via the `\session_set_save_handler` function? Looking at the warning message, it seems that’s not the case.

What about your session storage path then? What’s the output of `\var_dump(\ini_get('session.save_path'));` or `\var_dump(\session_save_path())`? Is that `c:/ospanel/userdata/temp/`? Is that directory writable by the web server?

Anyway, all this only happens if you provide a *third* parameter to `Auth#login`. But apparently, there are other problems if you *remove* that third parameter, right?

When you say “the login is executed, but immediately leaves the login”, does that mean that you cannot really log in because that login is immediately forgotten again and thus not persistent?

**Comment by crysan** [comment]
I tried everything you can.
It helped only when the server rolled back from PHP 7.3 to PHP 7.1.
On PHP 7.2, the error persisted.

**Comment by ocram** [comment]
Could you answer some of the questions from the comment above perhaps?

It’s good to know that the problem appears to occur on PHP 7.2 and 7.3 while everything is fine on PHP 7.1 – but this could also be a configuration issue.

**Comment by crysan** [comment]
1,2. No
https://yadi.sk/i/DRW9n6FaVMzB4w

3. Anyway, all this only happens if you provide a third parameter to Auth#login. But apparently, there are other problems if you remove that third parameter, right?
If there is no third parameter, then everything stops working. But somehow strange.
I make a login. A session file with all the data is created. I turn to another page and create a new empty session file. And there is no exit code from the login and the end of the session at all.

**Comment by ocram** [comment]
Sorry, we can’t reproduce this and don’t have sufficient information to investigate further.

If you have new details, please feel free to share these here.
