### ISSUE TITLE
Best way to make email field optional?

### ISSUE THREAD

**Issue by rstmsn** [delight-im/PHP-Auth#155]
What's the cleanest way to make the email field optional at registration?

**Comment by ocram** [comment]
Well, you need *some* kind of an identifier, right? This library has – as have many websites – decided to use email addresses as an identifier.

If you just want to use something else (e.g. phone numbers) instead of email addresses, you may find [this issue](https://github.com/delight-im/PHP-Auth/issues/106) helpful.

If you don’t want *any* identifier, how should that even work? Can I create five accounts with a single email address? Which one will be logged in if I enter my email address (and at least some of the accounts share the same password)?

Or do you want to allow registration and login with just a password (and nothing else)?

**Comment by rstmsn** [comment]
> Well, you need some kind of an identifier, right? This library has – as have many websites – decided to use email addresses as an identifier.

Sure - I agree with most of what you're saying, however, most privacy focused platforms will choose not to retain a users personal information. In this instance, using `username` as the unique identifier is the prefered option. [Note that this requires the possibility of `email` == null].

**Comment by ocram** [comment]
I see. That makes sense. Can’t you just do what you suggested, i.e. using a unique username instead? This can be done using `Auth#registerWithUniqueUsername`. As for the email address, which is *technically* required to date, how about generating some internal value randomly, e.g. `ebdeb1cc-7ae3-4919-8146-05179479d548@localhost` (using a UUID or other random value)?

**Comment by rstmsn** [comment]
> how about generating some internal value randomly

That's pretty much the conclusion I had come to. At least taking this approach will avoid having to make any modifications to the auth library. 
Thanks for the info & the librarys, they rock.

**Comment by ocram** [comment]
Thanks for your appreciation!

Yes, this approach is the recommended one because it doesn’t require any changes to the library and thus you’ll continue to be able to apply updates in the future with a single command.
