### ISSUE TITLE
Error after session has expired

### ISSUE THREAD

**Issue by bleutzinn** [delight-im/PHP-Auth#159]
I've successfully implemented logging a user in and out.

The problem is that when the session has expired and the homepage (or any other page is requested), I get this error:
```
Delight\Auth\DatabaseError: SQLSTATE[HY000]: General error: 1 no such table: users in file /fs_path/vendor/delight-im/auth/src/Auth.php on line 165
Stack trace:
  1. Delight\Auth\DatabaseError->() /fs_path/vendor/delight-im/auth/src/Auth.php:165
  2. Delight\Auth\Auth->resyncSessionIfNecessary() /fs_path/vendor/delight-im/auth/src/Auth.php:56
  3. Delight\Auth\Auth->__construct() /fs_path/vendor/delight-im/foundation-core/src/App.php:93
  4. Delight\Foundation\App->__construct() /fs_path/index.php:77
```

Based on the default `HomeController` class the homepage shows the login state:

```
class HomeController
{

    public static function getIndex(App $app)
    {

        $auth = Utils::getAuth($app);

        if ($auth->isLoggedIn()) {
            echo 'User is signed in';
        } else {
            echo 'User is not signed in yet';
        }
        // and return a view
        echo $app->view('welcome.html.twig', [
            'users' => ['Alice', 'Bob'],
        ]);
    }

}
```

BTW the `getAuth()` function is in a new separate class named `Utils`:

```
class Utils extends App {

	public function getAuth(App $app)
	{
		$db = new \PDO('sqlite:' . $app->getStoragePath('/db/sf_users.sqlite'));
		return new \Delight\Auth\Auth($db);
	}
}
```

What am I doing wrong? Thanks in advance for your help.

**Comment by ocram** [comment]
The error message in the stack trace is pretty precise in this case, isn’t it?

> SQLSTATE[HY000]: General error: 1 no such table: users

Are you sure there’s really a table named `users` in your SQLite database `/db/sf_users.sqlite`?

By the way, if this is using [PHP-Foundation](https://github.com/delight-im/PHP-Foundation), don’t the helpers `$app->db()` and `$app->auth()` work for you? It’s probably because you want to use SQLite and the framework does not support SQLite, right? In order to fix this, could you open `config/.env` and add a custom configuration value `DB_FILE_PATH="/db/sf_users.sqlite"`? Then open `vendor/delight-im/foundation-core/src/App.php` and, after `$dataSource->setPort($_ENV['DB_PORT']);`, add `$dataSource->setFilePath($_ENV['DB_FILE_PATH']);`. Does that make `$app->db()` work for your SQLite database?

**Comment by bleutzinn** [comment]
The error message is clear but it's simply not true. The database does include all tables. New users are added to that table too. Actually, I think, the message should be that it can't connect to the database at all.

Yes, I'm using PHP-Foundation and in the [Requirements](https://github.com/delight-im/PHP-Foundation#requirements) the docs state: "MySQL 5.5.3+ or MariaDB 5.5.23+ or PostgreSQL 9.5.10+ or SQLite 3.14.1+". So I wasn't aware the framework doesn't work with SQLite out of the box.
Thanks for the pointers to make it work; using SQLite is a pretty firm requirement (no need to install a db and ease of full backups).

I modified the files `config/.env` and  `vendor/delight-im/foundation-core/src/App.php` as you described. The db is in `storage/app/` so I used `$dataSource->setFilePath($this->getStoragePath($_ENV['DB_FILE_PATH']));`
A `var_dump($datasource);` shows that the file path is correctly set.

However, even before I can use `$app->db()` or `$app->auth()` in a controller I get the before mentioned error.

**Comment by ocram** [comment]
> So I wasn't aware the framework doesn't work with SQLite out of the box.

Sorry, all this has definitely been miscommunication on our part. Let me clarify this: The framework *does* work with SQLite in the way you used it, i.e. when you create your own PDO instance in `Utils#getAuth`. But we think there’s a better way to set up your database instances.

So in our framework, the recommended way is that you configure the `DB_...` environment variables in `config/.env` and then the framework takes care of creating and re-using the database instances for you automatically. So you never call `new \PDO(...)` yourself.

This is what is our preferred solution, and with your report, it became obvious that the framework does not support this for SQLite yet. Still, the note claiming SQLite support is there, as you mentioned, which is bad communication on our part again.

The steps I described earlier were intended to make the efficient database instance setup and usage available for you with SQLite as well. But the instructions were insufficient, because some more code changes in the framework were required, which have just been applied.

So please run

```bash
$ composer require delight-im/foundation-core
```

in the root directory of your project (where the `composer.json` file is) to update the framework to (at least) version `v4.4`.

Then update your `config/.env` to look like this:

```
DB_DRIVER=sqlite
DB_HOST=
DB_PORT=
DB_FILE_PATH=storage/db/sf_users.sqlite
DB_IN_MEMORY=0
DB_NAME=
DB_USERNAME=
DB_PASSWORD=
DB_CHARSET=
DB_PREFIX=
```

If you have this, you shouldn’t ever need to call `new \Delight\Auth\Auth(...)` yourself, either, and you can probably remove `Utils::getAuth($app)`. Instead, you just use `$app->auth()` (and `$app->db()`) everywhere.

> Thanks for the pointers to make it work; using SQLite is a pretty firm requirement (no need to install a db and ease of full backups).

Sure, SQLite is excellent software and we will definitely (continue to) support it.

**Comment by bleutzinn** [comment]
There's no need for apologies. Nobody and nothing is perfect though I sense you do strive for perfectness. I've never encountered such a high standard in responses to issues than yours. You are swift and your help is very comprehensive and clear. Kudo's, many kudo's.

Also I'm delighted ;) to say version 4.4.0 of [PHP-Foundation](https://github.com/delight-im/PHP-Foundation) works like a charm with my Sqlite database. Many thanks for the full support of Sqlite!
