### ISSUE TITLE
Inactive Users

### ISSUE THREAD

**Issue by rgvy** [delight-im/PHP-Auth#16]
Hello

First I'd like to express my appreciation for these very simple and extremely elegant libraries.

My question or suggestion relates to making users inactive. Rather than deleting rows, it is often preferable to set a flag for "isDeleted" or "isInactive". Storing such a column in another Users_Data table (e.g. Users_Profiles) might cause poor performance because of the join (especially when also joined with a User_Posts or User_Votes table). Would an "activeStatus" column be a candidate to be added to the main Users table in a schema update? I see you're careful to avoid bloat, but I just thought I'd suggest this. Alternatively, would it be bad form to combine this functionality with the suggested Roles feature?

Perhaps a workaround in the meantime would be to append or prepend an invalid ASCII string to the email column. Something like [[@@]] that isn't allowed in email addresses. It should still be able to query active users simply and quickly.

**Comment by ocram** [comment]
Thanks a lot for your feedback and appreciation!

> My question or suggestion relates to making users inactive. Rather than deleting rows, it is often preferable to set a flag for "isDeleted" or "isInactive".

You're right, that's still missing and we should definitely add it.

> Storing such a column in another Users_Data table (e.g. Users_Profiles) might cause poor performance because of the join (especially when also joined with a User_Posts or User_Votes table).

Yes, that should really be something that the library does, and not something that you have to implement in your own code (and database schema).

> Would an "activeStatus" column be a candidate to be added to the main Users table in a schema update?

Absolutely! We could add a new column named `deleted_at` to the `users` table. Using a new administration interface, this attribute could be set using `$auth->admin()->deleteUser(int $userId)`, which would be an alias of `$auth->admin()->softDeleteUser(int $userId)`. In contrast, a new method `$auth->admin()->hardDeleteUser(int $userId)` could actually delete the row. When trying to sign in, etc., there would be a `UserDeletedException` if that user has been "soft-deleted". If the user has been "hard-deleted", on the other hand, there will be a "not found" exception, just as there is today.

Is this an acceptable solution?

On the other hand, perhaps someone might need to mark accounts as inactive while still allowing the respective users to sign in (with a limited feature set and/or warnings). What do you think?

For that purpose, we could add another new column to the `users` table which would be named `suspended_at`. Using another new administration interface, this could be set using `$auth->admin()->setUserSuspended(int $userId, bool $suspended)`. A suspended user would still be able to sign in but the individual status would be available via `$auth->isSuspended()` after login.

Is that something that you (or others) might need? It's easier to add both new attributes *now* than to add one of the attributes now and the other one later, resulting in additional breaking changes. But in order to avoid bloat, it would be better to go without that attribute if it was needed rarely, given that we added the `deleted_at` attribute already.

Anyway, just like the roles feature in https://github.com/delight-im/PHP-Auth/issues/13, this would be a breaking change due to the required database modifications, so we can include this in the next major release only.

**Comment by rgvy** [comment]
I love the idea for the admin interface to the auth!

May I suggest instead of 2 columns for a timestamp of account suspension and deletion, using 1 column for the account status? I would think that significant events could be logged elsewhere and this reduces the column count. Additionally, it might provide other useful functionality-- now that I think about it, there may be many different states for an account. For example:
- Active
- Deactivated (by user, temporarily)
- Suspended (by admin due to terms violation)
- Delinquent (user has not paid a bill)
- Pending (user has applied for an account but it is not yet approved)
- Deleted (permanently)
- Duplicate

Of course now we are in danger of feature creep. I appreciate the difficulty in keeping this framework lean. This is just my suggestion. I think it allows flexibility for implementors while not doubling the work of logging events (which may be handled by a different robust and dedicated framework). 

I am new to GitHub and do not yet understand the etiquette for collaboration. If there's something I can do to help, please let me know.

Thanks again, and I look forward to using this excellent framework in my new project!

**Comment by ocram** [comment]
Good points!

We'll use a single status field (`TINYINT(2) UNSIGNED` in MySQL), whose possible values are stored in PHP constants, instead of multiple timestamps for different attributes.

To begin with, the set of possible values will include:

```
ACTIVE (default)
ARCHIVED
BANNED
LOCKED
REVIEW
SUSPENDED
```

That list should contain the states that most people will need. And with that solution, everybody can decide for themselves how to handle the individual states.

By the way, I don't really see the use case for `duplicate`. Is that really required?

**Comment by rgvy** [comment]
That list is great! I really appreciate the terminology you choose in these libraries.

I agree that `duplicate` is redundant with `archived`.

Looking forward to using it!

**Comment by ocram** [comment]
This feature has now been added. It has been implemented in the following commits:

 * https://github.com/delight-im/PHP-Auth/commit/d9dccf8100230cccb2b7d0e60ca45e0b1441c2d5
 * https://github.com/delight-im/PHP-Auth/commit/a05d277a2c1d09c08fcee56aabc124320b5f6819
 * https://github.com/delight-im/PHP-Auth/commit/9a0036b8a86827c82c9d42efa10b30532b5b55e8
 * https://github.com/delight-im/PHP-Auth/commit/93477e4e7e9d8ce54167c750734efdbaa2f5a8f1
 * https://github.com/delight-im/PHP-Auth/commit/89a7af17fe7ecd87daa8c249acdad3d54ce017d1

Right now, you have to update the `status` column in the `users` table yourself. But support for convenient operations that perform such updates will be included in the `Administration` class soon.

Please note that this is a breaking change due to the required database changes. If you're upgrading from an earlier version of this library, you should take a look at our migration guide.
