### ISSUE TITLE
change email not working while user is logged in

### ISSUE THREAD

**Issue by meshachviktor** [delight-im/PHP-Auth#160]
i am able to create new users, and keep them signed in but the changeEmail() function fails for some reason, even when TooManyRequestsException is not the problem. The reconfirmPassword() works as i always see the 'password confirmed' message but the email in the users table never gets updated. 
here's my code:

`include_once 'php-auth-init.php';`
`function php_auth_change_email() {`
`       global $auth;`
`	try {`
`		if ($auth->reconfirmPassword('password')) {`
`			echo 'password confirmed';`
`			$auth->changeEmail('prunedges@gmail.com', function($selector, $token){});`
`		}`
`	} catch (\Delight\Auth\InvalidEmailException $e) {`
`		die('Invalid email address');`
`	} catch (\Delight\Auth\UserAlreadyExistsException $e) {`
`		die('Email address already exists');`
`	} catch (\Delight\Auth\EmailNotVerifiedException $e) {`
`		die('Account not verified');`
`	} catch (\Delight\Auth\NotLoggedInException $e) {`
`		die('Not logged in');`
`	} catch (\Delight\Auth\TooManyRequestsException $e) {`
`		die('Too many requests');`
`	}`
`}`
`php_auth_change_email();`

**Comment by acodispo** [comment]
The following is based on my recollection from implementing this feature in my own application.

The changeEmail function needs to send an email to the *new* email address, so that the user can confirm that email address. Once the confirmation URL has been visited, *then* the new address will become that user's address.

Check the example under: https://github.com/delight-im/PHP-Auth/#changing-the-current-users-email-address

Especially starting at line 2:

```php
if ($auth->reconfirmPassword($_POST['password'])) {
     $auth->changeEmail($_POST['newEmail'], function ($selector, $token) {
         echo 'Send ' . $selector . ' and ' . $token . ' to the user (e.g. via email to the *new* address)';
     });
     echo 'The change will take effect as soon as the new email address has been confirmed';
}
```

And then the verification email has to direct them to a page built using these directions: https://github.com/delight-im/PHP-Auth/#email-verification

**Comment by meshachviktor** [comment]
okay. when i saw 'if a user is currently logged in' in the documentation it made me think that there is an option to change the email address without needing a confirmation. thanks. i will go and implement the confirmation feature.

**Comment by ocram** [comment]
@meshachviktor Thanks for this good question!

@acodispo Thanks a lot for your help! Your answer was perfect.

So the problem is really

```
function($selector, $token){}
```

which cannot work, because the function is empty and does not implement the usage of the selector and token.

No matter if the user is currently signed in or not, we need to confirm that the *new* email address actually belongs to the user, so that’s why the confirmation is required.
