### ISSUE TITLE
Pass ID to new user registration

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#179]
Hello there, I am using this library in addition to my own tables namely customer table. I allow guest checkouts to happen in this case there isn't a need for the user to have any login credentials but if they decide to register they can. 

I have looked at Additional user information section though, this looks like a user needs to be created first then the id passed to create additional info, is there a possibility to pass a user ID to the user table when registering because in my logic the customer is created first then the user, if only they decide to create an account?

Any help appreciated.

**Comment by ocram** [comment]
Thanks, good question!

First, your setup and your processes absolutely make sense. And your understanding of the recommended way to store additional user information (as per the “Additional user information” section) is also correct.

Now, in your case, this must indeed be solved in a different way.

But creating an ID yourself (for your custom tables) and then passing that ID to this library does not work and is not how this should be done.

Instead, you must choose a different attribute to associate the record from this library’s table with the records in your custom tables.

The key question is: How do you identify users in your custom tables, i.e. when the user decides to sign up for an account, how do you know which records in your custom tables belong to that user?

Do you collect an email address during the guest checkout? Or do you store in your session which rows belong to the current user?

For example, if I decide to sign up for an account on your site now, and in your custom table there are hundreds or thousands of records, how do you know which of those belong to me and my new account?

**Comment by tmblog** [comment]
Hey thanks for the reply,. So there is a `customer` table which contains the fields: 
`customer_id, customer_name, customer_email, customer_phone, customer_type`

In my php logic if the user chooses **create an account** then the tables from `delight/auth` should get populated after the customer is created. The relationship is 1:1 from the `customer` to `users` table. There are no natural key candidates so `customer_id` is the primary key, so to answer your question the relationships are built using the `customer_id` e.g. `customer.customer_id = users.id`. And yes the data is stored in session at the time of insertion along with the fields required for users table e.g. `password` if they want to create an account.

The reason I need to pass the `customer_id` is simply because there will be customers who are guests without any login credentials and some who do have accounts.
`users.id` is autoincrement and so is `customer_id` so at some point there will be an existing key for the customer table because there'll be more `customer_id` than `users.id` if that makes sense.

I can't think of any other keys because the user can change their emails so that won't work. The other way I can think of is I always create a user account and delete it if the user decides to guest checkout. But that seems inefficient. 

Hoping that clarifies more, and thanks again for your input on this!

**Comment by ocram** [comment]
Thanks for the additional details.

I think the answer to the most important question is not really clear yet:

A user has performed a guest checkout, and so your `customer` table contains some data, including a customer ID and an email address (verified or not?). Now the user decides to create an account as well. How do you know which ID you would want to pass in to this library? Do you store the customer ID in the session?

Or do you just use the last customer available? In that case, if another user performs a guest checkout in the meantime, you would wrongly pick their ID, right?

**Comment by tmblog** [comment]
Ah yes, I see what you mean. This is all done at once e.g. the `lastinsertid` from customer table will be the foreign key. The email remains unverified.

When checking out the user checks a box `create account` in this case the account is created else the customer is just created without any accounts. The user cannot come back in the future and claim old order data. So all this happens there and then.

Hope that clears it up, cheers once again!

**Comment by ocram** [comment]
> This is all done at once

Well, why can’t you just switch the order then and create the user first, using their ID as a foreign key in the customer’s record? Previously, you said the customer is created first, not that both are created at once.

> the lastinsertid from customer table will be the foreign key

So that must either be assigned to the user in the same request, or temporarily stored in the session. If it’s done in the same request, why can’t you either swap the two creation statements *or* update the customer record with the user ID as soon as you have that?

> When checking out the user checks a box create account in this case the account is created else the customer is just created without any accounts.

Thanks, that is helpful. Where does the password come from? Is it auto-generated or is the user asked for it as well?

> The user cannot come back in the future and claim old order data.

Makes sense.

**Comment by tmblog** [comment]
Ok so the problem is every user is a customer but not every customer is a registered user. So this is the reason I cannot create a login first, if the user doesn't want an account they just want to order just this once then they are a guest user without an account.

> Well, why can’t you just switch the order then and create the user first, using their ID as a foreign key in the customer’s record? Previously, you said the customer is created first, not that both are created at once.

It happens at the same time if only the user says they want to create an account. There is a mechanism to produce passwords which is supplied. If not then he is just a customer without any login credentials. 

The reason I need users.id to be the foreign key is because inevitably there is will be a clash of primary keys which will disallow relationships. 

Would appreciate if you could point a way to pass an id to the table instead of autoincrement or a work-around.
Thanks again!

**Comment by ocram** [comment]
> Would appreciate if you could point a way to pass an id to the table instead of autoincrement

That’s really not the way to go. There are better ways.

> Ok so the problem is every user is a customer but not every customer is a registered user.

Sure, I got that.

But I still don’t understand why you can’t do the following?

 * User wants to use guest checkout?
   1. Create row in `customers` with `customers.user_id` set to `null`
 * User wants to sign up for an account?
   1. Create row in `users`
   1. Fetch the last auto-increment ID for `users.id`
   1. Create row in `customers` with `customers.user_id` set to the ID from the previous step

Even if that didn’t work (for whatever reason), couldn’t you do the following?

 * User wants to use guest checkout?
   1. Create row in `customers` with `customers.user_id` set to `null`
 * User wants to sign up for an account?
   1. Create row in `customers` with `customers.user_id` set to `null`
   1. Fetch the last auto-increment ID for `customers.id`
   1. Create row in `users`
   1. Fetch the last auto-increment ID for `users.id`
   1. Update row in `customers` so that `customers.user_id` becomes the ID from the previous step (where `customers.id` has the ID from the second step)

**Comment by tmblog** [comment]
Hey Marco, really appreciate the time you're taking to help out. OK I guess your way with an additional field could work but it'd violate 3NF by having null values which is what I was trying to avoid. I'll see if I can find another logic without having to resort to null values. Please do also let me know your thoughts on my comment. Peace!

**Comment by ocram** [comment]
> OK I guess your way with an additional field could work but it'd violate 3NF by having null values which is what I was trying to avoid.

So you’re trying to avoid `NULL` values in all places of your database? Well, while that may satisfy the formal requirements of the normalization schemes, it’s neither an industry best practice nor otherwise any common pattern used in practice.

> I'll see if I can find another logic without having to resort to null values.

I’m sure one of the two solutions proposed above is the cleanest solution possible here, and both are certainly cleaner than feeding arbitrary IDs into an existing database scheme and library that otherwise use auto-incrementing IDs.

Since we have a practical solution now, I’m going to close this issue.

> Please do also let me know your thoughts on my comment.

What comment are you referring to? The 3NF one?

**Comment by tmblog** [comment]
Thanks for your input, it is important for some including me to stick to the formalities of relational databases. Hence the reason to be very rigid, this is by no means disrespecting your good solutions which I very much appreciate!

Just dropping by to say that, if anyone else has a similar model. The way I have overcome this is by creating a composite key in the customer table with the `customer_type` and `customer_id` fields. This way there will never be a duplicate key issue. Hope it helps someone.
