### ISSUE TITLE
Password reset ("forgot password")

### ISSUE THREAD

**Issue by Paulo--M--** [delight-im/PHP-Auth#181]
I'm not sure if this is the proper place to ask the question but I've been searching for help for a while and I keep drawing blanks. Please redirect me if there is a more appropriate place.

First of all, thank you for the excellent code. I'm trying to implement the various features of PHP-Auth and everything is pretty straight forward. Great!

Well, everything except the _**Password reset ("forgot _password")**_ bit... :-) Can someone tell me where I can read a bit more about this feature and how to properly implement it? I have read through the available documentation here and I'm completely lost as to where $selector and $token come from and how to get "Step 1 of 3: Initiating the request" working -- can some kind soul show me a working example or explain in more detail how things should work?

Many thanks in anticipation.

**Comment by ocram** [comment]
Thanks for your question!

The README of this project is really all there is when it comes to documentation. But it is fairly extensive, so we think it should cover most features and needs.

Let’s just address your specific questions here and tell us if there’s anything else you want to know.

Step 1 of 3 is done exactly as shown in the README:

```php
$auth->forgotPassword($_POST['email'], function ($selector, $token) {
    // send $selector and $token (function arguments received here) to the user (e.g. via email)
});
```

So you’re calling `Auth#forgotPassword`, passing in the email address of the user and an anonymous function or closure that accepts two parameters.

This is also how you get the selector and token.

Then, the README recommends that you build a URL with these two values and send it to the user, e.g. via email:

```
$url = 'https://www.example.com/reset_password?selector=' . \urlencode($selector) . '&token=' . \urlencode($token);
```

Next, you receive the two values again when the user clicks the link, and you check whether they are correct or not:

```php
$auth->canResetPasswordOrThrow($_GET['selector'], $_GET['token']);
```

Does that help?

**Comment by Paulo--M--** [comment]
Thanks for the feedback. It is much appreciated.

I have been reading through the README -- also because of that, my question referred specifically to "Step 1 of 3" :-)  I agree that it covers a lot and my request for further help is probably just dictated by the fact that I'm not a true programmer...

Meanwhile I had made a few trial-and-error attempts and I think that I may have answered my own question: the variables $selector and $token need to be created in my script, correct? I also see that encrypted versions end up in the table 'users_resets' (and I understand that this is necessary for step 2, to check that the received values are valid). For my own curiosity, what is their purpose, why the name 'selector', and why are both values encrypted?

I have one more question. If I have several pages (say, pageA, pageB or pageC) from which a user can potentially request a password reset, would it be possible to "store" the "origin page" somehow? So that, once the password is reset, the user is automatically sent to that "origin page".

Many thanks for reading all this.

**Comment by ocram** [comment]
Happy to help! Regarding your questions, no problem. You know, there are no stupid questions and no true or false programmers.

> the variables $selector and $token need to be created in my script, correct?

Well, not really. In your call to `Auth#forgotPassword`, as explained earlier, you pass in an anonymous function as the second argument. In that function declaration, you also declare these two variables, but the actual values you will get are created by the library and you just receive them in that function. Try printing or logging them inside of that anonymous function.

> I also see that encrypted versions end up in the table 'users_resets'

Yes, at least for the token. To be specific, they are *hashed*.

> and I understand that this is necessary for step 2, to check that the received values are valid

Yes, when generated, these values are inserted into that table. And when received later, after the user has clicked the link, they are looked up and compared using that table.

> For my own curiosity, what is their purpose, why the name 'selector', and why are both values encrypted?

Both are random strings, and only the token is hashed.

That is because, first, you don’t ever need the token in non-hashed form, just as it is the case with user passwords. You will only ever need to compare them, and for that purpose, hashes are sufficient.

Second, it provides a little extra security, because these tokens are (almost) as valuable as passwords for attackers, since they provide access to the account. That is only relevant in specific scenarios, of course, i.e. when the attacker somehow got access to the database (perhaps read access to a dump file only) and wants to log in to specific accounts.

The selector is named that way because it is used to select the row in the database, while the token is only compared (using the relevant rows). The fact that both are required separately and not just combined to a single value is just because it was implemented in that arbitrary way and we didn’t find the time to rewrite everything for a single value yet.

> If I have several pages (say, pageA, pageB or pageC) from which a user can potentially request a password reset, would it be possible to "store" the "origin page" somehow? So that, once the password is reset, the user is automatically sent to that "origin page".

While you may link to your password reset page from multiple pages, you usually have only one page for the password reset. But assuming you really need multiple pages, the library does not provide a way to remember the page where the request originated. You could, however, easily store this yourself in your own code, e.g. in `$_SESSION['passwordResetOriginPage']`, or in a cookie, or in a custom database table.

**Comment by Paulo--M--** [comment]
Thank you **very much** for the kind and helpful feedback. It is very generous and much appreciated. I will report back here after I have "studied and done a bit of homework"... ;-)

Regarding my final question, I'm also planning on having a single password reset page; however, the request itself may originate from different pages and I would like to send the user back to his/her original page after the password has been reset. I will cook something up, either with a cookie or a DB table -- it's not top priority at the moment. First, I would like to get your PHP-Auth working flawlessly :-)

Thanks again.

**Comment by Paulo--M--** [comment]
I have read, I have done my homework, and I have learnt... :-) All seems to be proceeding in the right direction. I just wanted to thank you again for the kind and thoughtful feedback; it was very helpful and is very much appreciated. If I were to need additional assistance, I'll come back knocking on this door again.

**Comment by ocram** [comment]
> I just wanted to thank you again for the kind and thoughtful feedback; it was very helpful and is very much appreciated.

You’re welcome!

> I would like to send the user back to his/her original page after the password has been reset. I will cook something up, either with a cookie or a DB table

You could also use `$_SESSION`, or even append the source URL to all paths, e.g. `/forgot-password?next=/details/42` and `/reset-password?next=/details/42`. But if the user clicks that link later, they may not want to go back to *that* page anymore. So the session data or cookies might be better solutions.

> Is there a simple way to determine the email address from a (valid) ‘selector’ / ‘token’ pair? I mean, I know that I can query the database joining 'users_resets' and 'users' but I was wondering if there was a builtin function that already does this...

There is none yet, no. This has never been requested, but I guess you’d like to display the user’s email address so that they know which account their resetting the password for, or just to personalize the experience, right?

Right now, the recommended solution for you would indeed be to join these two tables and search for the selector.
