### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by draxm** [delight-im/PHP-Auth#184]
I am looking to contribute but i do not know what coding style you prefer because i want to make sure i follow your standards so it's easier for you. If you have a specific coding style what is it?

**Comment by ocram** [comment]
Sorry for the long delay – what a great way to welcome a potential contributor!

In case you are still interested: There’s no specific (named) coding style, but new could should roughly match what is already there as far as the style goes. Further, as the README notes, we’d like to discuss any contribution before it is done, in order to save all sides from unnecessary extra work.
