### ISSUE TITLE
Would it be better not to be able to change email address based on password?

### ISSUE THREAD

**Issue by draxm** [delight-im/PHP-Auth#185]
Reasons for why this is because if someone cracks a password to an account they can change the email address with no problem and leaving the original user no chance of accessing it again. If we don't allow email changing the original can reset their password if their password is breached. What i suggest is allow users closing their own account and with that it sends an email message that has a link to reopen their account if they change their mind. Usually it would last like a week before expiring the reopen link. If they user wants a account in a new email it should be in a new account. What are your thoughts?

**Comment by Kooser6** [comment]
Another thing that could be possible is allowing multiple email address to an account. Then make the registering email the master email and if the attacker adds his email you can still reset your password with their master email.

**Comment by ocram** [comment]
Thanks for sharing this idea!

If you supply both the username (or email address) and the correct password, you are considered *authenticated* by this library and in most other places. That makes sense, doesn’t it? Supplying the correct password *is* your way of authenticating after all.

Now you would want to disallow this?

Who would get to change an account’s email address if not the client who successfully authenticated with a correct password?

Only a client who can prove control of the old email address as well? That would ignore that the reason for changing one’s email address may often be that the old one does not exist anymore. This is especially true if users visit your site only rarely.

Finally, requiring a new account in order to use a new email address ignores all experience from practical usage in the real world, in which this would be a huge annoyance to many users.

Security is not binary, or black and white. You always want tradeoffs between security and usability.

In your own application, you may decide what features to offer, of course. So if you don’t want to allow for password resets, just don’t implement that feature.

And if you want to let users decide for themselves, this is possible as well:
https://github.com/delight-im/PHP-Auth#enabling-or-disabling-password-resets
