### ISSUE TITLE
how do i do multi-company?

### ISSUE THREAD

**Issue by avierr** [delight-im/PHP-Auth#187]
I want something really simple, 
a company can have multiple roles and there can be multiple companies.
Users from one company cannot access assets of another company.
is it possible with PHP-Auth?

**Comment by tomnuss** [comment]
To accomplish what you describe you could add an additional table with an account ID (unique per company) that links to the user ID of PHP auth. 

Depending on your desired setup you could store the company’s data in a unique database that is defined along with the account ID.

**Comment by ocram** [comment]
@tomnuss Thanks a lot for your help!

@avierr It’s not that easy to answer because the details are unclear, but in general, this should be possible with this library.

First, do you want companies to act as users and thus receive individual accounts? So each company gets their own login credentials? In this case, you could simply store the owner’s user ID for all assets that you store. Then, on each access, check if the current user’s ID matches the owner’s ID.

If a company is not a user, i.e. if there must be multiple accounts for each company, you can use an extra table to assign user IDs to companies. This may be the first part of what @tomnuss suggested.

Finally, if you need total separation between individual companies’ assets, you may choose to run one instance per company, or at least one set of database tables per company. This is the second part of what @tomnuss said.
