### ISSUE TITLE
Remembering session not work on iOS client app

### ISSUE THREAD

**Issue by BanHammerYKT** [delight-im/PHP-Auth#188]
Hi, i used this lib for along time on my small web projects.
Without any problems.

But on mobile I found this problem:
I have two apps - ios and android.
Logins success in both apps and cookies stored locally on device.
But ios app logouts every time, ~ 30 min. [$auth->isLoggedIn() returns false]
If I set this option some greater value, ios app keep logged in for a value
session.gc_maxlifetime = 1440
Why an android app still keeps logged in? 'Logged in' state already ~1 month.
Remember duration sets to one year:
$rememberDuration = (int)(60 * 60 * 24 * 365.25);
Cookies in both delivered to server successfully. [var_dump($_COOKIE); isnt empty]

How fix this problem?

Regards, Bogdan.

**Comment by ocram** [comment]
Thanks for your feedback!

The normal login state and session are handled with one cookie, and the persistent logins over long times (“remember me”) are handled with another cookie.

So if one of these two things (the latter) doesn’t work in your iOS app, while the server-side code base is the same for your Android and iOS apps, it could be that iOS doesn’t accept the second cookie.

In order to debug this, on subsequent page loads after logging in, could you print the contents of `$_COOKIE` on both Android and iOS and compare whether they both have both cookies?

Perhaps iOS *does* accept the second cookie but limits its lifetime. Though I only know about such a feature in iOS for [cookies created through JavaScript](https://webkit.org/blog/8613/intelligent-tracking-prevention-2-1/), which is not the case here.

**Comment by BanHammerYKT** [comment]
Yes, you are right.
In ios cookies saved wrong, the cookies joined with comma separator.
And remember_xxx joined with SameSite
["SameSite"]=>string(94) "Lax, remember_xx ...

Thank for your answer!

**Comment by ocram** [comment]
Thanks!

That’s strange. Do you think there’s something wrong in this library here that caused this?

**Comment by BanHammerYKT** [comment]
Hi!

No, I don't think this library issue.
The ios app developer has mistake, when writing networking code.

Regards, Bogdan.
