### ISSUE TITLE
User Table Not Configurable

### ISSUE THREAD

**Issue by ed-iv** [delight-im/PHP-Auth#189]
Firstly, this project looks awesome and I'm excited to bring it into an existing project. However, it looks like the implementation is coupled to the provided database schemas. This presents an issue for existing projects like mine where the user table in question is not named 'users'.

Wondering if anyone has suggestions on making this work, I suppose I could create a 'users' view in my database (mariadb)?

**Comment by ocram** [comment]
Thanks for your appreciation and feedback!

The problem you describe is certainly something we have thought about a lot.

But supporting any *existing* project instead of just *new* projects that are developed from scratch is hard. Really hard. And it’s either us or the project developer who needs to do some additional work.

We could do it, but many implementations adjusting to a library is much easier than a single library adjusting to many implementations. We could support *your* schema, but it’s almost impossible to support *everybody’s* database layout, right?

If it were just the name of the database table, that would be simple. Just rename your table and replace the occurrences in your code. But it’s usually also the column names inside, and often also the possible values and their meaning.

All in all, we really don’t see any way to make this work for every existing project. Sorry!

**Comment by ed-iv** [comment]
Thanks for taking the time to respond. I understand your position, and while it would obviously be impossible to support every database layout out there and I certainly don't expect you guys to adjust your project to accommodate the particulars of my schema I do think that making certain key parameters configureable would go a long way towards facilitating integration of this library into existing projects.

All those sites out there that suffer from inadequate authentication systems already exist. Such legacy projects are often a dense tangle of spaghetti code without any test coverage making a search and replace of table or column names treacherous. By and large the only schema that is going to collide with those in existing projects is the users table so I think you would cover most cases just by making the key fields there configurable.

The above notwithstanding I know where you are coming from and understand if thats not a priority. Still looking forward to trying to make it work for my use case.

**Comment by ocram** [comment]
> I do think that making certain key parameters configureable would go a long way towards facilitating integration of this library into existing projects.

Sounds reasonable. What would you suggest specifically? The two fields for the email address and the password? What about the IDs?

> All those sites out there that suffer from inadequate authentication systems already exist.

Sure. Do you think making the integration with this library easier would make more of them switch and improve their legacy projects’ security? That would certainly be something worth doing the extra work for.

> Such legacy projects are often a dense tangle of spaghetti code without any test coverage making a search and replace of table or column names treacherous.

100 % agreed.

> Still looking forward to trying to make it work for my use case.

It seems that, in general, we agree here. Let’s talk about the specifics of what you need.

**Comment by ed-iv** [comment]
> Sure. Do you think making the integration with this library easier would make more of them switch and improve their legacy projects’ security? That would certainly be something worth doing the extra work for.

For sure. Of course the developers put in charge of maintaining these projects will first need to be informed enough and interested enough to seek out available options, but ease of integration is surely going to have an impact on the adoption rate. 

The list of available standalone options is with encouraging momentum behind them them is pretty small ... my research ultimately led me to just this project and [auraphp/Aura.Auth](https://github.com/auraphp/Aura.Auth), which offers [some flexibility for existing databases](https://github.com/auraphp/Aura.Auth#pdo-adapter) through their PDO adapter but the project as a whole is far less feature rich from what you have here.

I'd guess that most legacy projects will be able to adopt all but your 'users' schema, and will either run a script to sort of grandfather known users into 'users_confirmations' or simply leave it empty to force all users to confirm after integrating this library.

Regarding the 'users' table, I think everything I'm looking for could be achieved by expanding/adjusting the UserManager constructor to accept an associative array that allows the user to re-map the name of the users table as well as its constituent columns so that users can map the semantics of the project onto their existing database schemas. If it is a pain to make this work for all of the columns, I think the most likely to have conflicting semantics with existing projects are 'id', 'email', 'username', 'password', and probably 'status'. 

Something along those lines is what I was looking for anyhow when looking into the repo.

**Comment by ocram** [comment]
Thanks!

Let’s talk about how a migration would usually work (perhaps also in your case):

 1. `users_confirmations` table: You would probably create the structure for this table from scratch, adding this new table to your existing tables. As for the data inside, this is only for ongoing email verifications.

    * For users who have a verified email address and do *not* have an open request for their email address to be changed, there would be no data to migrate here.

    * For users with a verified email address who *have* recently requested their email address to be changed (without that process being completed yet), you’d have to create the records here and (re-)send the corresponding verification emails. You could do this by impersonating these users one after another (programmatically, e.g. using `Administration#logInAsUserById`) and then simply calling `Auth#changeEmail` with their desired new email address. Alternatively, you could just ignore those old change requests and force the changes to be requested again.

    * For users who have no verified email address yet, you could leave them out from your migration of the actual user records and instead create them as new records by using either `Auth#register` or `Auth#registerWithUniqueUsername` with their given details.

 1. `users_remembered` table: Again, you would probably create the structure for this table from scratch, adding this new table to your existing tables. As for the data inside, you could just leave this table empty if you were fine with every user being logged out after the migration. Otherwise, you’d need cookies set on their devices (which you cannot do remotely without any user interaction, obviously) and the corresponding records created here. It’s a little extra work.

 1. `users_resets` table: The structure would be added to your existing tables as a new table again. The content could be ignored (i.e. the table left empty) if you were fine with every user having to request a password reset again after the migration, should they need it. Otherwise, you could impersonate the affected users again using `Administration#logInAsUserById` and then call `Auth#forgotPassword` as the current user.

 1. `users_throttling` table: You really don’t need any existing content here. As for the structure, it would be added to your existing table as a new table again.

 1. `users` table: This is the most important table, of course. There are two possibilities:

    1. You create the structure from scratch and add it as a new table. In this case, in order to fill the table, you could re-create your existing users one after another using `Administration#createUser` or `Administration#createUserWithUniqueUsername` if they have a verified email address, or `Auth#register` or `Auth#registerWithUniqueUsername` if they didn’t verify their email address yet. One important question: How do you get the old passwords? Just passing in the passwords would only work if you previously stored the passwords as plaintext, which would be an excellent reason to switch to this library. Alternatively, if you used the same hashing procedure for all of the old passwords, you could pass in the hashes and when trying to log in users with this library later, apply your own hash procedure again before passing the password to this library.

    1. You adjust your existing table layout to match this library. This is what you were mainly interested in. Important questions: Do the charsets or encodings of your columns match [what this library needs](https://github.com/delight-im/PHP-Auth/tree/master/Database)? If not, could you convert them without breaking your remaining application code? Have you been using integer IDs? Did you use the `password_hash` function to hash passwords before, or did you use a different hashing procedure, or none at all? Can you map your existing values for `status` and `roles_mask`, if any, to new values? It’s unlikely your existing values had the same format.

As you can see, the names of the columns are only one of many problems.

**Comment by ed-iv** [comment]
1. `users_confirmations` - In my case I would just grandfather all existing users in my database in, effectively identifying them as verified though no actual verification has taken place. So no data would need to be migrated here.

2. `users_remembered` - Same deal here, I would just leave it empty. Issues with the project I'm working on are pretty severe and a forced re-authentication a non-issue.

3. `users_resets` - This one I would programmatically populate as you suggest using an impersonated call to Auth#forgotPassword. The best solution for my use case will be to force all users to provide a new password. Passwords (and usernames for that matter) are relatively short, not-so-random-random generated alphanumeric strings stored in plaintext (i.e. garbage).

4. `users_throttling` - Agreed, nothing to be migrated here.

5. `users` - The easiest thing for me to do is going to be (I think) to adjust my table the match the library. Pending a more in-depth column-for-column investigation, I'm fairly confident that any necessary adjustments can be made to the column definitions without significant breakages. 

    - IDs for user table are integers
    - yep, passwords are plaintext
    - User table does not currently have `status` or `roles_mask` columns so we are good there, however I suspect it is not uncommon for other existing projects to have an existing `status` column with different semantics in their user table.

I have a couple of additional legacy systems outside of the main web application that rely on the current database schema for authentication (username and password). Security is not a concern for these and -- at least in the short-term -- I need to keep them as-is while I put out fires elsewhere.

I am thinking I can make this work pretty painlessly by creating a `users` view in my database to re-map column names as necessary to be consumed by this project and leave my existing users table as-is for the legacy systems that need it unaltered and then proceed with the rest of the migration as outlined above.

I really appreciate you taking the time to dialogue, shows you are really putting yourself behind this repo and has already been an immense help to me in clarifying my approach on this.

**Comment by ocram** [comment]
Sounds good. (1) makes sense. As for (2), I agree that there are usually more severe problems than the need to re-authenticate users. With (3), remember that you would also have to implement the logic for sending the emails in your application code. Otherwise, the tokens have been generated but not sent to anyone yet. You can’t retrieve them later. You would have to generate new ones again.

Another thing you could probably do is keep both database layouts live side by side. In the beginning, you copy (and adjust) all records from the old database tables to the new ones (for this library). After that, when the library updates its own tables, e.g. when a call to `Auth#register` succeeds in your application code, you update the old tables to include the changes.

However, if you can make all this work with views, that might be the easiest solution.
