### ISSUE TITLE
User is not verified due to error.

### ISSUE THREAD

**Issue by glebavladimir** [delight-im/PHP-Auth#19]
> **/src/Auth.php** on line **682**
`if ($userData['verified'] === 1) {`
On one of my servers, this condition always returns false. On localhost it's ok, but on the live server, it throwed me an error. I suppose it's because MySQL alway returns strings as an output and `1 !== '1'` while `1 == '1'`. For some reason two my servers are dealing with this issue differently.
So I just switched from === to == and it worked. 
I thought maybe it will be helpful to change.

**Comment by rgvy** [comment]
Hello

This is the same issue as in #7 and #18.

For me, it was caused by lacking the new MySQL driver `mysqlnd` in my LAMP configuration. The older driver converts everything to a string while `mysqlnd` retains types.

My LAMP host (Bluehost) does not include `mysqlnd` despite offering PHP 5.4 through PHP 7.0. Many other hosts use the newer driver by default.

Hope this is helpful.

**Comment by ocram** [comment]
@rgvy Thanks for your help! As you can see, you're really not the only one with this issue :)

@glebavladimir The `mysqlnd` driver for MySQL with PDO is really what you need here, as perfectly explained by @rgvy. It has been the default driver in PHP for a while now. The real question is why that driver is not enabled on your server. Could you check your PHP versions (both local and on the server) perhaps? Thanks!

**Comment by glebavladimir** [comment]
@ocram sorry for late answer. PHP version on the server remote server is higher than on my localhost. despite this, I have an error only on the localhost. so I don't think this is the issue. 

so this is my remote server where error does appear:
`php -v
PHP 5.6.30 (cli) (built: Jan 25 2017 17:00:08) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.8, Copyright (c) 2002-2016, by ionCube Ltd.
`
I don't know, maybe the driver causes the problem, but I live for a long time with the knowledge – MySQL converts everything to string and never thought that it can be changed. so when I saw `===` comparing operator to integer on the SQL query result, I knew what's the problem from this very moment.  Basically, I was more surprised, that worked on localhost)

So.. is there a problem in fixing it? cause I use siteground shared hosting for some of my projects and lot of people does too. there you cannot change stuff like you want. And I think it's better for the library to run on different hosting setups.

**Comment by rgvy** [comment]
The `mysqlnd` driver and the old driver are independent of the php version. I've used localhost (MAMP) php v5.6 with `mysqlnd` and Bluehost php v7.0 with the old driver. Check your `phpinfo();` to see which mysql driver each configuration is using.

**Comment by ocram** [comment]
@glebavladimir As @rgvy said correctly, this problem can occur with any PHP version, though the correct `mysqlnd` driver has actually been the default since PHP 5.4.0.

What you should do is view the `phpinfo()` again and in section "pdo_mysql", look up the "Client API version", which *must* contain the "mysqlnd" keyword. If it does, you're using the correct `mysqlnd` driver (probably on your local machine). If it does not, you're using the wrong `libmysqlclient` driver (probably on your server).

The knowledge that MySQL converts everything to strings is indeed wrong, or rather outdated, as the newer driver doesn't have that limitation anymore, fortunately. We should all be able to enjoy the advantages of the newer driver!

I absolutely understand your concerns, and I see that this library not running on some shared hosts is annoying. But we have to make a choice. And supporting an older driver is not what we decided to do because:

 * The newer driver has been the default for a long time.
 * There are quite a few shared hosts available where you can use the newer driver (see related issues).
 * When running your own server, you can pick the newer driver, anyway.

As you can see, state-of-the-art technology is easily available in many ways, so this library won't support the older driver. Sorry!

Because of this, the latest version of this library has started throwing `WrongMysqlDatabaseDriverError` now if you use the wrong driver. This has been implemented in https://github.com/delight-im/PHP-Auth/commit/04a2e8ef4e909a580542699e0e792c2913230677. Apart from that, the requirement for the correct driver has been added to the README, finally, as of https://github.com/delight-im/PHP-Auth/commit/79db94f50032b0f7b2ad2b749febe7dc35566e2a.

Nevertheless, what you can certainly do is patch the library manually in order to make it work with the older driver, which some of you have already done. With the latest additions, you just have to remove the part where the `WrongMysqlDatabaseDriverError` is thrown as well.

But, of course, I absolutely recommend getting a hosting provider or a server where you can switch to the newer driver, which makes this library work without any manual effort, increases your productivity when writing your own database code, and lets you update this library via Composer without re-applying your patches.
