### ISSUE TITLE
Migrate users from WordPress

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#190]
Hi I am migrating some users from a WordPress site, I wondered if I could copy all the emails and password hashes over, would it be compatible e.g. is the password hash generated by WordPress same as the one used on PHP-Auth? If not what would you recommend as a way to migrate users without asking them to reset password? Or would it be best to reset password?

Cheers.

**Comment by ocram** [comment]
You might want to read [this recent issue](https://github.com/delight-im/PHP-Auth/issues/189) as well.

As for password (hash) migration, I would keep the new database (table) and the old one (from Wordpress) active side by side. Then, when a WordPress user tries to authenticate, check if they are in the new database. If they are, proceed as normal. If they aren’t, instead try to authenticate them using the WordPress functions. If that succeeds, they are authenticated, and you have the cleartext password available for that request. So at this point, create a new user record in the new database (table) by registering the user with that password. Don’t save that password in cleartext anywhere, of course.

Otherwise, you could inspect your WordPress code and database fields to check what hash type and parameters they are using. You could effectively chain the old hashing and the new one, as described in the other recent issue.

Finally, forced resets could be used, as you suggested.

**Comment by Aristotle22** [comment]
I did a WordPress migration.

Here some ideas:
- WordPress uses by default a non standard PHP hashing system. It's located in /wp-includes/class-phpass.php.
- If you plan to migrate to the delight-im PHP auth library you could install a WordPress plugin that changes the hash algo of WordPress to a native PHP hash as soon as possible. I installed the plugin "PHP Native password hash" about two years before migration.
- I migrated all WordPress users from the _wp_users_ table to the _users_ table. When the password hash had a length of 34 chars (WordPress standard hash length) I put a random hash in the _users_ table.
- I created a separate _my_users_ table for additional user information. In this table in stored the WordPress login, email and hash for the users that had only a WordPress standard hash.
- When an user tries to log in I load the email, login and the old WordPress hash from the _my_users_ table. If there is a record I use the WordPress hash library (class-phpass.php method: CheckPassword) and check if the password is valid.
- If the password is valid I hash the password with the native PHP function password_hash().
- I put the new hash in the _users_ table and delete the email, login and old WordPress hash in the _my_users_ table.
- You might remove the migration code after a couple of months and either delete old users that don't login anymore or these users have to reset their password.

**Comment by ocram** [comment]
@Aristotle22 That’s really helpful, thanks! Good to have some feedback from someone who actually did the migration.
