### ISSUE TITLE
Question: Anyway to make the remember tokens device specific?

### ISSUE THREAD

**Issue by podoco** [delight-im/PHP-Auth#192]
I have my "remember me" cookies set to HttpOnly and Secure but I am still able to transfer them over to a separate machine, insert the cookies into a browser, refresh, and be logged into the site. Is there a way to make them more device specific so that this cookie theft wouldn't be possible? Obviously this type of attack would require physical access to the victim's computer, but I am still curious 😊

**Comment by ocram** [comment]
> I have my "remember me" cookies set to HttpOnly and Secure but I am still able to transfer them over to a separate machine

Of course, because that’s not what `Secure` and `HttpOnly` are about. They prevent other things and types of attacks.

We would indeed need a separate mechanism to prevent what you describe.

> Obviously this type of attack would require physical access to the victim's computer

Exactly, and that’s the reason why no protection against this type of attack has been implemented so far.

Cookies being secret and potentially containing sensitive data is a valid assumption that you can base your implementation on, isn’t it?

You could certainly tie the cookie’s value to the user-agent string, to the IP address, or to other identifiers, e.g. via a short checksum. But that would also have downsides (e.g. frequently changing IPs).
