### ISSUE TITLE
email confirmation via code instead of link

### ISSUE THREAD

**Issue by eniac314** [delight-im/PHP-Auth#194]
I am planning to use this library in a single page application. If possible I would like my users to use a confirmation code/key rather than clicking on a link in order to confirm their email. That way they would not have to reload the app after sign up. Is there a way to do that?

I was thinking about encrypting the selector and token using a random key, then:
- send the key to the user via email
- send the encrypted selector and token to the app
- have the user input the key in the app
- have the app send both key and encrypted selector and token to the server
- decrypt selector and token server side and then use $auth->confirmEmail 

I don't know if it is doable, or secure.

**Comment by ocram** [comment]
This is definitely possible.

The important thing to pay attention to is that you will most likely want your confirmation codes to be short, e.g. 6-digit numeric codes.

This limits the key space so much that encryption with such codes as keys is basically useless.

What you could do instead is, in your database, create a simple plaintext mapping of your custom confirmation codes (e.g. 6-digit numeric) to the ones generated and used by this library:

```
TABLE confirmation_codes_to_selectors_and_tokens
COLUMN confirmation_code (e.g. 482947)
COLUMN selector (e.g. iHFvWfAL16n79ryAMBbpxSN9)
COLUMN token (e.g. YOWyHY8jGvmKxgXVI9hmv9Rp)
```

The short codes, however, have considerably less entropy than the selectors and tokens used by this library. That means they are much more likely to be guessed by attackers.

To prevent easy guessing, you should certainly limit the duration for which your custom codes are valid, and you may include a user ID or email address in the list of mappings so that attackers cannot guess codes for all users at once.

Does that help?

**Comment by eniac314** [comment]
It does help, thank you very much.
