### ISSUE TITLE
What happens when Remember Me is `uncheck`? 

### ISSUE THREAD

**Issue by jitendraharpalani22** [delight-im/PHP-Auth#2]
This is more of a question than an issue. I wanted to understand the behaviour when I login using your library and Remember me is `uncheck`. 

Will my session expire while browsing through the website? Imagine a use-case where I logged in and browser to `about-us` page from `homepage`. After landing on `about-us` page I should still be logged in. 

Another example is of refresh. What happens when I refresh my page? 

Only cases where I should be logged out is when I close my tab or browser or manually type another url in address bar. Post these user actions if I come back on the site and Remember me was `uncheck` I should be asked to login again. 

Thanks in advance!

**Comment by mwaclawek** [comment]
Thanks for your question!

Does https://github.com/delight-im/PHP-Auth/commit/f45e0f1cb47d730e38d2d7b415838b583536f14e describe the difference more clearly?

A login with this option unchecked will be sufficient and do what you want. Checking this option just *extends* the lifetime of the login.

Hope that helps!

**Comment by jitendraharpalani22** [comment]
So you store the user information in session after login (remember me `check`/`uncheck`). 

If remember me is `check`, then the user is logged in forever unless they opt to logout. 

If remember me is `uncheck` how do you clear session on browser close?

**Comment by mwaclawek** [comment]
Exactly. The user information is stored in the session in both cases. You can just use the login without that option. When switching between pages, you will stay logged in, of course.

If you check the option, you are indeed logged in until you log out manually. "Forever" has been limited to 28 days in this library for now. But it could be any (longer) duration.

When the user closes their browser, *they* destroy the session actively, because the browser usually deletes the session cookie. If not, the server will clear the session automatically some time later.

**Comment by jitendraharpalani22** [comment]
Thanks for your response!

**Comment by mwaclawek** [comment]
Glad I could help!
