### ISSUE TITLE
Issue with my server's MySQL setup

### ISSUE THREAD

**Issue by podoco** [delight-im/PHP-Auth#200]
This isn't an issue with the PHP-Auth library, only asking incase you've ever seen this error before. 
I have two hosting accounts, and one of them just reinstalled PHP and MySQL (along with phpMyAdmin) and now on that server I am getting this error:

```php
Fatal error:  Uncaught Delight\Auth\DatabaseError: SQLSTATE[42000]: Syntax error or access violation: 1064 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"users_throttling" SET "tokens" = ?, "replenished_at" = ?, "expires_at" = ? WHER' at line 1 
in /website_path/vendor/delight-im/auth/src/Auth.php:1738

Stack trace:
#0 /website_path/vendor/delight-im/auth/src/Auth.php(1033): Delight\Auth\Auth-&gt;throttle(Array, 1, 3600, 75)
#1 /website_path/vendor/delight-im/auth/src/Auth.php(299): Delight\Auth\Auth-&gt;authenticateUserInternal('password123...', 'email@p...', NULL, 31557600, NULL)
#2 /website_path/private/api/login.php(20): Delight\Auth\Auth-&gt;login('email@p...', 'password123...', 31557600)
#3 /website_path/public/moonbase.php(8): require('/home/projecttr...') in /website_path/vendor/delight-im/auth/src/Auth.php on line 1738
```

I think this may be due to some incorrect configuration of PDO on my server side. My hosting company has not been helpful about this. If you have seen this error, please let me know if you have any suggestions! Otherwise feel free to close or delete this issue. 

Note: I have the exact same code installed on both servers. One server works, the other is experiencing the above error.

**Comment by ocram** [comment]
Thanks a lot!

Indeed, this seems to be an actual issue in the code. Not in this library right here, but in [our database library](https://github.com/delight-im/PHP-DB).

In `Auth.php:1732`, the block that caused the problem is the following:

```php
try {
    $affected = $this->db->update(
        $this->makeTableNameComponents('users_throttling'),
        $bucket,
        [ 'bucket' => $key ]
    );
}
catch (Error $e) {
    throw new DatabaseError($e->getMessage());
}
```

Which looks fine, but in turn uses [`PdoDatabase.php:415`](https://github.com/delight-im/PHP-DB) internally:

```php
public function quoteIdentifier($identifier) {
    $this->ensureConnected();

    if ($this->driverName === PdoDataSource::DRIVER_NAME_MYSQL) {
        $char = '`';
    }
    else {
        $char = '"';
    }

    return $char . str_replace($char, $char . $char, $identifier) . $char;
}
```

Since your error message talks about MariaDB, it’s probably the lack of explicit MariaDB handling here, which would need to copy the MySQL behavior.

Any chance your hosting company might have switched from MySQL to MariaDB during their recent changes?

Please run the following and report what the exact output is:

```php
// $pdo = new PDO('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');

$db = \Delight\Db\PdoDatabase::fromPdo($pdo);
\var_dump($db->getDriverName());
```

Thank you!

**Comment by podoco** [comment]
that code exported

    string(5) "MySQL"

**Comment by ocram** [comment]
> that code exported
>
> `string(5) "MySQL"`

On both servers? I’m pretty sure it must show that output on *one* server and *different* output on the *second* server. Can you check again?

That quick workaround is indeed fine for your case right now. It shouldn’t break anything, but it’s not a complete fix, either.

As soon as you have confirmed the two outputs from `$db->getDriverName()`, we’ll have a complete fix here very soon.

**Comment by podoco** [comment]
not sure if case sensitivity matters but:

The working server:
`string(5) "MySQL"`

the non-working server:
`string(5) "mysql"`

if that isn't the issue, is there a way for me to extend the `quoteIdentifier` function so when i run composer update I dont overwrite the fix?

**Comment by ocram** [comment]
Well, that’s strange. Any chance one of those servers could be running something else than the unmodified last version of this library here? Let’s try something different:

```php
// $pdo = new \PDO('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');

\var_dump($pdo->getAttribute(\PDO::ATTR_DRIVER_NAME));
\var_dump($pdo->getAttribute(\PDO::ATTR_CLIENT_VERSION));
\var_dump($pdo->getAttribute(\PDO::ATTR_SERVER_VERSION));
\var_dump($pdo->getAttribute(\PDO::ATTR_SERVER_INFO));
```

Could you please try this on both servers?

(Updating using Composer should not change anything, since Composer thinks you already have the latest version. If we release a new version here, it should include the fix that we need here.)

Sorry for the trouble!

**Comment by podoco** [comment]
No need to apologize! You are going above and beyond with your help. I appreciate this so much!

I ran the above code.

```php
Non-Working Server
string(5) "mysql" 
string(79) "mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $" 
string(21) "5.5.5-10.3.22-MariaDB" 
string(142) "Uptime: 1086984 Threads: 9 Questions: 3420606 Slow queries: 0 Opens: 977 Flush tables: 1 Open tables: 488 Queries per second avg: 3.146"



Working:
string(5) "mysql" 
string(79) "mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $" 
string(21) "5.5.5-10.1.44-MariaDB" 
string(147) "Uptime: 196297 Threads: 5 Questions: 8588497 Slow queries: 30 Opens: 210356 Flush tables: 1 Open tables: 4096 Queries per second avg: 43.752"
```

**Comment by ocram** [comment]
Thanks for your understanding, and for the additional debug output!

So the server versions tell us that both servers seem to be running MariaDB, but version 10.1.44 is working while 10.3.22 is not. Just looking at these versions, I don’t think that makes sense. So it’s probably something else.

The two database instances probably have different `SQL_MODE` settings. You should be able to query these like this:

```
SELECT @@SQL_MODE, @@GLOBAL.SQL_MODE;
```

The different values are explained [here](https://mariadb.com/kb/en/sql-mode/#sql_mode-values), and `ANSI_QUOTES` is what we’re looking for, specifically.

But since PDO reports the driver name as `mysql` (same case) for both instances, I would really expect our `$db->getDriverName()` from the `PdoDatabase` class to return the same value (same case) for both instances, too.

**Comment by podoco** [comment]
Ran:
```sql
SELECT @@SQL_MODE, @@GLOBAL.SQL_MODE;
```

Working Server:
```sql
@@SQL_MODE                                 | @@GLOBAL.SQL_MODE
NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION | NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

Non-Working Server:
```sql
@@SQL_MODE             | @@GLOBAL.SQL_MODE
NO_ENGINE_SUBSTITUTION | NO_ENGINE_SUBSTITUTION
```

Would `NO_AUTO_CREATE_USER` need to be specifically stated 
even though it is a default value in MariaDB 10.1.7+ ?

**Comment by ocram** [comment]
So the working server uses the default values for its version, but the non-working server lacks the two new default values for its version, `STRICT_TRANS_TABLES` and `ERROR_FOR_DIVISION_BY_ZERO`, and even drops the old default value `NO_AUTO_CREATE_USER`.

But all that shouldn’t matter. These all don’t affect the quoting behavior.

So, apparently, it’s only what our database library writes into the statements, i.e. `` ` `` or ` " ` for quoting.

But the big question is, if both servers return their database driver as `string(5) "mysql"`, why doesn’t the database library return the same value from `$db->getDriverName()` for both calls?

Are you sure you’re running the same unchanged library code on both servers, and neither of those servers has been updated (again) in the meantime?

**Comment by podoco** [comment]
Very sorry for the late response. I no longer have access to the second server since my company discontinued it. I'm fairly certain that the server we have now has some configuration not setup correctly. Giving every SQL column a default value and only using the backtick symbol seems to keep the code happy. 

Let me know if you need me to do anything else! Otherwise feel free to close the bug 🥇 . You've been an amazing resource.

**Comment by ocram** [comment]
No problem!

It’s still the case that the unmodified versions of both this library here and our [database component](https://github.com/delight-im/PHP-DB) should work fine for you without any problems.

If that’s not the case, and you still need the workaround in [`PdoDatabase#quoteIdentifier`](https://github.com/delight-im/PHP-DB), that is something we could debug.

The following would be what we need for that purpose:

```php
// $pdo = new \PDO('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');

\var_dump($pdo->getAttribute(\PDO::ATTR_DRIVER_NAME));
\var_dump($pdo->getAttribute(\PDO::ATTR_CLIENT_VERSION));
\var_dump($pdo->getAttribute(\PDO::ATTR_SERVER_VERSION));
\var_dump($pdo->getAttribute(\PDO::ATTR_SERVER_INFO));
```

Don’t know if you want to investigate here or not. Please feel free to reopen if you want.
