### ISSUE TITLE
PostgreSQL PHP Fatal error:  Uncaught PDOException: SQLSTATE[55000]

### ISSUE THREAD

**Issue by Y0ngg4n** [delight-im/PHP-Auth#202]
Getting following Error:
```2020/03/18 19:22:23 [error] 161840#0: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval(): lastval is not yet defined in this session in /usr/share/nginx/html/deployer/vendor/delight-im/db/src/PdoDatabase.php:288```

after executing this code:
```
try {
    $userId = $auth->register($_POST['email'], $_POST['password'], $_POST['userName'], function ($selector, $token) {
        echo 'Send ' . $selector . ' and ' . $token . ' to the user (e.g. via email)';
    });
} catch (\Delight\Auth\InvalidEmailException $e) {
    echo "Invalid email address";
} catch (\Delight\Auth\InvalidPasswordException $e) {
    echo "Invalid password";
} catch (\Delight\Auth\UserAlreadyExistsException $e) {
    echo "User already exists";
} catch (\Delight\Auth\TooManyRequestsException $e) {
    echo "Too many requests";
}
````
But error already gets throwen when acessing the $token variable of the register() callback.

I located the Error at this File:
https://github.com/delight-im/PHP-DB/blob/master/src/PdoDatabase.php : 288
To fix this you should return the ID of the user on your Insert because you should not use `lastval()`:
https://stackoverflow.com/questions/17819001/postgres-not-returning-lastval-properly

If this error is not clear to you dont hestitate to contact me ;)

**Comment by ocram** [comment]
Thank you!

That’s due to our usage of `Database#getLastInsertId`, which in turn uses `PDO#lastInsertId`. We use that in one place, namely `UserManager#createUserInternal`, which is a function used by four public methods:

```
Auth#register
Auth#registerWithUniqueUsername
Administration#createUser
Administration#createUserWithUniqueUsername
```

Could you please remove your own workarounds, and then in `UserManager.php`, find the line that says

```php
$newUserId = (int) $this->db->getLastInsertId();
```

and add the sequence name inside of the parentheses?

So that argument should probably be `'users_id_seq'`.

Does that work?

**Comment by Y0ngg4n** [comment]
@ocram Thank you for your fast answer. Tried it with following code 

https://github.com/Y0ngg4n/PHP-Auth/blob/bug/202-Postgresql-error-fix/src/UserManager.php

But now throwing following Error:
```
2020/03/20 08:50:27 [error] 7634#0: *230 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  currval(): relation "users_id_seq" does n$
Stack trace:
#0 /usr/share/nginx/html/deployer/vendor/delight-im/db/src/PdoDatabase.php(288): PDO->lastInsertId()
#1 /usr/share/nginx/html/deployer/vendor/delight-im/auth/src/UserManager.php(182): Delight\Db\PdoDatabase->getLastInsertId()
#2 /usr/share/nginx/html/deployer/vendor/delight-im/auth/src/Auth.php(234): Delight\Auth\UserManager->createUserInternal()
#3 /usr/share/nginx/html/deployer/public/pages/auth/login.php(26): Delight\Auth\Auth->register()
#4 {main}

```

**Comment by ocram** [comment]
Thanks for testing this!

What’s the name of your `users` table? Is it something else? Did you add a prefix?

Or did you rename the automatically generated sequence?

**Comment by Y0ngg4n** [comment]
@ocram no i have used your PostgreSQL Script to create the Tables.
https://github.com/delight-im/PHP-Auth/blob/master/Database/PostgreSQL.sql

**Comment by ocram** [comment]
Your error message says:

> currval(): relation "users_id_seq" does n[ot exist]

But if the table is still named `users` and the ID field is still `id`, that sequence name should be correct.

Could you try prefixing the sequence name with your *schema* name (and a dot)? So that would be

```php
$newUserId = (int) $this->db->getLastInsertId('my_schema.users_id_seq');
```

if your schema was named `my_schema` in PostgreSQL. I think that could help.

Otherwise, please explicitly look up the sequence name for the column `users.id` in your database.

Thanks!

**Comment by Y0ngg4n** [comment]
Fixed it. My database version doesn´t supported lastval().

**Comment by ocram** [comment]
Didn’t know this was possible.

Thanks a lot for sharing the solution!
