### ISSUE TITLE
How long is the cooldown to send another email verification?

### ISSUE THREAD

**Issue by Seb1929** [delight-im/PHP-Auth#207]
Hei.
I'm getting a "TooManyRequestsException" error when i try to send another verification link to the email. How long is the cooldown for each request?

**Comment by Seb1929** [comment]
Still not possible to send another requesten.

**Comment by Seb1929** [comment]
Also can't login. Getting the same error. Possible to change this?

**Comment by ocram** [comment]
Did all this occur just randomly? Or did you really attempt to request multiple confirmation messages and then performed several (failed) login requests as well?

Further, do you use `Auth#resendConfirmationForEmail` or `Auth#resendConfirmationForUserId`?

In general, requesting a new confirmation message should – currently, at least – be allowed roughly once every 6 hours.

The `Auth` constructor also has an option to disable automatic throttling, as documented. Perhaps you might want to enable this temporarily, or, if you can safely identify administrator clients internally, disable it for those.

**Comment by Seb1929** [comment]
Just tried to send two emails after each other then i got the TooManyRequestsException error. Now i can't login in on an account that has email verified because i still get the TooManyRequestsException. Also using Auth#resendConfirmationForEmail.

**Comment by ocram** [comment]
> Just tried to send two emails after each other then i got the TooManyRequestsException error

Yes, that should indeed not be possible, since it should be about 6 hours between requests. As confirmation messages are usually delivered via email, you should allow for some time for the email to actually be delivered to your inbox. The service might also queue these emails and only send it after some time. And the receiving email provider may take some time to process the email as well. So it really doesn’t make any sense to request another confirmation email just a few seconds or minutes later.

> Now i can't login in on an account that has email verified because i still get the TooManyRequestsException.

That should really be two different throttling mechanisms, though. So just by requesting confirmation emails, you should not be blocked from logging in. Did you also perform many login requests perhaps?

**Comment by Seb1929** [comment]
Alright.
No, no failed login attempts. 

I manged to login again now. So i logged out and tried to send an email confirmation again. Got the TooManyRequestsException error. Then i tried to login again on the same account that i successfully login in a few minuts ago and i got the samme TooManyRequestsException error. So i feels like its the same throttling.

**Comment by ocram** [comment]
Or did you attempt to request the confirmation emails *many times*, i.e. in fact *dozens* of times, despite seeing the same error message every time?

That might indeed block logins temporarily, but it should never happen in real-world (non-testing) usage.

So confirmation requests and logins can indeed have the same throttling mechanism, but only when used *a lot*, not with just a few attempts. That is because both types of requests can be used to enumerate existing users, accounts and email addresses.

So you might either want to wait a little bit, or disable throttling *temporarily* using the `Auth` constructor parameter.

**Comment by Seb1929** [comment]
I only did the send email two times and then login with right password right after. Was possible to login after a few minutes so that is okay. But i did not spam the send email button and 
at least not right after each other. I did wait sometime between so check if it was possible to send again because i knew it was a limit. 

I would like to change the trolling down to maybe 1 hour for email verification, but if you think 6 hours is fine for production then i will just leave it.

Turn of trolling for now so that i can continue to test. Thank you for the help :)

**Comment by ocram** [comment]
What you have described should not trigger the login to be blocked. If you’re in development or testing, as opposed to production, you might want to clear (truncate) the table `users_throttling` and then test your scenarios again and look for throttling.

We really think there’s no need to allow for more frequent attempts to request a new confirmation again in production. The current 6 hour limit should be sufficient in almost all cases and, given the context and environment of the email delivery between two servers, there should be no practical benefits to reducing the limit from 6 hours to 1 hour.

If you really want to do that, feel free to edit the code directly in your `vendor` directory – but keep in mind that this makes future updates a little bit more difficult.
