### ISSUE TITLE
composer strange import

### ISSUE THREAD

**Issue by CaneloDigital** [delight-im/PHP-Auth#21]
It's actually my first try with PHPAuth & Composer, so maybe I did something wrong.

I followed the install guideline as suggested and uploaded to my server.
To my astonishment when testing I was getting a 
Fatal error:  Call to undefined method Delight\Auth\Auth::getStatus() in /home/........./delightPHPAuth/tests/index.php on line 349

Now after some long debugging, I've found out that composer included a delight-im package, which seems not matching the one in the master tree.
the file structure is different, and the AuthClass obviously too, that's where the error came from.
So now instead of taking the AuthClass from root/src it takes it from root/vendor/delight-im/auth/src

Now the main questions is: Did I something wrong? is there even something I could do wrong?
And even better: How to do it right and correctly fix it?

**Comment by ocram** [comment]
Since you have this library somewhere in your master tree, as you said (at `/src/`), I guess you added that directory manually, right? So that's what you don't need to do anymore if you're using Composer. You can safely delete that directory if it's just a copy of this library that you added manually.

If Composer added this library under `/vendor/delight-im/auth/src/`, that's exactly what Composer is supposed to do, so that's perfect.

The only problem is probably that the version added by Composer is outdated. If you're in the root directory of your project, one level above `vendor/`, you can execute the following on the command line in order to show all Composer packages with their respective version numbers:

```
composer show
```

It will probably show `delight-im/auth` (this library) with an outdated version. What you need is `v5.0.0`.

Upgrading, then, is really easy with Composer. Open your `composer.json` in the root directory and ensure that the version for this library is `^5.0`. In the same directory (root), run

```
composer update delight-im/auth
```

to let Composer update the package and fetch the latest files. Afterwards, it should work, as far as I can see. Please note that the switch from version 4.x.x to version 5.x.x is a breaking change that requires some manual adjustments. See the upgrade guide linked in the README for further information.

Hope that helps!

**Comment by CaneloDigital** [comment]
That is what I call an answer ;-) Well explained, thanks!

**Comment by ocram** [comment]
Glad I could help!
