### ISSUE TITLE
Question about CSRF protection

### ISSUE THREAD

**Issue by podoco** [delight-im/PHP-Auth#212]
When an admin submits a form to change their name, I run the UPDATE query from the delight-im/db, and check for $auth->getUserID() to make sure they are updating their own name instead of someone elses. Do I need to include any kind of CSRF protection here? Is a CSRF attack even feasible if i am consistently using $auth->getUserID() ?

**Comment by ocram** [comment]
If you’re also using `?` placeholders instead of string interpolation or concatenation in your database statements, that sounds good.

CSRF is more about me sending you a link to `good.example.com/delete-account?sure=yes` and this causing you to delete your own account accidentally.

So always using `$auth->getUserID()` to check the owner is a basic fundamental for the security of your site, and absolutely essential to having a secure service. But it doesn’t prevent CSRF in any way.

And if you say you’ll surely recognize the link to `good.example.com/delete-account?sure=yes` in my email to you, I can try again by sending a link to `bad.example.org/free-offer` which *redirects* to `good.example.com/delete-account?sure=yes`.

And if you say “no, dangerous operations like deleting an account should always be done via POST instead of GET, anyway”, I’ll just use a self-submitting HTML form on `bad.example.org/free-offer` instead of an HTTP redirect.

Does that make sense?

As for the protection, though:

Yes, there is some built-in protection. Your cookies should have the `SameSite` flag enabled, which you can check in your browser’s developer tools, either in the “Network” tab on the first request or in the “Storage” tab to inspect the cookies later.

Does that help?
