### ISSUE TITLE
forgotPassword is not affected by $throttling=false

### ISSUE THREAD

**Issue by binoculars88** [delight-im/PHP-Auth#213]
While developing, I always turn throttling off just so that I don't hit the "too many requests" error all the time:
`$auth = new \Delight\Auth\Auth($db, '', '', false); `

This seems to work fine for stuff like
`$auth->login($_POST['email'], $_POST['password'], 0);`

... but when using
```
$auth->forgotPassword($_POST['email'], function ($selector, $token) {
        echo 'Send ' . $selector . ' and ' . $token . ' to the user (e.g. via email)';
});
```
... I still get the error "too many requests". Anything I can do to bypass this?

**Comment by ocram** [comment]
Thanks a lot!

This has been the only place where the `$throttling` option was not considered. Fixed in https://github.com/delight-im/PHP-Auth/commit/157a7095b0a4e12246923449e6083212438fc071.

Please try running

```bash
$ composer update delight-im/auth
```

to update the library to `v8.2.1` and see if that changes the behavior.

By the way, passing `null` is generally cleaner than passing `''`, although in this case it does indeed not make any difference.

**Comment by binoculars88** [comment]
Seems to work! Thanks a lot for the quick fix and the tip regarding `null`!
