### ISSUE TITLE
Force Logout

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Auth#214]
Sorry for the question if there are info in doc but I didn't find. I saw in db table that the field force logout have different value for example 0, 1, 2, 5 I suppose that need for logout an user but how work.

Thanks.

**Comment by ocram** [comment]
Usually, you don’t have to manipulate those values manually, because `Auth#logOutEverywhereElse` and `Auth#logOutEverywhere` do that for you.

But in the rare cases where you do, it’s as simple as incrementing those values by one.

The two methods `Auth#logOutEverywhereElse` and `Auth#logOutEverywhere` do a little more than that, of course – for example managing persistent (“remember me”) cookies and tokens and keeping you logged in on the local device if you want that.

**Comment by daebak74** [comment]
Always perfect and fast your answer. Thanks!
