### ISSUE TITLE
Database engine

### ISSUE THREAD

**Issue by Paulo--M--** [delight-im/PHP-Auth#229]
I am taking the liberty of including a small suggestion that I believe would improve this great package :-)

Your MySQL table creation scripts use 'MyISAM' as the DB engine. For my own purposes, I have changed this to 'InnoDB' so that transactions play nice... :-) Unless there is a specific reason why you are using MyISAM, I would suggest changing that to InnoDB in the scripts that you distribute -- just a thought...

And, again: great work -- thank you.

**Comment by ocram** [comment]
Thanks!

This is already tracked in https://github.com/delight-im/PHP-Auth/issues/137 and https://github.com/delight-im/PHP-Auth/issues/86.

If you’re using InnoDB instead of MyISAM in practice, we’re really happy to hear *any* feedback about your experience and possible adjustments you had to make.

As for changing the default engine, we may consider that in the future. And feedback from testing it priorly helps a lot with that, of course.

**Comment by Paulo--M--** [comment]
I changed all PHPAuth tables to InnoDB; in fact, I hardly ever use MyISAM anymore -- it all started because of transactions, years back, and the usefulness of commit/rollback. From a practical point of view, in some cases I need to act on PHPAuth tables AND some of my own tables -- having the rollback option is such a plus that everything is InnoDB. As far as I'm aware, this has always worked perfectly (having InnoDB PHPAuth tables, that is) but if there are any pitfalls I should be aware of, please feel free to point them out :-) Just to make things clear, I did not touch/adjust anything else: just changed the table engine to InnoDB -- is there something that is completely escaping my attention? :-) PHPAuth seems to be working perfectly... 
Thanks again for this great piece of code.

**Comment by ocram** [comment]
Thanks! So https://github.com/delight-im/PHP-Auth/issues/137 suggests you would really have to adjust the length of two email columns. Other than that, I don’t see any problems at the moment.
