### ISSUE TITLE
automatic login after email verification

### ISSUE THREAD

**Issue by Tchayka** [delight-im/PHP-Auth#23]
Hello,

From a user experience point of view it may be a bit bothersome to have to login right after the "registration and verification of email address" process. 

I thought about storing the email/password in sessions variables to automatically log the user in right after checking the token/selector for the email verification but this seems to create security issues (ie: storing a plain text password somewhere). Is there a better way to do this?

Is there a security reason for it not being already implemented?

Thanks.

**Comment by ocram** [comment]
Good point, thanks!

Right now, there is indeed no better solution than storing the cleartext password somewhere in the session, or adding similar workarounds, which one shouldn't actually do in an ideal setup, of course. That being said, asking the user for their credentials again and performing a normal login is the recommended way of handling this right now.

You are thus right in that we should definitely add the functionality of an automatic login after verifying one's email address. At least, we should make it configurable so that you can choose if the user is to be logged in or not when performing the email verification.

There are a few minor reasons why this hasn't been implemented as the default, but none of those reasons is actually really serious, so an option should work fine for everybody here.

Will implement this soon!

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/ad5784364df14b4e4895d4810ec1b8dc0acd4947
 * https://github.com/delight-im/PHP-Auth/commit/838c6edf66e05727a2617d41efdcb0fe40632a14
 * https://github.com/delight-im/PHP-Auth/commit/fb982cee6ad5bff6d7f6ab5520d7fad9e8974d4c
 * https://github.com/delight-im/PHP-Auth/commit/aae0bfb5ab58d27eef57119ba124cb40c788ff77

This is available in a new major version, `v6.0.0`, which comes with a few breaking changes. For a guide on how to upgrade, please see the migration notes in `Migration.md`.
