### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by 66Martin** [delight-im/PHP-Auth#235]
Hi,

I'm quite new in PHP and Auth is my first libary installed with Composer. Maybe I did something wrong, maybe the installation text should be a little bit better, or maybe there's a bug with the new version (13 days old).

I belive, I did everthing right by installing with the composer: There are several new files at ` \php\vendor\delight-Im`. Now I want to add Auth in test.php:
```
$db = new \Delight\Db\PdoDsn('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');
$auth = new \Delight\Auth\Auth($db);
```
The result:

Fatal error: Class 'delight' not found in F:\www\test.de\test.php on line 29

**Comment by eypsilon** [comment]
First of all you have to require composers autoloader to use this Lib

```php
<?php
require_once '/vendor/autoload.php'; // fix this to wherever the vendor dir is
// here goes auth
```

**Comment by ocram** [comment]
Thanks for your question – and @eypsilon, thank you for your help!

@66Martin You say that the new files added by Composer are in `\php\vendor`, but your script is in `\www`, is that correct?

You should install the library using Composer by running the Composer command in the same directory that your script is in, i.e. in the root directory of your project. So that should create the folder `F:\www\test.de\vendor\delight-im\auth`.

Then include the autoloader using the code shown by @eypsilon or the line from the README.

Does that help?
