### ISSUE TITLE
Re-send confirmation request

### ISSUE THREAD

**Issue by steinitzu** [delight-im/PHP-Auth#24]
Very nice library! Been a breeze to integrate into my Slim3 app.  

I wanted to discuss the possibility of re-sending an email confirmation request on demand after registration. 
Case being where confirmation link is lost or expired before the user clicks it. In which case the user is stuck in limbo as far as I can tell.  

It looks to me that this would mostly be a matter of making [`createConfirmationRequest`](https://github.com/delight-im/PHP-Auth/blob/master/src/UserManager.php#L279) public.  
A DB DELETE query could also be issued on every call by default to invalidate any previous confirmation tokens for given email so that only the latest one is valid.  

Are there any potential issues with this that I'm overlooking?  

Best
Steini

**Comment by ocram** [comment]
Thanks for your appreciation!

Everything you said was correct and this is definitely a missing feature that we must add. I'd even say this should have the highest priority, since undelivered emails can be quite frequent depending on how you sent your emails, and inattentive users will cause problems, anyway.

Regarding the implementation, I wouldn't make that method public but instead create a simple wrapper. This gives us two advantages: The new wrapper can have a meaningful name like `resendConfirmation` and we can do some additional database queries in the wrapper. First, we could check that the last request has been a while ago, i.e. you shouldn't be able to request a new confirmation just ten minutes after the first one. Second, as you said, we should invalidate the old request.

Thanks for the hint, this is absolutely needed!

**Comment by steinitzu** [comment]
That sounds great!  
Rate limiting would definitely be needed too, should be configurable in some way. Maybe just by passing a min number of seconds that should have passed the function.

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/b7a47fc70752cf992778f2ac46ef901a482caf54
 * https://github.com/delight-im/PHP-Auth/commit/d86d7ffd251241265860c46bff4a36a63099ed8a
 * https://github.com/delight-im/PHP-Auth/commit/2839743c46552cd0aca53bfa9309021df67864eb
 * https://github.com/delight-im/PHP-Auth/commit/381e05f102a199b8faf3f00c10756e12cf7254fb
 * https://github.com/delight-im/PHP-Auth/commit/0bbf9d32b1045c57951538b4a55ba9441802c2c6
 * https://github.com/delight-im/PHP-Auth/commit/f83ac969d4ac42eeb18165aa4d2841083a637018
 * https://github.com/delight-im/PHP-Auth/commit/c9a4e28c7b4cdcfc0dc3d83cb7e386cd22c707d5
 * https://github.com/delight-im/PHP-Auth/commit/27adc9fa91105b9a69833411c9cda0a8e1afa90c
 * https://github.com/delight-im/PHP-Auth/commit/b3d37ada8603f4ded5af0e6874ac06203b7d15a8

This is available in a new major version, `v6.0.0`, which comes with a few breaking changes. For a guide on how to upgrade, please see the migration notes in `Migration.md`.
