### ISSUE TITLE
List of users roles

### ISSUE THREAD

**Issue by vmaysov** [delight-im/PHP-Auth#242]
Hi! Can i getting roles list of any users from DB set (That need for administration) in foreach? Example like this:

foreach($users as $user) {
echo $auth->getRolesByUserId($user['id']);
}

Maybe it will SQL-query with join or something else.

P.s. I use custom role names, by the way

**Comment by eypsilon** [comment]
> Hi! Can i getting roles list of any users from DB set
> 
> foreach($users as $user) {
> echo $auth->getRolesByUserId($user['id']);
> }

The following method returns an array with all Roles setted for a User.
```php
$auth->admin()->getRolesForUserById($userId);`
```

[/delight-im/PHP-Auth#user-content-checking-roles-1](https://github.com/delight-im/PHP-Auth#user-content-checking-roles-1)

**Comment by vmaysov** [comment]
Thank you, @eypsilon! It's working, but this way is not solution for custom role names:(

**Comment by eypsilon** [comment]
> Thank you, @eypsilon! It's working, but this way is not solution for custom role names:(

You can do this with an additional function, where you translate the Role names. At the end, the Roles are just numbers (the Naming is for us Humans :))

You can do something like
```php
// namespace My\Namespace;

use Delight\Auth\Role as RoleApi;

final class MyRole {
    
    const CUSTOM_ADMIN = RoleApi::ADMIN;
    const CUSTOM_SUPER_ADMIN = RoleApi::SUPER_ADMIN;

    public static function getMap() {
        return \array_replace(
            RoleApi::getMap(), [
                self::CUSTOM_ADMIN => 'CUSTOM_ADMIN',
                self::CUSTOM_SUPER_ADMIN => 'CUSTOM_SUPER_ADMIN',
                // your custom Roles 
            ]
        );
    }

}

// check
print_r(RoleApi::getMap()); 
print_r(MyRole::getMap()); 
```

**Comment by vmaysov** [comment]
One more tnx, @eypsilon! This is why it is not clear how to turn numbers from the `roles_mask` field into custom user roles

**Comment by ocram** [comment]
@eypsilon Thanks again – perfect explanation, solutions and code!

In order to avoid having to write the custom constant names two additional times, perhaps that could be implemented like the default `Roles` method: https://github.com/delight-im/PHP-Auth/blob/729c76668fa638769ab834c904d50696686797e9/src/Role.php#L49

@vmaysov Did this solve your problem? You use `Auth#admin#getRolesForUserById` to get the role identifiers, and perhaps the solution above to translate them to names.

If you have just a few (custom) roles, and you want to avoid the custom `getMap` implementation, that’s possible by iterating over your constants. If you’re signed in as the user, check with `Auth#hasRole` in every iteration step. Otherwise, check with `Auth#admin#doesUserHaveRole`.

**Comment by eypsilon** [comment]
> @eypsilon Thanks again – perfect explanation, solutions and code!

I've the perfect foundation to work with ;)

> In order to avoid having to write the custom constant names two additional times, perhaps that could be implemented like the default `Roles` method:
> 
> https://github.com/delight-im/PHP-Auth/blob/729c76668fa638769ab834c904d50696686797e9/src/Role.php#L49

The Reflection API is great, but for this little task it seems a bit too much for me. I'm more the pragmatic type.

BTW, grüße aus der Nachbarschaft :)

**Comment by vmaysov** [comment]
Thank you, @eypsilon and @ocram ! I want to see a list of users with their assigned roles. This will allow the moderator to know what features users have. Example:
user1 (CUSTOM_ROLE1, CUSTOM_ROLE2)
user2 (CUSTOM_ROLE4, CUSTOM_ROLE7)
etc.

A great library, but working with roles causes difficulties for me:(

**Comment by eypsilon** [comment]
> A great library, but working with roles causes difficulties for me:(

You just need to intersect the needed Roles from the RolesMap and replace the Names with the custom ones. Using the Example Class above you can do it like:

```php
/**
 * Make sure the UserId exists at this point and run
 */
$userRoles = $auth->admin()->getRolesForUserById(1);
$translateRoles = \array_replace(
    $userRoles, \array_intersect_key(MyRole::getMap(), $userRoles)
);

print_r($translateRoles); 

// [1] => CUSTOM_ADMIN
// [262144] => CUSTOM_SUPER_ADMIN
```
You could do this also in another Function to easify the task for yourself in general.

**Comment by vmaysov** [comment]
one more thanks, @eypsilon! wonderful gist, it work. I'm just confused that it turns out to be too cumbersome. I use MVC pattern and for get list of users in model class, write something code:

`public function listOfUsers() {

        $stmt = $this->dbh->query("SELECT `id`, `username`, `status`, `verified`, `roles_mask`, `last_login` FROM users ORDER BY `registered`");
        if($stmt->rowCount() > 0) {
            $listOfUsers = [];
            foreach($stmt->fetchAll() as $data) {

                array_push($data, \Engine\Helpers\Roles::getUserRoles($this->auth->admin()->getRolesForUserById($data['id'])));
                array_push($listOfUsers, $data);

            }

            return [
                'count' => $stmt->rowCount(),
                'list'  => $listOfUsers
            ];

        }   else return null;

    }`

foreach, array_push... And it is just one of method of one model:(

**Comment by ocram** [comment]
@vmaysov Sorry you had a bad experience with this method and use case. I agree it’s not perfect, and perhaps it could be improved in some way, but it’s not *that* complicated, either:

 1. You only need this if you want custom role names. Many roles are included and can be used as they are.
 2. Individual roles can be checked just as easily, using your custom role identifiers simply with the built-in methods for checking the presence of certain roles.
 3. If you have just a few different roles, and you’re getting all the user data from the database anyway, the easiest way is probably to check if your role values are in the roles bitmask from the database, as is [shown here](https://github.com/delight-im/PHP-Auth/blob/729c76668fa638769ab834c904d50696686797e9/src/Auth.php#L1643).
 4. If you really need custom roles with complete lists of roles per user, this issue right here actually affects you. But it’s not that hard after all: First, you create your custom `ManyRoles` class with the role identifiers. You would need this, anyway. No extra work. Second, you add `getMap`, as shown in the Gist or as used in the source code of this library. This is useful to have in any case. Third, and this is the only extra work, you add `getUserRoles` (or perhaps better named `translateUserRoles`) as shown in the Gist.

@eypsilon Thanks again for your appreciation and help, and greetings to the Ruhrgebiet!

**Comment by eypsilon** [comment]
> foreach, array_push... And it is just one of method of one model:(

No Pattern can ensure that every task within will be a simple one to write. And Roles in special because it's an admin-feature. But you really make it harder for yourself than it is. Because at the end, you just need translations of the Roles, that you are using. You don't change the behavior at all and in the Database, there is just a numeric representation of the setted Roles, so just translate them in the final output, somewhere in your Template. Doing translations in your Templates can easify many things plus can shrinks your Code at least a bit. And it will only be executed, when needed, not in generell.

And you don't need array_push in your method to modify the result, just do it on the fly:

```php
foreach($stmt->fetchAll() as $data) {
    $data['roles_names'] = $this->auth->admin()->getRolesForUserById($data['id']);
    $listOfUsers[] = $data;
}
```

@ocram you're right, `translateUserRoles()` is more appropriate than get. It was also my first chose, but nevertheless i ended somehow with `get`
