### ISSUE TITLE
Static expiry for confirmation request

### ISSUE THREAD

**Issue by jaydeepchauhan7** [delight-im/PHP-Auth#246]
There is no configuration for how long confirmation link valid. Right now its valid for day.  If you put settings, that will be great.
```
$expires = \time() + 60 * 60 * 24;
```

**Comment by ocram** [comment]
Thank you! It’s not obvious why users would need more time than one full day, or why developers would need to configure this differently because their users have special requirements. Are the tokens shipped to the user via snail mail? Otherwise, the user can probably just request a new token after that full day, as is already supported.
