### ISSUE TITLE
Question on Use Case

### ISSUE THREAD

**Issue by andrewteg** [delight-im/PHP-Auth#247]
Would a use case be something where you have a chain of restaurants and you need an owner, a manager who may manage 1 or more locations (see reports and add employees to their locations only), and an employee who works at but doesn't manage 1 or more locations (no reports but submits when they last cleaned the grill for example)?  Would the Roles and Permissions work for that, or is there another way to integrate PHP-Auth into a hierarchy based system like that? Is there a best practice to integrate custom data like the list of restaurants in this case?

**Comment by ocram** [comment]
What you want is *authorization*, which is part of this library (in the form of the roles and permissions), as you suggested. So that would work.

But do you want *authentication* as well? That is, do you want employees/managers/owners to authenticate with a combination of email and password or username and password? Usually you want that. Because you can’t really have authorization if you have no authentication and thus cannot be sure who the user really is. For example, without authentication, the employee could just switch to the owner role. This library here has authentication – it’s the main part even.

As for your custom data like a list of restaurants, this is *completely* independent of this library. You can put your data into separate database tables and access it as you would without this library. Just wrap some checks with this library around the accesses.

Does that help?

**Comment by andrewteg** [comment]
Yes, that helps a lot. Thank you.  We do want both _authentication_ and _authorization_ and only really have basic authentication right now, so moving to PHP-Auth for authentication would definitely help make that more robust (and likely more secure and more tested) and adding in the authorization but not being limited by custom data sounds great.  I look forward to diving into this library and appreciate your work and helpfulness here!

**Comment by ocram** [comment]
Sounds good. Thank you!
