### ISSUE TITLE
conversion script or method

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#27]
Is there a recommended way to convert an existing table of users to work with php-auth?

**Comment by ocram** [comment]
Thanks for your question!

This definitely depends on what you need specifically.

If you only need a custom prefix, this is tracked here: https://github.com/delight-im/PHP-Auth/issues/17

Alternatively, it might be more helpful if you could set the entire table names to custom strings. Support for that would have to be added.

If you even need custom *column* names, well, I'm not sure if this is a good idea. Custom column names suggest that the column *types* might be different as well. In the end, if everything is custom, there's nothing we can rely on anymore. We shouldn't support that, I'd say.

The easiest way would be to update the schema of your existing table to match the schema required by this library. But that may not always work due to existing business logic that operates on your existing tables.

**Comment by acodispo** [comment]
@ocram Thanks for your quick answer! I actually  shouldn't have any problem converting my existing schema to match. Thanks for the tip on #17, though!
