### ISSUE TITLE
registration throttling

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#276]
Hello, and thanks in advance for your attention on this!

I'm encountering throttling of registrations after only five successful requests (the sixth is throttled).

Is this the intended behavior?

Here is the test code I've used to reproduce:

```php
for ($i = 6; $i > 0; $i--) {
  try {
    $userId = $auth->register('myemail+'.$i.'@mydomain.com', 'test123!', null);
    echo 'We have signed up a new user with the ID ' . $userId . '<br>';
  } catch (\Delight\Auth\InvalidEmailException $e) {
    die('Invalid email address<br>');
  } catch (\Delight\Auth\InvalidPasswordException $e) {
    die('Invalid password<br>');
  } catch (\Delight\Auth\UserAlreadyExistsException $e) {
    die('User already exists<br>');
  } catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests<br>');
  }
}
```

This yields:

```
We have signed up a new user with the ID 1
We have signed up a new user with the ID 2
We have signed up a new user with the ID 3
We have signed up a new user with the ID 4
We have signed up a new user with the ID 5
Too many requests
```

We have a user who needs to onboard batches of clients. Our registration form takes a minute or two to fill out, so unlike the above code there are probably five requests over the course of 5 minutes at the least, not a few seconds, but the throttling still engages.

I'm aware of #253 but the behavior we're seeing above doesn't seem to line up with [the limits you documented there](https://github.com/delight-im/PHP-Auth/issues/253#issuecomment-819538573). Before we implement custom throttling for registrations I just want to verify that this isn't a bug.

We are still on version 8.2.2 in case it matters.

Thanks for your time!

**Comment by ocram** [comment]
Thank you!

The limits documented in the issue that you linked to are not for the registration feature. Each feature has different throttling, as the needs naturally vary as well.

Is your application behind a proxy, e.g. a load balancer, perhaps? If you don’t pass the real IP address of the client in the constructor then, multiple clients may be treated as one for throttling purposes (because they will appear to have the same IP address).

Or is your onboarding done from a single machine in a controlled environment? If you try to create more than 5 accounts from a single client machine within a short time, yes, that will trigger a limit. This is unlikely to happen in normal usage. And if you still want to do it, because you trust the client, there is no reason why you couldn’t just disable throttling for that one client (and for that one feature), right?

(Your library version is fine.)

**Comment by ocram** [comment]
Yes, looks like the best solution here is indeed managing your own allow list of trusted IP addresses and then setting the fourth argument of the `Auth` constructor (i.e. throttling on or off) based on whether the client’s current IP address is in the allow list.

**Comment by Paulo--M--** [comment]
It's not directly connected to the registration process but I'm interested in bypassing throttling in specific situations. Unfortunately, I'm not an experienced programmer so... Regarding the statement _"managing your own allow list of trusted IP addresses and then setting the fourth argument of the Auth constructor (i.e. throttling on or off) based on whether the client’s current IP address is in the allow list."_, could any kind soul point me in the direction of exactly how this is done? I mean, 1) how do I manage a list of trusted IP addresses, and 2) how do I tell the constructor to disable throttling based on the list of allowed IPs? An example snippet of code would be GREATLY appreciated. Thanks in advance.
