### ISSUE TITLE
Failing to check if email is verified

### ISSUE THREAD

**Issue by prometeusweb** [delight-im/PHP-Auth#28]
In Auth.php the authenticateUserInternal method is failing to check if user column 'verified' is set to 1 because it is strictly comparing a string with an integer:

`if ($userData['verified'] === 1) {`

should have been casted to an integer:

`if ((int)$userData['verified'] === 1) {`

is it correct?

**Comment by imbr** [comment]
You are right,
Some versions of PHP7 need **(int) $ userData ['verified']** to work properly.
You can also set **$userData['verified'] == 1**

Ł

**Comment by ocram** [comment]
Thanks, @prometeusweb and @imbr!

Are you really sure that your setup meets the requirements outlined in the README? To be specific, do you really have the MySQL Native Driver (`mysqlnd`) installed and in use by PHP?

As far as currently known, this library does not forget to check anything, but instead, you must have the correct driver so that the database results have the correct types already and casting is not necessary anymore.

@imbr Are you really sure that this varies between minor versions of PHP 7? Can you point out specific versions where this happens?

**Comment by prometeusweb** [comment]
@ocram you're right, I'm testing it under Xampp that uses libmysql  as mysql driver so I think this is the point. However in order to make it work under my dev environment I had to add the type casting because Xampp doesn't offer a native way to change the mysql driver.

**Comment by ocram** [comment]
@prometeusweb Are you sure? XAMPP should really have this. Maybe it's just the specific version of XAMPP that you're using which doesn't have this?

A few reasons why I think XAMPP must have some way to enable `mysqlnd`:

 * It has been the default driver for `mysql`, `mysqli` and `pdo` for quite some time now.
 * It is compiled and built-in by default in PHP, so XAMPP would probably want to ensure compatibility.
 * XAMPP lets you install several pre-packaged applications (e.g. Wordpress, Drupal, etc.) and some of them will probably need `mysqlnd`.
 * The `readme_en.txt` file in the root folder of the current XAMPP (PHP 5.6.30) for Windows says:

   > For trouble with the mysql connection (via mysqlnd API in php) see also the startpage

   They wouldn't say that if `mysqlnd` wasn't included, would they?

 * The file `php/snapshot.txt` of the current XAMPP (PHP 5.6.30) for Windows includes `mysqlnd` in the list of "Built-in Extensions".

**Comment by ocram** [comment]
See also https://github.com/delight-im/PHP-Auth/issues/7, https://github.com/delight-im/PHP-Auth/issues/18 and https://github.com/delight-im/PHP-Auth/issues/19. But again, XAMPP should have support for `mysqlnd`.
