### ISSUE TITLE
Sqlite setup schema

### ISSUE THREAD

**Issue by prometeusweb** [delight-im/PHP-Auth#30]
As I'm using a sqlite db to store user auth I wanted to share the schema to setup the tables for PHP-Auth: 
[schema.sqlite.txt](https://github.com/delight-im/PHP-Auth/files/1064658/schema.sqlite.txt)

**Comment by ocram** [comment]
Thanks a lot!

Will definitely review and test this and include it here for everyone, if possible.

Adding other database systems is something we really need to do here and also need help with. SQLite and PostgreSQL have the highest priority. So that's great to have!

Did you encounter any problems so far, using this library with SQLite instead of MySQL? Did you need to make any adjustments to the PHP code or to the database schema (other than just "translating" it to SQLite)?

**Comment by prometeusweb** [comment]
Glad if it will be useful! 
Had no problems at all to use the library with sqlite, I just initialized the pdo connection with
`$db = new PDO('sqlite:' . $sqliteFilePath);`
`$auth = new \Delight\Auth\Auth($db, true);`
and everything worked fine.

**Comment by ocram** [comment]
Works fine!

Though I had to add a little type cast in order to make the state of account verification work: https://github.com/delight-im/PHP-Auth/commit/ee485f99ab242002233c8669bd0f5507a4eff82b Perhaps you had that fix implemented for other purposes already.

Merged your schema in https://github.com/delight-im/PHP-Auth/commit/45553afaea9fc9fa2aa4daf8ffa28e8b7b7d2590 and documented it in https://github.com/delight-im/PHP-Auth/commit/26cb41e992d000eb0c11573b831672e2e48e0ad0.
