### ISSUE TITLE
Using Content-Security-Policy instead of X-Frame-Options

### ISSUE THREAD

**Issue by brotkiste** [delight-im/PHP-Auth#32]
In "enhanceHttpSecurity" X-Frame-Options is used do prevent clickjacking. Would it be possible to use Content-Security-Policy instead?

This would allow to add exceptions without having to change PHP-AUTH or removing the X-Frame-Options and readding it with changed parameters.

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)

Thank you for this amazing piece of work, I really enjoyed integrating the authentication system in some of my projects :)

**Comment by ocram** [comment]
Thanks a lot for your appreciation, and for making this good point about `X-Frame-Options`!

As per [Content Security Policy Level 2 § 7.7.1](https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options), the CSP can indeed replace `X-Frame-Options` with similar effects. But that same section also says:

> The frame-ancestors directive obsoletes the X-Frame-Options header. If a resource has both policies, the frame-ancestors policy SHOULD be enforced and the X-Frame-Options policy SHOULD be ignored.

So why don't we keep the old header? If popular browsers (e.g. Chrome and Firefox) follow that specification correctly in their latest versions, let's keep the old header and just add the new header in addition to that.

Apart from that, I have only ever seen multiple CSP directives in *one* header, separated with `;` between them. Looking at the specification again, [Content Security Policy Level 2 § 3.4](https://www.w3.org/TR/CSP2/#enforcing-multiple-policies) says that multiple CSP headers are in fact possible. But it says that requests must pass *all* CSP headers. So if we added

```
Content-Security-Policy: frame-ancestors 'self'
```

to this library and you tried to add

```
Content-Security-Policy: frame-ancestors example.com
```

in your application, additionally, would that really work? Did you try that? In both Firefox and Chrome, for example? Reading the specification, my guess would be no.

That, however, is the requirement for your change to have any advantage, right?

**Comment by brotkiste** [comment]
Chrome does ignore X-Frame-Options when the CSP frame-ancestors are defined, Firefox doesn't.

I tried placing the CSP headers at different places, this worked for both browsers.

Inline scripts and styles did also work for both browsers, I didn't have the time to check for eval, I can do that later.

I'm currently using a workaround for this, removing the X-Frame-Options header before adding my CSP header, so if you prefer to keep X-Frame-Options I'm ok with that.

`header_remove('X-Frame-Options');
 header("Content-Security-Policy: frame-ancestors 'self' example.org");`

**Comment by ocram** [comment]
Thanks!

Since that last code snippet you posted is so short and effective, we should also consider just leaving everything as it is, avoiding the risk of introducing any breaking changes, inconsistencies, or problems with (older) browsers.

Yet another possibility would be to add an option on the instance where you can enable or disable those headers, e.g. `setEmbeddingAllowed`. If enabled (default), it sends the two headers

```php
\header('X-Frame-Options');
\header("Content-Security-Policy: frame-ancestors 'self'");
```

and otherwise does nothing.

**Comment by brotkiste** [comment]
I think if you keep it as it is, the workaround should be documented in someway.

I'm not sure it's worth the added complexity to add another option. In this case I would prefer to only switch from X-Frame-Options to CSP

**Comment by ocram** [comment]
Confirming my earlier doubts, it turns out that the proposed semantics are not actually valid, as per [CSP Level 2 § 3.1](https://www.w3.org/TR/CSP2/#content-security-policy-header-field):

> A server MUST NOT send more than one HTTP header field named Content-Security-Policy with a given resource representation.

The section that was mentioned earlier, [CSP Level 2 § 3.4](https://www.w3.org/TR/CSP2/#enforcing-multiple-policies), just describes what happens when multiple *policies* are found, which may (and should) be in a *single* header field. The examples apparently just show what a client may encounter in the wild. Apart from that, the section is "not normative".

Further, as per [HTTP/1.1 § 3.2.2](https://tools.ietf.org/html/rfc7230#section-3.2.2):

> A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list [i.e., #(values)] or the header field is a well-known exception (as noted below).
>
> A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma.

This does not match what we need here, which is why Firefox 54 (What version did you try?) correctly merges the two fields

```
Content-Security-Policy: frame-ancestors 'self'
Content-Security-Policy: frame-ancestors sub.example.org
```

to

```
Content-Security-Policy: frame-ancestors 'self', frame-ancestors sub.example.org
```

which is obviously invalid syntax and in practice has the effect of `'none'`.

Thus, the correct solution remains, as you suggested:

```php
\header_remove('X-Frame-Options');
```

This is now documented: https://github.com/delight-im/PHP-Auth/commit/829d5614edcdfe26edfc8fc925841b22cf35e9a9

Thanks for bringing this up!

**Comment by brotkiste** [comment]
I used Firefox 54, and according to developer tools, the header was merged to 
`Content-Security-Policy: frame-ancestors 'self' example.org`
The documentation looks good, it was great working with you :)
