### ISSUE TITLE
Impossible to use any anti-CSRF library

### ISSUE THREAD

**Issue by ponasromas** [delight-im/PHP-Auth#35]
I want to use https://github.com/gilbitron/EasyCSRF or https://www.owasp.org/index.php/CSRFProtector_Project but it's not possible as PHP-Auth running it's own session and I always receive warning:

`Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time <...> vendor/delight-im/auth/src/Auth.php on line 73`

How to resolve this? I'am unable to use any application which do it's own session_start();

**Comment by mhmd1983** [comment]
I think u should use AUTH before CSRF library 
I don't know ur code but i think you're using csrf library before auth library you should initiate AUTH 1st then use CSRF

**Comment by ocram** [comment]
Thanks for your feedback on this issue, @ponasromas!

Are you sure that it's *any* anti-CSRF library? I doubt it, because you could easily build such a library in a way so that it would just pick up our session and use that.

So the problem seems to be that those anti-CSRF libraries create their own sessions, and this library here does also modify the session configuration and starts the session.

The specific warning message that you reported, however, is clearly a result of loading this library here *after* other (anti-CSRF) libraries. Can you switch that, so that you load and initialize this library here *before* the others, as @mhmd1983 suggested?

In general, *we* could also just pick up the session created by other libraries. But we want some secure defaults and would like to enforce certain guarantees, as can be seen here: https://github.com/delight-im/PHP-Auth/blob/829d5614edcdfe26edfc8fc925841b22cf35e9a9/src/Auth.php#L67 So if another library creates the session for us and we just pick it up, you might lose all those guarantees about the security of your application, e.g. session IDs might start appearing in query strings, cookies might be accessible by JavaScript, etc.

**Comment by ponasromas** [comment]
Hello @ocram , thank you for answer. Indeed, I have managed to resolve this problem. The fault was not in PHP-auth, but in order how libraries are loaded... And that was sorted out after 2 days investigation 👎 . 

However, it's a pleasure to work with PHP-auth library! Very user friendly and understandable to noobs :) . Waiting for new versions with more features.

**Comment by ocram** [comment]
That's great, thanks! (Although finding out about it that late probably wasn't ... Sorry!)

In general, it looks like this is an issue that many others could have as well. In the hope of saving others the time tracking down this problem, an explanation has been added to the README: https://github.com/delight-im/PHP-Auth/commit/6156b1c13580c1b87b3cda0a72e1fd795d4bc53f

Thanks for your appreciation!
