### ISSUE TITLE
Headers already sent on logout

### ISSUE THREAD

**Issue by luca-parolari** [delight-im/PHP-Auth#44]
I'm having an issue using your logout method.

I'm using an MVC pattern so there is a link on my view like `http://mysite/Account/Logout` from which i call `logout` from PHP-Auth lib.
This produce to me the error `Delight\Auth\HeadersAlreadySentError`, with this stack trace:
```
#0 C:\xampp\htdocs\auth-bcv\vendor\delight-im\auth\src\Auth.php(315): Delight\Auth\Auth->setRememberCookie(NULL, NULL, 1502959682)
#1 C:\xampp\htdocs\auth-bcv\vendor\delight-im\auth\src\Auth.php(414): Delight\Auth\Auth->deleteRememberDirective(7)
#2 C:\xampp\htdocs\auth-bcv\Controllers\AccountController.php(411): Delight\Auth\Auth->logout()
#3 C:\xampp\htdocs\auth-bcv\Routes.php(61): AuthBcv\Controllers\AccountController->LogOut(Array)
#4 C:\xampp\htdocs\auth-bcv\Routes.php(97): call('Account', 'LogOut', Array)
#5 C:\xampp\htdocs\auth-bcv\Views\Shared\_Layout.php(23): require_once('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\auth-bcv\index.php(37): require_once('C:\\xampp\\htdocs...')
#7 {main}
```
 that i can't understand how to solve.

How can i fix this problem? Is there something wrong in my use of logout?

**Comment by ocram** [comment]
The message "Headers already sent" always means that you're trying to modify the HTTP response headers (in this case, this is done for you by this library) *after* some actual output (usually HTML) has already been sent, which is not possible.

From your stack trace, it seems that the line causing the problem is line 411 in `AccountController.php`. Can you check that? There must be a way for you to move anything that affects the HTTP response headers (like a call to the `logout` method) to an earlier step in the request's execution.

**Comment by luca-parolari** [comment]
Ok, i've found the problem.

My infrastructure was loading the layout (which was ouputting HTML data on my browser) before calling actions in controller.
The problem is that if i don't call layout, pages cannot be injected into the body of my layout, avoiding the controller to execute code.

To solve the problem I've moved the logout action before the layout call with a rude check, but it works, so...

```
if (Routing::getAction() == 'LogOut')
    $auth->logout();

if ($auth->isLoggedIn() == false)
    require_once('Views/Shared/_LayoutAuth.php');
else
    require_once('Views/Shared/_Layout.php');
```

Thank you very much for the help!

**Comment by ocram** [comment]
Thanks for sharing your solution! That's exactly what I had in mind.
