### ISSUE TITLE
No test/exception for DB failure on construct

### ISSUE THREAD

**Issue by 32Blahs** [delight-im/PHP-Auth#45]
Nice library (although wish you would also include a manual include/no autoload include.php, had to do that myself and it's painful because the dir structure sprawls a bit, I don't like autoloaders....).

When instantiating a PHP-Auth, there doesn't seem to be a way to immediately test or catch whether there was an issue with the database / setup. 

Testing whether the setup was ok is pretty critical for an authentication/security mechanism. If there was an error connecting to the DB or reading any data, I want to die() immediately rather than risk some unexpected insecure code flow.

For example, the following doesn't throw any exception. I tried using isLoggedIn() to force a throw, but nothing happens:

```
$db = new \Delight\Db\PdoDsn('mysql:dbname=SOME;host='INVALID', 'DATABASE', 'CONFIG');
$auth = new \Delight\Auth\Auth($db, SITE_HTTPS_ENFORCED, FALSE, NULL, "php_auth_");
$auth->isLoggedIn(); // should fail, but doesn't throw?
```
However later if I call
`$auth->login("deliberately", "junkdata");
`

I get a Delight\Auth\DatabaseError thrown.

This seems wrong workflow to me. I understand why it happens due to PHP-DB, but in my opinion this isn't right. Regardless of lazy load in PHP-DB (which I don't use anywhere else in my code), PHP-Auth should actively check for valid DB connection on instantiation. If PHP-Auth doesn't throw when I instantiate it with all the data necessary to set up, the logical assumption is everything is working.

Ability to immediately dump out on critical error of PHP-Auth failure to access DB is essential. It creates the following scenario, for example when allowing a password reset after form submission:

```
$db = new \Delight\Db\PdoDsn('mysql:dbname=SOME;host='INVALID', 'DATABASE', 'CONFIG');
$auth = new \Delight\Auth\Auth($db, SITE_HTTPS_ENFORCED, FALSE, NULL, "php_auth_");
$auth->forgotPassword("irrelevant - db config is bad", function ($selector, $token)
{
// blah
});
```

The exception thrown is InvalidEmailException, when actually it should be DatabaseError and handled completely differently.

I'd be happy with a ->Connect method, to force immediate DB connection. There's no penalty here as you're only ever instantiating PHP-Auth when you need it for something...

**Comment by 32Blahs** [comment]
Also in an unrelated suggestion, can you set foreign key constraints on the SQL please? Makes things clearer and more consistent, plus extending the user data into another table is also clearer.

One additional suggestion ref the "add extra user fields". Could you consider adding one additional column that acts as a key to another table, which is programatically retrievable from the API? I have a scenario where I have a table of all potential users, and the PHPAuth table of "registered" users. The primary key id for my table will never match the PHPAuth table, so my only current option is to hack around your API or have a separate join table.

It's useful in cases where you may have a table of customers of a service, and you want to provide a web portal for the subset of those customers who register online. 

Thanks

**Comment by 32Blahs** [comment]
Forget the suggestion in my second post. I've written an extend to PHPAuth that allows an unlimited number of extra user data columns in the users table, and handles requests for that extra data transparently within PHPAuth without hard coding column names. 

I'll share that, plus admin and management enhancements for a proper user manager system, plus an internal access control extension (makes the role feature easily usable), in a few days.

**Comment by 32Blahs** [comment]
FYI I wrote this report originally before I went poking around in your code, so my thoughts here have been superseded by my other posts (which you've closed.....)

> Correct. Because isLoggedIn doesn't use the database. See above. Why should it check the database if it doesn't need the database?
>  because we want and do have lazy loading here

Because that's insecure. You shouldn't defer checking the right of user to take an action, it should be checked at point-in-time-of-request. isLoggedIn doesn't actually check whether the user has the right to be logged in, it just checks whether there's a session var set. I've mentioned this in some other posts that you've closed, and this is exactly why I wrote isLoggedInHard() in my extend. 

Because you rely on the session for IDAM, and processRememberDirective() relies on isLoggedIn(), the user state is not authoritative in code. 

User logs in and uses the system. Administrator then decides that the user should be deleted/disabled/role changed/whatever. Administrator makes the change (deletes the user in the DB), yet the user can still happily use the system because the code is only checking whether the session vars are set, not whether the user account/roles/rights etc actually exist in the DB at a given point in time. This is why I moved the "authority" for user state back to the DB in my extend. isLoggedIn() should only be used for control of views.

Now if your isLoggedIn was authoritative (like my isLoggedInHard), then it would check the DB to actually confirm login, and DatabaseError would be thrown.

**Comment by ocram** [comment]
> FYI I wrote this report originally before I went poking around in your code, so my thoughts here have been superseded by my other posts (which you've closed.....)

No problem. The reasons for closing other posts were outlined in those posts.

> Because that's insecure.

It's not. Please stop making such claims without evidence.

> You shouldn't defer checking the right of user to take an action, it should be checked at point-in-time-of-request.

It is.

> isLoggedIn doesn't actually check whether the user has the right to be logged in

It checks whether the user has successfully logged in before and has a valid session. That's also what it says it does.

> it just checks whether there's a session var set.

Yes, because that's how you generally do it.

> User logs in and uses the system. Administrator then decides that the user should be deleted/disabled/role changed/whatever. Administrator makes the change (deletes the user in the DB), yet the user can still happily use the system because the code is only checking whether the session vars are set, not whether the user account/roles/rights etc actually exist in the DB at a given point in time.

Now it becomes clear what you really want, which seems to be something like https://github.com/delight-im/PHP-Auth/issues/52. That certainly makes sense and is a valid point.

But duplicating part of the session management in your database and performing a database request every time you want to check if a user is logged in is definitely not the way to go.

How you can revoke sessions is completely unrelated to this library and the library allows you to control that without touching the library's code. In PHP, the two configuration values [`session.save_handler`](http://php.net/manual/en/session.configuration.php#ini.session.save-handler) and [`session.save_path`](http://php.net/manual/en/session.configuration.php#ini.session.save-path) determine how and where session data is saved exactly. That may be a file-based solution, some *fast* database (e.g. Redis), etc.

If that's really what you want, the issue linked above suggests a way how we might incorporate that into this library. In the meantime, feel free to track and destroy sessions manually.

**Comment by 32Blahs** [comment]
> It is.

How and where?

> Yes, because that's how you generally do it.

We'll have to disagree again. Existence of a session var that was created at some point in the past when a login was valid doesn't authoritatively confirm whether that session (login) should be valid now.

Unless yet again I've missed something.

**Comment by ocram** [comment]
Sorry, I don't think I can add anything new to this discussion, as I've explained everything related to how this library works and why this is an acceptable way to do it.

As I said, this is exactly what sessions are for. You have sessions so that you *don't* have to check the database on every single request. If you did, why would you need sessions? Proper invalidation of sessions is another topic, and I pointed you to the PHP mechanisms that you need for that.

The referenced issue for remote logouts and invalidation of other sessions for the user seems to be what you want. So that's tracked there. Lazy loading for the database will be kept.
