### ISSUE TITLE
Security issue (and why autoloaders are a bad idea)

### ISSUE THREAD

**Issue by 32Blahs** [delight-im/PHP-Auth#48]
For clarity, the issue is with the way examples in the docs are written, combined with the way the PHPAuth library uses your DB library. It's creating a false sense of security.

The simple version: all of the examples in the documentation directly use unchecked POST input for params. This is OK in terms of SQL injection, because the underlying DB lib uses PDO prepared statements which automagically escapes everything.

However it does NOT prevent app level security risks. For example, a user can write javascript into a param (e.g.: change my email address). The script will be escaped when written to the DB, but unescaped on read and output in original format if echo'd to a page.

Assuming you code an admin system that lists all the users with their email addresses in a table, so you can take admin actions, this is a flaw - a user can execute code in the admin view. 

So anyone using this library must ensure that all user input from POST and GET etc are correctly sanitized, despite PHPAuth documentation not mentioning this and explicitly using it in the examples (and, on assumption, relying on PHPDB PDO automagic to secure input). The OWASP recommendations are a good starting point: https://www.owasp.org/index.php/OWASP_PHP_Filters

The autoloader compounds this problem. If you simply use the autoloader, you can be forgiven for not realizing that PHPAuth uses PHP DB library & what protection it actually does/does not offer. This is why autoloaders are a bad idea - you don't know what dependency code is being included in your project simply by using a library.

In summary, either the documentation needs to be changed to highlight that POST and GET must be sanitized and should absolutely not be passed to PHPAuth unchecked. Or PHP Auth must be changed so that data is properly escaped at all stages (I'd suggest this is a better option, because nobody should have a username or email address that includes < script > etc

The problem is that at the moment you have a half way solution - some issues are prevented due to PDO automagic, but other issues are not prevented. Less savvy users of this code may assume that the protection offered by PHPDB (from the docs: "Safe against SQL injections through the use of prepared statements") is sufficient, when it's absolutely not - that is, if they even realize the additional libs that are in use due to autoload.

Happy to be told I'm wrong here because I don't use PDO, I use mysqli, but looks like a gap to me.

**Comment by rgvy** [comment]
(Note: I don't speak for the project)

Regarding <script> attacks, the framework's recommended template engine is twig and the default configuration properly escapes output for html. Perhaps there could be security features added to `Input` but for most users, twig's security is sufficient.

But about autoloaders in general -- don't write them off yet. It seems your criticism of autoloaders is that their users ignore dependencies. The problem isn't with autoloading classes, but rather autogenerating the autoloading code (typically via composer). The way I handle it, which you might appreciate, is to manually write the autoload function. This forces me as a developer to manually locate and understand the dependencies.

**Comment by 32Blahs** [comment]
Rgvy, have to say I can't find any reference to twig in a scan of the docs, and actually I've never even heard of twig before your post. My thoughts were more along the line of how this lib is very easy to use, light and simple to implement, which lends itself to potentially less tech/security savvy people not realizing there's an implicit reliance on twig/any other framework for security. I like how lightweight it is - I'm looking at using it on my bespoke (all custom, no php framework) project. But I think some users will end up security undermining themselves due to the examples vs PDO vs lib level security I outlined. Easily fixed with a note at the top of the documentation and simple escaping in the examples, but very important for a security library that less aware users may take at face value as "secure, as per documentation and examples"

Ref your comment on auto loaders, you're absolutely correct and I wasn't accurate enough in my criticism. My issue is with use of composer etc, and I agree your approach makes absolute sense / best of both worlds.

**Comment by rgvy** [comment]
(Again, I can't speak for the project)

Sorry, I was assuming that you were using the whole framework like myself. (See: https://github.com/delight-im/PHP-Foundation). The templating system (twig) seems to be best of breed for php. The other features of the framework (routing, ORM, etc) are also very nice, elegant, and minimal.

To further fan the flames against composer, there is another serious drawback: auto updating of dependencies. By forcing a manual update of source code, the developer can use the opportunity to research what has changed and consider any breakage...

**Comment by 32Blahs** [comment]
Aha, I didn't even see that framework. Skimmed the docs quickly, although it's not for me it's still interesting stuff. They do the input/output cleaning in a similar way to my approach. You're right though, now I see why you said the framework handles it.

Overall I'm pretty impressed with the light, clean code in these libs. Now I just need to break out that mail utility code from the framework and borrow it, was just about to hand craft one myself too ;-)

**Comment by 32Blahs** [comment]
Rgvy, you may be interested in my extend to this library, please see my post on this forum. Thanks

**Comment by rgvy** [comment]
Thanks, I'll take a look.

Generally the project developers are happy to incorporate fixes and features in newer versions. I'd guess that they're on vacation lately...

**Comment by 32Blahs** [comment]
Yeah that's cool, and they've done a good job with the core. That's why I wrote the code as extend and overrides rather than rewriting their core code. Easier for them (and others) to see what I've done and why, keeping complete compatibility with core PHPAuth. If they want to incorporate my code, great. If not, also no problem - I'll keep it as an extend for now.

Good luck :-)

**Comment by rgvy** [comment]
When they get back, I'm sure they'd be glad to discuss and incorporate specific enhancements.

Thanks for contributing! I love using this framework

**Comment by 32Blahs** [comment]
Proper role management system added to my extend.

**Comment by ocram** [comment]
@rgvy Thanks for your help again!

@32Blahs Thank you for your thoughts on this! Fortunately, there is no security issue here. The problems you describe simply result from a wrong understanding of output escaping and where/when it should be applied.

Users having a username of `<script> ... </script>` is absolutely fine (security-wise), though uncommon, of course. Output escaping is context-specific and should only be performed when you know the exact context. And that is always immediately prior to sending the output.

I might accept usernames containing JavaScript code, because my application talks plaintext over a HTTP API. Your application, on the other hand, might output HTML, as you suggest, and as most applications do. But not all applications do that. My API might also output JSON, which needs other escaping than HTML does.

The point is, you should never apply escaping to your *input* but only to your *output*. You don't want your `I<PHP` user to be called `I&lt;PHP` in your database. What happens if you want to write a letter to that user on good old paper? Send them a PDF invoice? There's no reason why they should be called `I&lt;PHP` in those other formats and in your database.

Apply output escaping when you're actually sending output to the user and you're safe. Template engines such as Twig do this by default, and as such generally improve the security of your application, but they're not required.

Using raw `$_GET` and `$_POST` data for calls to this library is fine, you should be safe against SQL injections. But regarding other vulnerabilities, such as XSS and content injection, this library is not related to their causes or prevention in any way. In so far, the examples are all valid. Apply output escaping correctly, and again, you should be safe against these two specific types of vulnerabilities.

Last but not least, @32Blahs and @rgvy, dependency managers and autoloaders really aren't part of the problem here. When using Composer, simply run `composer show --tree`, or just `composer show`, and you will know exactly what dependencies are used in your application. No need to have all the extra effort of manual dependency management to achieve just that. And, by the way, there is no auto-updating with Composer if you use it correctly. You will have to run `composer update` manually to trigger the update, and you will see exactly which dependencies have been updated from/to which versions. Look at the respective dependencies' source control or changelogs to see what is new and what might break.
