### ISSUE TITLE
Fixed issues, added features

### ISSUE THREAD

**Issue by 32Blahs** [delight-im/PHP-Auth#49]
There's some other security issues with this library, and it's missing a lot of admin features. 

I've fixed all that, made the login system authoritative, and done some other stuff.

I also dislike how unfriendly github is, so I've done my best with the files. Good luck.

https://github.com/32Blahs/PHP-AuthExtra

**Comment by 32Blahs** [comment]
I've updated the code with an extendable role management system. Now you can manage all your access permissions from the database, and programmatically manage them from the admin system too.

This is the last update I'll do on the code until the original developers of PHP-Auth pick it up and decide whether they want to incorporate or not (if not, I'll recode the extend into the base lib for speed).

**Comment by ocram** [comment]
Thanks!

> There's some other security issues with this library

I have to contradict that claim. I have not seen any description of an actual vulnerability in this library that does not result from a wrong understanding of it. Though whenever you should discover such a vulnerability, please report it.

> and it's missing a lot of admin features

Of course! Everyone's needs vary, and the admin interface is a bit younger than the rest of the library, so future additions are definitely expected.

> This is the last update I'll do on the code until the original developers of PHP-Auth pick it up and decide whether they want to incorporate or not (if not, I'll recode the extend into the base lib for speed).

We would love to discuss individual problems and features and incorporate fixes and improvements where possible, but we will not sort through complete forks, especially those with different underlying concepts, and see what we can pick up.

**Comment by 32Blahs** [comment]
> I have not seen any description of an actual vulnerability in this library that does not result from a wrong understanding of it.

I disagree with some of your other comments, especially around data sanitization, but let's leave that alone because it's up to you. Another flaw is around the reliance on session data for login status, as I explained in my other reply to you today (in the open issue).

> We would love to discuss individual problems and features and incorporate fixes and improvements where possible, but we will not sort through complete forks, especially those with different underlying concepts, and see what we can pick up.

That's a shame, I'd have hoped that after I took the time to share my enhancements in an easy to review way, you'd have taken a look at them to at least see if they are of any interest. It's not a true fork - I haven't changed your core code beyond removing final and private from classes and methods so I can inherit and override as required.

I'm not really willing to open new topics and retype descriptions for each of the enhancements and updates I've made as that's impractical. So in summary my extend:

- Allows easier management of roles for the user and via admin() interface
- Provides the concept of "activities" via a database table, so that app level code can simply call $Auth->canUserPerformActivity() to check access permissions to app parts (follows the suggestion in the PHPAuth docs, but has the advantage of allowing the creation of views so that app level admins can change access controls without changes at the app code level)
- Provides methods through admin() interface to manage those activities against roles - allows adminstrators to edit which roles can take what actions/activities in the app
- Allows unlimited extra data to be stored and changed for each user simply by adding extra columns to the PHPAuth users table, solving a feature request that a few people have asked for
- Provides hard login check to ensure the current user really is allowed to log in and take actions, versus the current soft session only check in PHPAuth which is insecure
- If a user is logged in, and an administrator changes properties of that user (e.g.: roles), enforces a relogin so that the new properties are picked up
- Allows retrieval of an array of users obeying SQL OFFSET and LIMIT, for showing paginated lists of users (e.g.: datatables table in the admin system loading large user database by ajax)

If there's no interest I'll leave the discussion there and just recode your library for my own use, no sense in sharing further updates if they're not of interest.

Thanks for a good core lib, it saved me a couple of days writing one myself.

**Comment by ocram** [comment]
> I disagree with some of your other comments, especially around data sanitization, but let's leave that alone because it's up to you.

I don't think that's a matter of opinion or taste, but a matter of facts and what solution is actually better. But yes, let's end that discussion.

> Another flaw is around the reliance on session data for login status, as I explained in my other reply to you today (in the open issue).

As explained, that is not a flaw. The proposed additions from https://github.com/delight-im/PHP-Auth/issues/52 indeed seem to be what you want here.

> That's a shame, I'd have hoped that after I took the time to share my enhancements in an easy to review way, you'd have taken a look at them to at least see if they are of any interest.

Oh, I have! I have both read your source code and checked the list that you provided in your post above again. I would never ignore such effort. But we really don't think that way is the best way to collaborate. Instead of changing everything you don't like about a library and adding everything you're missing, we are convinced that addressing specific issues, talking about problems and delaying the implementation until some consensus has been reached is the way to go.

> I'm not really willing to open new topics and retype descriptions for each of the enhancements and updates I've made as that's impractical.

No problem. I have seen all the features and just don't want to incorporate any of them as they are, except for the `Auth#getUserRoles` method, the deletion of individual session fields in `Auth#logout` and perhaps some of the administrative stuff which we might add in the future. That's because we disagree in either concept or implementation on most of the things.

> Allows unlimited extra data to be stored and changed for each user simply by adding extra columns to the PHPAuth users table, solving a feature request that a few people have asked for

We had discussions about that already. We have this point in mind, but we're just not sure whether that "extra columns" or "extra profile fields" is the best solution. Among other things, you lose type safety and have no schema to rely on, losing valuable guarantees a proper database schema would provide. In the end, you will always have other database tables with additional user data, anyway. Your business logic will surely handle some other data related to users. So why not handle these additional profile fields the same way?

**Comment by 32Blahs** [comment]
Ok well we seem to have a fundamental disagreement on many of these things (not on the purpose of your lib, which I agree with, but with the implementation or gaps in certain things).

I'll just leave it all there, will rewrite into your code and will keep it local as I don't feel there's much point updating the fork here on github. 

Thanks for the core lib, as I said above it's a good starting point for what I needed and saved me some time. Cheers.

**Comment by ocram** [comment]
No problem. Thank you!
