### ISSUE TITLE
Questions about db schema

### ISSUE THREAD

**Issue by natoot** [delight-im/PHP-Auth#5]
Hello!
First, thanks for this nice library.
I just have a couple questions about the database schema you use:
- Is there any reason you use MyISAM over InnoDB (with foreign keys)?
- Some columns are defined with a latin charset, is there a reason for that also? (simple curiosity)

Thank you!

**Comment by ocram** [comment]
Thanks for these excellent questions!

 * Regarding MyISAM vs InnoDB: Not really. There's indeed no specific reason. There was no real need for foreign keys yet, but we may definitely consider switching to InnoDB in the future.
 * Regarding the `latin1` charset: Yes, there is a reason. That charset is only used for columns storing tokens, hashes, etc. These do not and will never store anything other than ASCII chars. While there are only minor advantages in using `latin1` here, there are absolutely no disadvantages, either.

Any changes that we could do here would probably be of low priority only, since they affect neither functionality nor security.

**Comment by natoot** [comment]
Fair enough. :)
Thank you for that answer!

**Comment by ocram** [comment]
No problem, hope that made sense :)
