### ISSUE TITLE
Provide a way to revoke sessions and to perform remote logouts

### ISSUE THREAD

**Issue by ocram** [delight-im/PHP-Auth#52]
Whenever a user signs in, we could add the session ID, together with the ID of the user who has just logged in, to the database (into some new table that will be created for that purpose).

It might even make sense to track the IP address and user-agent string there as well, if not disabled for privacy reasons.

```sql
CREATE TABLE users_sessions (
    user_id int(10) unsigned NOT NULL,
    session_id varchar(256) CHARACTER SET latin1 NOT NULL,
    user_agent varchar(192) DEFAULT NULL,
    ip_address varchar(45) DEFAULT NULL,
    expires_at int(10) unsigned NOT NULL,
    PRIMARY KEY (user_id, session_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
```

In the two methods `UserManager#onLoginSuccessful` and `Auth#logOut`, we would always update the database with the latest information about the current session. That may not be enough, though. The `expires_at` column in the database schema is the critical piece of information here.

That would allow us to show users a list of all sessions (or devices) where they're currently logged in.

In addition to that, any of these sessions could then be killed remotely, e.g. as in the following example, which has neither been tested thoroughly nor been executed at all, though:

```php
function destroySessionById($id) {
	$pausedSessionId = '';

	// if a session is currently active
	if (\session_id() != '') {
		// if that session is not the one we're trying to destroy
		if (\session_id() !== $id) {
			// remember which session it was that we interrupted
			$pausedSessionId = \session_id();
			// save and close that active session
			\session_write_close();
		}
	}

	// if the session to be destroyed has not been opened yet
	if (\session_id() == '') {
		// impersonate the session to be destroyed
		\session_id($id);
		// and open the session
		\session_start();
	}

	// unset the session variables
	$_SESSION = array();
	// destroy the session
	\session_destroy();
	// save and close the destroyed session
	\session_write_close();

	// if we have previously interrupted another session
	if ($pausedSessionId != '') {
		// assume that session again
		\session_id($pausedSessionId);
		// and open the session
		\session_start();
	}
}
```

Using those new resources, some new `logOutFromAllDevices` method would be possible as well.

**Comment by 32Blahs** [comment]
Hi ocram, delayed reply as following our other discussions I've completely rewritten your lib to meet my requirements (more accurately, I've used your core approach but rewritten all your code, including removing the dependency on your DB lib, so I can implement the extended features from before into the core). So our respective versions are drifting further apart, but this might help.

I was looking at something similar to this suggestion. I'm already retaining IP and session ids in the DB for login (and ip for reset requests etc), so this was easy to implement. However I found that hard killing the session from the admin interface (which I think is your approach in the example code) creates inconsistencies at the app level. For example, if a user has logged in and is performing multiple activities through Ajax, or has data in their session that would be elegantly saved/handled on logout, the code above would hard-kill the session in the middle of those activities. If the app layer is relying on a set of serial activities, or is storing data in the session, undefined behavior/inelegant exit will occur. Ie the same reason that you split the logout into 2 methods with session close separated.

What I think you actually want to do is, in isLoggedIn, have auth check for a flag that forces elegant session logout for the current user (as though the user clicked logout for example). 

In my case I have a DB flag which is checked through my isLoggedInHard method, which also addresses the change of rolemask (and activity permissions in my lib) for currently logged in user. I know you disagree with my approach, so maybe you can add a session field bool for force logout using the same approach above, then auth code can check for that flag and gracefully log the user out if it's set, with a call back to app level for the forced log out (so the app can determine what needs to be done/discarded). 

Because you don't do a hard login check or garbage collection on the remember table you'll need to clean those up too. The garbage collection relates to another point with your lib too - expired data (remember, reset etc) is stored forever, so app layer cannot gracefully handle expired info (random example: user logs in but doesn't formally log out, so contents of shopping basket should expire with session/remember expiry, but "last item viewed" should be retained into db for next user login).

Hope that's useful, and doesn't start another disagreement, haha!

**Comment by ocram** [comment]
Thanks for mentioning these concerns!

> However I found that hard killing the session from the admin interface (which I think is your approach in the example code) creates inconsistencies at the app level.

Not if you do it the right way in your application code. Remember that a session could expire at *any* time, in general, not just with these changes, so relying on the session being around for an indefinite time is never safe.

> For example, if a user has logged in and is performing multiple activities through Ajax, or has data in their session that would be elegantly saved/handled on logout, the code above would hard-kill the session in the middle of those activities. If the app layer is relying on a set of serial activities, or is storing data in the session, undefined behavior/inelegant exit will occur.

Right, these are some race conditions that wouldn’t normally occur due to session timeouts because sessions usually don’t time out while they’re being actively used. So that’s something to pay attention to, I agree. Nevertheless, if you use proper techniques in your application code, I don’t see any problems here. For example, use transactions with your database.

> What I think you actually want to do is, in isLoggedIn, have auth check for a flag that forces elegant session logout for the current user (as though the user clicked logout for example).

We could certainly do another database query on every single page request. But I’m pretty confident that the solution proposed above, which does *not* do these extra queries, is superior. And if you really didn’t want to kill sessions remotely, why not just *update* the session data, e.g. setting another flag or toggling the login state, instead of *destroying* that session? That way, you don’t need an extra database query per page request, either.

> In my case I have a DB flag which is checked through my isLoggedInHard method, which also addresses the change of rolemask (and activity permissions in my lib) for currently logged in user.

Likewise, you could handle this situation by *remotely* updating the bitmask in the session containing the roles.

> I know you disagree with my approach, so maybe you can add a session field bool for force logout using the same approach above, then auth code can check for that flag and gracefully log the user out if it's set, with a call back to app level for the forced log out (so the app can determine what needs to be done/discarded).

That seems close to what I’ve suggested above, right? But instead of setting another flag or session field, I proposed updating or toggling the existing fields that are already in use.

> or garbage collection on the remember table you'll need to clean those up too. The garbage collection relates to another point with your lib too - expired data (remember, reset etc) is stored forever

Yes, you’re right. Cleaning the expired data is something that we could handle as well, but I don’t think this is related to the current issue in any way and I don’t think it’s an urgent problem, either. Right now, if somebody really had too much expired data, they could simply clean it themself.

> Hope that's useful

It is, thank you!

**Comment by 32Blahs** [comment]
I think we're moving into a full on session management discussion now :-)

> Not if you do it the right way in your application code. Remember that a session could expire at any time, in general, not just with these changes, so relying on the session being around for an indefinite time is never safe.

Yes, but there's a difference between a session that's naturally expired because the user hasn't been back in _session-lifetime_, and a live session that you're hard-killing with this code whilst the user may be actively using it. The former can be killed without issue. Killing the latter in the way you're doing it (from an admin interface across another session) means the user could be right in the middle of doing something, then for no apparent reason - and with no warning to the app level - they're suddenly logged out and all their session data is lost (back to the phpauth session vars vs all session vars change discussed & fixed in your recent commits).

> That seems close to what I’ve suggested above, right? But instead of setting another flag or session field, I proposed updating or toggling the existing fields that are already in use.

It's close, but the subtle difference is this. As above, your method uses the context of the admin login to "remotely" kill sessions. My method - using a bool in the sessionvars - uses the context of the "current" user to elegantly log out etc.

Let's imagine the normal logout process saves some important session data into the db - the exact detail doesn't matter. In your case, the session data is simply lost and the user is dumped out back to the login screen with no warning or whatever - which is massively frustrating for UX.

In my suggestion (session related, in reality I use the DB as discussed which avoids all these challenges), PHPAuth isLoggedIn() checks for the bool, sees its set, so knows it has to force the current user to logout. PHPAuth then uses an app level callback for an elegant logout/data save/nice UX message to user explaining what's happened, the app does the pre-logout saving etc before PHPAuth finally logs out and (if needed) kills the session. 

(Yes, if the user never came back and the session naturally expired, the sessiondata would also be lost. But from a UX point of view users will accept "losing their shopping basket contents" if they don't come back for 30 days. They wouldn't accept filling their basket then "randomly" being logged out and losing everything they've done whilst they're actively using the site).

Now I accept you could replicate the data save piece into the destroySessionbyID(), so that when an admin forces a logout, destroySessionByID() is given the app level callback to elegantly save the data in each session. But this a) doesn't solve the UX point of dumping a user out of whatever they were doing, b) relies on more complex code to clean up other data not stored in the session/transactions etc, and c) leads to the next point/garbage collection.

Note that both approaches demand every "known" session is impersonated and affected through an iterator in PHP. Doing it via DB in the way I actually do it means that you've got one single SQL query to set the flag for every active session, then the individual user sessions pick that up as and when they load pages etc.

I.e.: the session approach means (N) db rows of session data have to be queried, loaded to PHP, iterated through, session impersonated, var changed etc. My DB approach avoids that completely, because state is checked in the individual user sessions on demand. If there's 10k rows in the DB session table but only 100 users actively using the site, the session approach touches 10k rows but my DB approach touches only the 100.

> Yes, you’re right. Cleaning the expired data is something that we could handle as well, but I don’t think this is related to the current issue in any way 

Imagine a case where you need to log out a subset of users (finance system, month end reconciliation, force logout for all except Role::Manager, Role::Finance etc). Assuming sessionids are stored in a table and not garbage collected (same model as rememberdata for example). Using your method, without garbage cleaning of expired sessions, code will have to work through a potentially massive table of every sessionid ever generated & stored, load them from DB to PHP, iterate through each, check validity and then decide if the user represented by the session should be logged out or not. (the only way to avoid that is to continually update the table that records the sessions, which is effectively the same /slower than using my DB isLoggedInHard() approach)

Using my method, with garbage collection, code will a) only have active sessions in the table to work through and b) only users who are actively using their session will be logged out through the session bool check. 

For the session bool approach, you could even have a mirror method that removes the bool from the sessionvar of active sessions. That would allow the admin to set the bool, force active users to logout/suspend session, take an admin action, unset the bool, and any user who wasn't logged in during the suspension period wouldn't even be impacted. Perfect for "site is offline for temporary maintenance" etc scenarios. Again, using my DB approach this functionality is for free without any additional code because the check is in the user context.


> Right now, if somebody really had too much expired data, they could simply clean it themself.

I guess this is where I get confused about your thought process for your lib. On the one hand you want to tightly control the PHPAuth lib, e.g.: you don't want to make methods protected for extends, the lib completely controls the entire session, you want to keep the schema tightly controlled etc. But on the other hand you suggest lib users to clean DB tables (by hand, by code, whatever), that sessions hard killed by the lib should somehow be handled by the app layer etc. Kind of feels to me like it needs to be one or the other - either the lib should provide all methods and all functionality to self-maintain, or the lib should provide a framework that can be extended as needed.

Anyway, not looking for an answer on that last point - as I said, I've rewritten all your code so doesn't apply to my case anymore.

**Comment by ocram** [comment]
I agree with you on most of these points. However, there are some important things to keep in mind.

The most important aspect you’ve been missing is the way in which the method proposed at the top will be used: Remember that the average user will not regularly encounter their session having been killed by someone else without notice. Instead, this method will mainly be used to allow users *themselves* to kill all sessions for their own account that may still be open on some devices. Alternatively, they might kill sessions for attackers that are trying to break into their accounts. And in the rare cases where admins will kill sessions, that will probably be for “rogue” users only. So in most cases, this should be fine from a UX perspective. I really see not a single problem here.

And, again, I would like to emphasize the importance of database transactions used properly in your application code. If the session ends within a series of activities, that won’t be a problem.

> Note that both approaches demand every "known" session is impersonated and affected through an iterator in PHP. Doing it via DB in the way I actually do it means that you've got one single SQL query to set the flag for every active session, then the individual user sessions pick that up as and when they load pages etc. I.e.: the session approach means (N) db rows of session data have to be queried, loaded to PHP, iterated through, session impersonated, var changed etc. My DB approach avoids that completely, because state is checked in the individual user sessions on demand. If there's 10k rows in the DB session table but only 100 users actively using the site, the session approach touches 10k rows but my DB approach touches only the 100.

Of course, you always have trade-offs. With the approach I suggested, we’ll have to make PHP impersonate a few sessions, which might in some cases be a large number. But with your approach, we would be making a lot more database queries, possibly on every page request.

> Imagine a case where you need to log out a subset of users (finance system, month end reconciliation, force logout for all except Role::Manager, Role::Finance etc).

There are better solutions to that problem, and a remote logout for all other users is not the most elegant solution here. Instead, you could easily implement some maintenance mode or a special mode that only allows certain roles to perform actions during some given time window.

> Assuming sessionids are stored in a table and not garbage collected (same model as rememberdata for example).

Remember, if you really need full control over sessions, PHP offers you all the tools you need to do so. You can change the session storage handler to save the session data wherever you like. And that happens transparently – you can still use this library as it is, without changing a single line of its code.

> I guess this is where I get confused about your thought process for your lib. On the one hand you want to tightly control the PHPAuth lib, e.g.: you don't want to make methods protected for extends, the lib completely controls the entire session, you want to keep the schema tightly controlled etc. But on the other hand you suggest lib users to clean DB tables (by hand, by code, whatever)

That may appear a little bit confusing, I agree, but it’s not really. The parts where this library should have its logic and schema enforced strictly are chosen for good reasons. Apart from that, what is important is the assumptions that you can rely on and those which you should rather not rely on. If there are database entries that have an “expires” timestamp that is in the past, it’s certainly safe to delete them yourself. That’s an assumption you can rely on. Nevertheless, that garbage collection is something that this library should probably do itself in the future, you’re right.

> that sessions hard killed by the lib should somehow be handled by the app layer etc.

That’s something different. It just means your application must have correct structure and implementations. If you rely on unsafe assumptions again, e.g. that your session will be around indefinitely, or at least a certain period of time if you’re currently still active, and that you can always save data persistently later on which are currently only stored in the session … well, that’s just something you should avoid in general.

**Comment by 32Blahs** [comment]
Let me prefix this entire response with one question:

How do you expect to manage and track session ids to userids?


>  So in most cases, this should be fine from a UX perspective. I really see not a single problem here.

Most cases (I believe it will be more than that, but that's an app layer question), but not all cases. Therefore there are definitely, let's say, "considerations".

> the importance of database transactions used properly in your application code.

Wrapping DB transactions is not going to solve this problem in an easy or straight forward manner. If a user is forcibly logged out (and I use the logout purely as an example, it could be anything else affected in the session that changes access rights for a period of time), the app layer will have zero warning of this. This then places the demand on the app layer to separate or duplicate DB commits & data management both inside "logged in status" code and "not logged in status" code, breaking separation of privilege. This is why I suggested a callback, so at least the lib notifies the app layer when it's taking some unilateral action.

> we’ll have to make PHP impersonate a few sessions, which might in some cases be a large number. But with your approach, we would be making a lot more database queries

Well no, you wouldn't be. With my approach, you make 1 query for 1 user only when that user is actively loading a page. To implement the overall suggestion, you need to store userid and session data for PHPAuth's usage. Lets say we do this in an additional table for now (see next point on this & your session manager comments). You also need to track if the session is still active, and maintain that record in the same table. Therefore on every page load, PHPAuth will need to update the userid:sessionid:expiry row, otherwise the expiry in the DB will drift out of alignment with the real session expiry.

Really with my approach we're talking about 1 query per page load here - hardly a heavy price in the context of any modern app.

> a special mode that only allows certain roles to perform actions during some given time window

Which, again, requires a check against the DB. If you don't garbage collect the sessions, and you don't update the expiry in <whatever mechanism you're using to match PHPAuth userid : session, see below > then you have 2 options. Either iterate through every single session in the table, find the sessionids where the rolemask matches whatever roles should be suspended, impersonate the sessions and edit the rolemask. Then do it all again to reverse it, regardless of whether or not the user is active and this needs to be done.

Or, my approach, the admin sets a single flag in the DB using my Activities approach (role::customer can_dostuff false). Then as users use the site, on each page load via the isLoggedInHard() method, reconfirm with the DB that the current user's roles are accurate and allow the user to continue doing whatever they're doing. If not, hit the app layer callback to notify an elegant save of data etc. Again - you get this functionality for free, and only the active users are touched.

This is the key of RBAC: apply the controls to the role (my way via Activities/rights map), not to the individual user (your way via editing individual session rolemask, data, etc).

> Remember, if you really need full control over sessions, PHP offers you all the tools you need to do so. You can change the session storage handler to save the session data wherever you like.

Yes, I know this, surprising though it may seem that I know things! However now we're back to the other discussion of where's the line of what is in or out of scope for PHPAuth. This line seems to shift to suit the situation, IMO, and you're conflating 2 things.

The discussion here which I'm trying to avoid is absolutely **not** about how PHP does session handling, or writing your own session handler (note the very first sentence in my previous reply). It's not even about having full control over sessions.

The discussion is about how PHPAuth as a library allows users and/or admins to manage, revoke, edit PHPAuth logins. Full stop. Global PHP session management is irrelevant to this.

It just so happens that internally within PHPAuth, the lib uses session data for individual login management. But, let's remember your lib is locked down and you don't want to allow extends etc, so for the purposes of the discussion we can consider PHPAuth a black box. PHPAuth could use small gnomes to print out and OCR scan back in the user data for all it matters - it's transparent and invisible to the app layer. 

In the black box, PHPAuth records session data that is relevant to itself. To implement any of these features we're discussing in this thread, PHPAuth must keep track of live sessions against userids.  As far as I know, short of writing your own session manager or some real nasty hacks using local filesystem, there is no core PHP way of simply getting all active sessions. Therefore session:userid must be stored somewhere.

That means we're left with possible choices:

1. PHPAuth includes a proper session management system, not using the DB schema, that works around these issues and solves your reluctance to do a single DB query per page load. This is implemented transparently, taking over all session management (back to how logout() kills the entire session), and extending PHPAuth's remit/purpose way beyond an auth system, which I assume you don't want to do and places much interference at the app layer/other libs that may be in use.

2. PHPAuth requires the user (app coder) of the lib to provide some smart way of managing sessions that doesn't rely on DB queries for PHPAuth session info, and PHPAuth is somehow allowed to use that method for the session management. But the only reason for this requirement is to deal with an internal process in the lib and places a dependency between app and lib, so that's not great.

3. PHPAuth uses the DB schema for all internal processes with your DB lib, including a table to store userid:sessionid map.


Unless I've missed something, 3 is clearly the most reasonable. 3 also requires the session info (expiry etc) to be tracked and updated. Therefore 3 also requires a query per page load, meaning that you've ended up exactly at my solution with the isLoggedInHard().


> If you rely on unsafe assumptions again, e.g. that your session will be around indefinitely, or at least a certain period of time if you’re currently still active, and that you can always save data persistently later on which are currently only stored in the session … well, that’s just something you should avoid in general.

Right, except it's not an unsafe assumption. The assumption is that session data is transient and only exists for the duration of the user's active-ness. If the user stops visiting the site, the data will be lost. I factor that in, because my design accepts that (example) the contents of a shopping basket will be lost if the user doesn't return within session-lifetime. My design also accepts that some important data that should never be lost must be saved in some persistent manner, because a session can die.

However because  PHPAuth can kill the session at any time, without warning, my assumptions are broken. I now have to save absolutely all data in some persistent manner - even data I don't really care about - for UX because PHPAuth could kill it without warning. I don't want to store basket contents in the DB, but I have to, because PHPAuth could really annoy my users by force killing their session whilst they're still browsing my site. And when they log back in - poof, all their items in their basket have disappeared. 

Now if PHPAuth used a callback on page load, in the context of the user session, to let me know that it's about to kill the data of the current user who is actively browsing the site, I have a chance of saving whatever needs to be saved and avoid really annoying my users. 

Anyway I think I've exhausted my explanation (and myself) of why you should consider my isLoggedInHard() query-per-page-load. Good luck, whatever approach you choose. I'll be interested to see what you do and if it is better than/different to my implementation!

**Comment by ocram** [comment]
> How do you expect to manage and track session ids to userids?

This is the critical question here, of course. Once we’ve got this working and have a proper mapping of the IDs, this feature is mostly done. It will then use some method to revoke a specified ID, something like the solution proposed at the top. For more information on the proposed implementation, please see further down.

> Most cases (I believe it will be more than that, but that's an app layer question), but not all cases. Therefore there are definitely, let's say, "considerations".

I really meant “most cases”, as in “almost every case”, because regular users will seldom find their own session revoked. Revocation will happen in two cases:

 * When a user revokes sessions from *their own* account. In this case, the other sessions from that account can only be the user themself (They won’t be surprised to find them discarded!) or malicious users attacking the account (We don’t care about their user experience!). So where are the major problems here?
 * In your own application, you may implement a feature that allows administrators to revoke sessions for arbitrary accounts. Well, I guess you won’t do this regularly and still worry about the user experience of those whose sessions you revoke.

> Wrapping DB transactions is not going to solve this problem in an easy or straight forward manner. If a user is forcibly logged out (and I use the logout purely as an example, it could be anything else affected in the session that changes access rights for a period of time), the app layer will have zero warning of this.

Does the app layer really need a warning? I still think you’re relying on unsafe assumptions here. If a user stops browsing your website “suddenly” at a given time, the session will expire just as well – likewise without any warning to your app layer. For everything else, i.e. sequences of operations in a single request, transactions within your app layer will work fine. Beyond that, I can’t really imagine any scenarios where there might be a problem, so concrete examples are welcome.

> Well no, you wouldn't be. With my approach, you make 1 query for 1 user only when that user is actively loading a page.

Yes, as I said, a lot more requests: at least one per HTTP request.

> Therefore on every page load, PHPAuth will need to update the userid:sessionid:expiry row, otherwise the expiry in the DB will drift out of alignment with the real session expiry.

See above. For a potential mitigation of that extra load, please see further below.

> Really with my approach we're talking about 1 query per page load here - hardly a heavy price in the context of any modern app.

This *is* a heavy price, because users expect this library to be careful with resources and right now, this library often uses not a single query for several consecutive page loads or HTTP requests. If we’re okay with one extra query per page load, the implementation here is trivial.

> Which, again, requires a check against the DB.

Not necessarily. It’s entirely up to you how you implement this. You could also use flags in your code or in environment variables. That implementation is not a problem this library should care about.

> If you don't garbage collect the sessions, and you don't update the expiry in <whatever mechanism you're using to match PHPAuth userid : session, see below >

Of course, we *do* have to track expiry times and garbage collection. This is obvious. Otherwise, the garbage would pile up pretty quickly and we would have to do much extra work that is useless (operating on expired sessions).

> This is the key of RBAC: apply the controls to the role (my way via Activities/rights map), not to the individual user (your way via editing individual session rolemask, data, etc).

This is obviously out of scope for this thread here. But there are multiple perspectives on that and the README explains why this library has opted for the most basic and easiest-to-implement approach.

> so for the purposes of the discussion we can consider PHPAuth a black box

Correct. A black box with a well-defined API that covers most of what most people may ever need.

> To implement any of these features we're discussing in this thread, PHPAuth must keep track of live sessions against userids. As far as I know, short of writing your own session manager or some real nasty hacks using local filesystem, there is no core PHP way of simply getting all active sessions. Therefore session:userid must be stored somewhere.

Right. Finally, let’s move on to discuss the actual implementation that we may choose. Please see further down.

> PHPAuth uses the DB schema for all internal processes with your DB lib, including a table to store userid:sessionid map.

Yes, that’s what we do.

> Unless I've missed something, 3 is clearly the most reasonable.

Agreed.

> If the user stops visiting the site, the data will be lost. I factor that in, because my design accepts that (example) the contents of a shopping basket will be lost if the user doesn't return within session-lifetime. My design also accepts that some important data that should never be lost must be saved in some persistent manner, because a session can die.

Perfect! That’s what I was talking about.

> However because PHPAuth can kill the session at any time, without warning, my assumptions are broken.

No. Please see above for why this does not break your assumptions. The library will rarely kill sessions for regular users without the user themself initiating that process.

> I don't want to store basket contents in the DB, but I have to, because PHPAuth could really annoy my users by force killing their session whilst they're still browsing my site.

Why should this library do that? There won’t be a lottery where the “winner” is randomly kicked out of their session.

Finally turning to the possible implementation of how users are mapped to sessions:

 * In the two methods `UserManager#onLoginSuccessful` and `Auth#logOut`, we will always update our session list so that it reflects the latest state of the user’s session, i.e. a record will either be created (potentially just updated) or deleted.
 * The session information will be stored in a new database table with the following schema:

   ```sql
   CREATE TABLE users_sessions (
       user_id int(10) unsigned NOT NULL,
       session_id varchar(256) CHARACTER SET latin1 NOT NULL,
       user_agent varchar(512) DEFAULT NULL,
       ip_address varchar(45) DEFAULT NULL,
       expires_at int(10) unsigned NOT NULL,
       PRIMARY KEY (`user_id`,`session_id`)
   ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
   ```

As a result, we’ll have a database table that we can query for all session IDs associated with a specific user. If not disabled for privacy reasons, the user-agent string and the IP address will also be stored as they can serve to describe the origin of the session.

The `expires_at` column in the database schema, though, is the critical piece of information here. If we want to know when a session will expire, the expected expiry time cannot be known after just the login. That is not enough. It must be updated regularly, perhaps on every request. But even then, we can’t be sure that a session has expired. Sessions in PHP are subject to garbage collection and only discarded with a certain probability within a certain time frame. This depends on the following configuration directives, at least:

```
session.gc_maxlifetime
session.gc_probability
session.gc_divisor
```

If even an update on every request does not yield data that we can safely rely on, why incur an additional database operation on every request? We could do this less often, as in:

```php
$intervalBetweenUpdates = (int) \ini_get('session.gc_maxlifetime') * 0.05;
$_SESSION['auth_session_updated_at'] = isset($_SESSION['auth_session_updated_at']) ? $_SESSION['auth_session_updated_at'] : 0;
$nextUpdateTime = $_SESSION['auth_session_updated_at'] + $intervalBetweenUpdates;

if ($nextUpdateTime < \time()) {
    // update the database with information about the current session

    $_SESSION['auth_session_updated_at'] = \time();
}
```

But after all that, we can’t safely delete a session from our internal list because it may not actually have expired, due to how PHP handles this. The session may be alive again (or still). Sure, it will probably be re-created on one of the next requests. But that may not be enough.

One way to be sure about the expiry time of *any* session would be to enforce a strict life time of each session in the library’s code. If we knew (and enforced) that a session could never live longer than 24 hours after being created (during login), we could simply discard sessions older than that. But that may not be desired. It could even cause sessions to expire while a user is active.

**Comment by 32Blahs** [comment]
> Does the app layer really need a warning? I still think you’re relying on unsafe assumptions here. If a user stops browsing your website “suddenly” at a given time, the session will expire just as well – likewise without any warning to your app layer. For everything else, i.e. sequences of operations in a single request, transactions within your app layer will work fine. Beyond that, I can’t really imagine any scenarios where there might be a problem, so concrete examples are welcome.

I've mentioned several times that "forced logout" is only an example. Anything that changes the attributes of the user is in scope. There is a huge difference between a logged in user stopping browsing the site and the session expiring naturally, and - FOR EXAMPLE - a change to the permissions granted to that user. 

The former is just a change in user state. The latter is a change in "what the user is allowed to access". Those change in permissions may now mean the user is not allowed access to code, using the Permissions model you've described in the readme, that they were previously accessing. There are many examples where transactions aren't relevant at the app layer, such as any app level workflow. 

If I'm wrong, then why bother - FOR EXAMPLE - providing a logout method at all? Just let the sessions expire naturally and garbage collect them. But no login system ever will do that, because that makes no sense. 

> This is a heavy price, because users expect this library to be careful with resources and right now, this library often uses not a single query for several consecutive page loads or HTTP requests. If we’re okay with one extra query per page load, the implementation here is trivial.

I just compared microtime of isLoggedIn and isLoggedInHard. There is a 0.5 millisecond difference between the two methods. 

To save 0.5 milliseconds, you're relying on sessions to control user state rather than the authoritative check in the database, you're creating a convoluted solution with session recording and impersonation which isn't fully reliable due to the reasons you've explained, and we haven't even seen the solution for garbage collection yet. 

I admire the intent of keeping your library light and careful, but this is taking things to the extreme. Looking at the bigger picture where this lib will be simply one component of an app, a half millisecond difference is irrelevant. And for the cost of 0.5 milliseconds you gain huge benefit over the control and security of the system.

> But there are multiple perspectives on that and the README explains why this library has opted for the most basic and easiest-to-implement approach.

Well there's only really one perspective, especially for anyone who has dealt with non-trivial size IDAM directories. Using RBAC works, and applying rights to individual users is a path to chaos. That said, if your choice is to not use RBAC then nobody can disagree with it. It's your library to do as you wish.

> Why should this library do that?

Because that's exactly how you're proposing the implementation should be done. Scenario: administrator changes something (e.g. a role), now all sessions for relevant users must obey that change.

In your proposal, the admin context impersonates every relevant user session and hard changes the appropriate values. Within the user session, there is no warning of this. It just happens. Code that the user had permission to access is suddenly inaccessible.

In my proposal, following the hard check against the DB on each page load, the user context can see the session vars no longer match the DB row. An app layer callback is called to gracefully deal with the change - data can be saved, a message can be shown, whatever. 

> Finally turning to the possible implementation of how users are mapped to sessions:

Seems like a reasonable solution which is exactly the same as mine - it's a DB check, but you're doing it at intervals rather than on page load. If you provide a new method for it, then you have exactly my approach.

Note, remember that my approach allows the use of both isLoggedIn and isLoggedInHard as and when the app layer wants to do it. In my app layer, I just happen to use isLoggedInHard on every page load because I want to - for all the reasons explained repeatedly.

As we know, sessions are "unreliable", which simply underlines the need for "regular" hard checks against the DB.

> In the two methods UserManager#onLoginSuccessful and Auth#logOut, we will always update our session list so that it reflects the latest state of the user’s session, i.e. a record will either be created (potentially just updated) or deleted

Nope, this can't be trusted to reflect latest state. As you've said yourself, sessions can expire whenever. Auth#logOut may never be called. Again, the benefit of doing it on every page load is that it can be trusted.

Finally, this will be my last post as I don't see that we're really adding anything here, other than repeatedly underlining a massive difference of opinion and going round in circles (for example, you've previously said not to use the DB for session management, but now you're doing exactly that).

Our codebases and approaches are completely different and there's no reason for me to contribute further, I only got involved to try and offer input and a new perspective. Feel free to not bother replying as I won't be returning. Cheers.

**Comment by ocram** [comment]
Thank you!

> for example, you've previously said not to use the DB for session management, but now you're doing exactly that

Sorry, that’s just plain wrong. The very first sentence in this thread’s first post has always been (for several months now) the following:

> Whenever a user signs in, we could add the session ID, together with the ID of the user who has just logged in, to the database (into some new table that will be created for that purpose).

The only new thing is the proposed schema.

> Well there's only really one perspective, especially for anyone who has dealt with non-trivial size IDAM directories. Using RBAC works, and applying rights to individual users is a path to chaos. That said, if your choice is to not use RBAC then nobody can disagree with it.

I don’t agree. There *are* multiple perspectives. And the approach this library has chosen is the easiest for simple and medium-sized projects. Anybody who needs more can implement this on top, but that would not be possible the other way round.

Again turning to the actual issue at hand, I could imagine one alternative solution that is much closer to what you want:

In the constructor of the `Auth` class, we could add a fourth parameter named `$sessionSyncInterval` or something like that. It would be optional, the default value being `null` and disabling the behavior. Otherwise, one could specify an interval in seconds after which the library queries the database again for updated user data, right in the constructor, at the very beginning of a request, before the instance has been used in any way.

Setting it to `0` would mean that a query is made on every request, for those that need this. Choosing a value such as `60` would mean that updated roles, killed sessions, etc. would be reflected no later than 60 seconds after the change has been made, but not requiring an extra query on every request.

That would probably also be the easiest solution. We would only need one place in the database to store a flag or directive that tells the library to kill certain (or all) sessions for a user.

**Comment by ocram** [comment]
Superseded by https://github.com/delight-im/PHP-Auth/issues/67
