### ISSUE TITLE
Login as user

### ISSUE THREAD

**Issue by ponasromas** [delight-im/PHP-Auth#53]
Recently I faced a need to implement "login as user" function. Any ideas how to do this on top of PHP-Auth?

**Comment by ocram** [comment]
Thank you very much!

You want to impersonate another user for administrative purposes, right? For example, you want to log in as one of your customers to help with a problem they have with their account. Is that correct?

If so, that's still a missing feature, I have to admit. Sorry!

We should definitely add this soon.

**Comment by ponasromas** [comment]
Yes, for admin purposes. Eagerly waiting for such fantastic feature!

**Comment by ponasromas** [comment]
Hey @ocram I see library updated to 2.2. Is there any ETA for "Login as client..." feature?

**Comment by ocram** [comment]
It’s there, finally! It comes in three different variants, one for each identifier that is supported for selecting users as an administrator, i.e. user ID, username and email address.

Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/47d1e303aaead8670c8fd79210281d0021e76a77
 * https://github.com/delight-im/PHP-Auth/commit/382ee5bf93b5c1c00bab0e322aaf52ba9d84fd0b
 * https://github.com/delight-im/PHP-Auth/commit/aec738a9dbad059684cd7c6eca2932935b7743a0

@ponasromas The latest major version of this library is `v7.x.x`, and that’s where this feature is in as well. So in order to use this feature, you may have to upgrade to that major version before. For a guide on how to do that, please see the migration notes in `Migration.md`.

**Comment by acodispo** [comment]
@ocram Some questions about this feature! Once impersonating a user, how do you get out (i.e. switch back to the admin user)? If impersonating, may I then change the email address of the impersonated user using the usual method?

**Comment by ocram** [comment]
@acodispo There is currently no direct way to get back to the admin account after impersonating another user. Sorry! The way this feature is implemented has been the most straightforward and basic solution that does what it advertises. More complex use cases and sequences of tasks have not been considered. So the only way to get back to the admin account is, for now, to simply log out from the impersonated account and log back in as the admin user or go to the section of your service where you make the admin interface available. Once impersonated, you can do *anything* that the user can do. Actually, this is just a normal session, you simply circumvent authentication so that you don’t have to know the user’s password as an admin. So you could certainly change the user’s email address which will trigger the normal confirmation email (if configured).

**Comment by acodispo** [comment]
@ocram Thanks, that answers my question!
