### ISSUE TITLE
problem in using PDO and calling from CLI.

### ISSUE THREAD

**Issue by tolgaulas** [delight-im/PHP-Auth#54]
Auth.php line 53 has issue if the app is called from CLI and passes $db only as ref. Perhaps,  is_null($ipaddress) may be usefull before assignement. 

		if (is_null($ipAddress)) {
			$this->ipAddress = $ipAddress;
		}else{
			$this->ipAddress = empty($ipAddress) ? $_SERVER['REMOTE_ADDR'] : $ipAddress;
		}

**Comment by ocram** [comment]
Thank you!

First, curious to hear what your use case is for calling this library in a CLI application. Actually, this library has only been designed for use with a web server, not for use on the CLI. So that's why this hasn't been tested and there may be some bugs like this one.

Second, why do you think it's related to `$db` in any way? As far as I can see, that variable is neither in the code that you quoted nor in the error message.

The specific line in question is: https://github.com/delight-im/PHP-Auth/blob/f142dd91dc29da9a1574b41e3dc328531b4f8f39/src/Auth.php#L53

The issue that you're experiencing is probably the following:

```
PHP Notice: Undefined index: REMOTE_ADDR in Auth.php on line 53
```

That is because `$_SERVER['REMOTE_ADDR']` just isn't available on the CLI. We can't do anything about that. We could only set `$this->ipAddress` to `null` and prevent that notice, I guess. Don't know if that's reasonable, though. Maybe this library simply shouldn't be used in applications on the CLI.

**Comment by tolgaulas** [comment]
You're right on the low/no use of it for CLI; it's a web lib. However, it was giving headaches on the dev phase, we test it some features on CLI, which is faster. How ever, we modded line 53 of  auth.php per my initial code segment in the first post, it solved the case, just fyi.

**Comment by ocram** [comment]
I see, thanks. It can't hurt to make this notice go away, even if CLI usage is a pretty rare use case.

Implemented in https://github.com/delight-im/PHP-Auth/commit/6162092618e28f4e6f0af2f015c9dd7fa8b2d0b1.

Thank you!
