### ISSUE TITLE
too many requests 

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#58]
A few questions about this exception.

1. How many is "too many"?
2. Is there a way to tweak that number?

Thanks!

**Comment by ocram** [comment]
Thanks, good question!

There is currently no documentation on this topic because it's something where the details should be hidden from the developer using this library and you just shouldn't have to care about the internals here.

> How many is "too many"?

That depends. This is specific to the feature being used. As said before, you *shouldn't* have to care. But if you're really interested in the details or if there's some problem you have to debug or find out about, just search the source code for calls to the `throttle` method, as in this example: https://github.com/delight-im/PHP-Auth/blob/61041cc6fd3c973c818ed148b20e20e9862f863d/src/Auth.php#L160

The example above describes that the resource specified by the array in the first parameter will be limited to, on average, `1` request per interval of `60 * 60` seconds (1 hour), allowing temporary bursts of up to `75`-fold size.

This is how "too many" is determined throughout most parts of the code. The key to understanding these calls is the signature and the documentation of the `throttle` method: https://github.com/delight-im/PHP-Auth/blob/61041cc6fd3c973c818ed148b20e20e9862f863d/src/Auth.php#L1610-L1623

In some rare cases, the limit is determined another way, like this: https://github.com/delight-im/PHP-Auth/blob/61041cc6fd3c973c818ed148b20e20e9862f863d/src/Auth.php#L864-L866

So in order to find *all* occurrences, you should just search for places where an instance of `TooManyRequestsException` is created and thrown.

> Is there a way to tweak that number?

Not at the moment. While I understand the wish to configure the rate limits, quotas and throttling behavior of your authentication component, more options is not always the right answer. If those limits were something that affects regular users in everyday usage, the lack of configuration would definitely be a flaw in this library. But this is not what it is. Instead, only "attackers" and "hostile" or "malicious" users should usually be affected by this. If someone tried to enumerate all the email addresses registered at your service or crack passwords using brute force, they should see the exception and its implications. Not your regular users.

I'm sure there are reasonable limits that *everybody* can live with, making an additional configuration superfluous here, unless you're building some legacy banking website that only allows 4-digit numeric PINs, which would require very harsh limits.

If you feel that some limits are poorly defined or wrong, let's talk about these specific cases and fix it so that they work properly for everybody.

**Comment by acodispo** [comment]
I'm currently trying to implement the `resendConfirmationForEmail` feature. I'm having trouble testing it, because it seems to throw TooManyRequests every time. I'm only submitting the request once. Any ideas here I might be going wrong? I'll try to put together a general test & duplicate my problem in a generic setup (rather than embedded as it is in my app).

**Comment by ocram** [comment]
> I'm currently trying to implement the `resendConfirmationForEmail` feature. I'm having trouble testing it, because it seems to throw TooManyRequests every time.

This is completely expected, I’m afraid, but apparently not documented at all. Sorry for the confusion and the trouble!

> I'm only submitting the request once.

I guess you’re submitting the “resend” request only once, but the actual confirmation request is thus submitted *twice*, isn’t it?

> I'll try to put together a general test & duplicate my problem in a generic setup (rather than embedded as it is in my app).

You don’t have to do that, as far as I can see!

So the lifetime of such a confirmation request is defined here: https://github.com/delight-im/PHP-Auth/blob/9637dfa60d5518c9ec4147db62a5292faff30b91/src/UserManager.php#L41

And unless 25% or more of that lifetime has already passed, the attempt to resend the request is declined: https://github.com/delight-im/PHP-Auth/blob/9637dfa60d5518c9ec4147db62a5292faff30b91/src/Auth.php#L842

That is because users shouldn’t (and have no reason to) request a new confirmation when they haven’t given the original one at least *some* time to arrive.

Do you think we should give one request for a new confirmation “for free”, i.e. enforce that limit only for the third request in a row, for users’ peace of mind as they can at least “do something” and not feel helpless?

The feature throttles against other attributes and indicators as well, but I don’t think these are kicking in here.

**Comment by acodispo** [comment]
@ocram Thanks for your help! I get it now. I don't have a strong opinion on allowing the one "free" request as you suggest. I could see either way. My only concern is being able to test the circumstance of a resend, without having to wait 18 hours before I do so. I should be able to change either of the lines you cited above temporarily to get a good testing value, yes?

Thanks again!

**Comment by acodispo** [comment]
I was able to set `$retryAt = 1` to escape the throttling for testing purposes. :-)

**Comment by ocram** [comment]
> I don't have a strong opinion on allowing the one "free" request as you suggest. I could see either way.

That’s fine. I have changed the code, which also became a bit simpler this way, so that one attempt to re-send the confirmation is always possible: https://github.com/delight-im/PHP-Auth/commit/0a97f6751510bec29206f8f1fc8afcf119dcbdf0

> My only concern is being able to test the circumstance of a resend, without having to wait 18 hours before I do so.

Sure, that’s definitely a problem. Thanks for bringing this to our attention!

> I should be able to change either of the lines you cited above temporarily to get a good testing value, yes?

Yes, both would work. Alternatively, you could even clear the `users_throttling` table in the database if you didn’t want to touch the code of the library.

> I was able to set `$retryAt = 1` to escape the throttling for testing purposes. :-)

Glad that this worked and it didn’t complicate development any further. Sorry for that!

Of course, all this should never have been necessary, so that’s why there’s now an option (as the fourth parameter of the constructor) to disable throttling (e.g. during development): https://github.com/delight-im/PHP-Auth/commit/09247e7203da075093aaedcc8d4303eafd416dda

Thank you!

**Comment by acodispo** [comment]
All that is great, thanks! And thanks again for your help & your work on this library.

**Comment by ocram** [comment]
No problem, thanks for your appreciation and support!

**Comment by roddyguy22** [comment]
>>>The example above describes that the resource specified by the array in the first parameter will be limited to, on average, 1 request per interval of 60 * 60 seconds (1 hour), allowing temporary bursts of up to 75-fold size.

Could someone please explain what a "temporary burst" means?

**Comment by ocram** [comment]
Sure. This was a reference to short periods of time with spikes in activity.

**Example:**

You personally need about 1.5 requests every day to access password-protected X. So you set up your throttling to allow 2 requests per day, which is sufficient.

But sometimes, you don’t seem to remember your password for X, so you have to try a few variants, and you need about 9.2 requests in those situations on average.

Now with the 2 requests per day, you would not be able to try all these variants. You would have to wait a day after every second request.

So that’s why we use a “burst” or “spike” factor of, say, 6. This allows for up to 6x the usual activity, while still not giving you 12 requests *every day*.
