### ISSUE TITLE
Manually reset expired email confirmation

### ISSUE THREAD

**Issue by crecent77** [delight-im/PHP-Auth#59]
Can I manually reset an expired email confirmation link by changing the date in the "expires" field in the "users_confirmations" table?  We are in the process of updating to the latest release so we can resend the confirmation link, but until we get that update done can I just change the date as noted above?

**Comment by ocram** [comment]
Thanks for your question!

> Can I manually reset an expired email confirmation link by changing the date in the "expires" field in the "users_confirmations" table?

If the user just waited too long or received the link too late, and the token has thus expired: Sure, go ahead and update the `expires` field as you like. That will work.

But if the user never received the link, e.g. because there was some problem with email delivery, changing the expiration time will obviously not be sufficient. This is one of the cases where the new features from the latest major version come into play, which allow you to re-send the email and work around delivery problems that way.

Does that help?

> We are in the process of updating to the latest release so we can resend the confirmation link, but until we get that update done can I just change the date as noted above?

Sure, I understand. And there may be other components and tasks that you need to address in your update, but judging from this library alone, the migration should really be easy, and mainly consist of simple changes to the database schema.

**Comment by crecent77** [comment]
Thanks you very much.  That is perfect for a quick workaround. We are in the final testing for rolling in the update to resend the emails and that will be helpful too.
