### ISSUE TITLE
Ensure account is verified before initiating password reset

### ISSUE THREAD

**Issue by lancehornback** [delight-im/PHP-Auth#6]
I have an app that requires admin-approval of user accounts. The email verification already built into PHP-Auth works great for this (verification links sent to admins instead of users).

This brings up the use case where a user may register, then attempt to reset their password prior to the account being verified (could also occur for user email verification as well, although perhaps less often). I modified `Auth::forgotPassword` as follows to check if the account is verified before initiating the password reset process:
```php
public function forgotPassword($email, callable $callback, $requestExpiresAfter = null, $maxOpenRequests = null) {
		$email = self::validateEmailAddress($email);

		if ($requestExpiresAfter === null) {
			// use six hours as the default
			$requestExpiresAfter = 60 * 60 * 6;
		}
		else {
			$requestExpiresAfter = (int) $requestExpiresAfter;
		}

		if ($maxOpenRequests === null) {
			// use two requests per user as the default
			$maxOpenRequests = 2;
		}
		else {
			$maxOpenRequests = (int) $maxOpenRequests;
		}

		// Ensure account is verified before initiating password reset
		try {
			$userData = $this->db->selectRow(
				'SELECT id, verified FROM users WHERE email = ?',
				[ $email ]
			);
		}
		catch (Error $e) {
			throw new DatabaseError();
		}

		if ($userData['verified'] !== 1) {
			throw new EmailNotVerifiedException();
		}

		$userId =  $userData["id"];
		// $userId = $this->getUserIdByEmailAddress($email); // no longer needed
		$openRequests = (int) $this->getOpenPasswordResetRequests($userId);

		if ($openRequests < $maxOpenRequests) {
			$this->createPasswordResetRequest($userId, $requestExpiresAfter, $callback);
		}
		else {
			self::onTooManyRequests($requestExpiresAfter);
		}
	}
```
And made sure to catch the new error in the `$auth->forgotPassword` handler:
```php
try {
	$auth->forgotPassword($_POST['email'], function ($selector, $token) {
			// send `$selector` and `$token` to the user (e.g. via email)
	});

	// request has been generated
}
catch (\Delight\Auth\InvalidEmailException $e) {
	// invalid email address
}
catch (\Delight\Auth\TooManyRequestsException $e) {
	// too many requests
}
catch (\Delight\Auth\EmailNotVerifiedException $e) {
	// email not verified
}
```
Would be happy to create a pull request if it'll help, or if there's a more optimal solution would be great to hear that too. Thank you very much for an excellent, lightweight, well-documented library!

**Comment by ocram** [comment]
Thanks a lot!

This has been very helpful. The case that you describe had undocumented behavior so far, which is not good. It didn't allow the user to do anything (except for changing the password again after sign up, where they initially set it up themselves). But fixing this and introducing documented behavior is a good idea.

> I have an app that requires admin-approval of user accounts. The email verification already built into PHP-Auth works great for this (verification links sent to admins instead of users).

That's great, a perfectly valid use case :) You could even send (different) confirmation emails to *both*, the user and the admin. That's why this library does not send (or at least prepare) emails itself but only produces a selector/token pair. This may seem annoying to some, but it allows for maximum flexibility.

> This brings up the use case where a user may register, then attempt to reset their password prior to the account being verified (could also occur for user email verification as well, although perhaps less often).

With email verification, users could trigger a password reset email even if they haven't verified their ownership of the email address yet. It's really an issue in both use cases.

> Would be happy to create a pull request if it'll help or if there's a more optimal solution would be great to hear that too

The idea and the places that had to be modified were all correct. I just refactored the method `getUserIdByEmailAddress` (which you dropped) to a more generic `getUserDataByEmailAddress`, since that method wasn't used anywhere else, anyway. That has been done here: https://github.com/delight-im/PHP-Auth/commit/6be456a27ad8a41198b5180237f77c6d2fc79d86

This way, we have automatic handling of the situation where the account does not exist at all (throwing `InvalidEmailException`) again, a shorter `forgotPassword` method, and re-usability of `getUserDataByEmailAddress` in the future.

With that being done, the actual fix becomes as simple as this: https://github.com/delight-im/PHP-Auth/commit/6bfa29883613bd0cf93b9a269dec7970e6105233

> Thank you very much for an excellent, lightweight, well-documented library!

Thanks for your appreciation, and for this equally excellent and well-documented patch :)

You may update your dependency using Composer now in order to get the updated version of this library.

**Comment by lancehornback** [comment]
Great - thank you very much for taking the time to explain everything so thoroughly!
