### ISSUE TITLE
Working Example of Implementation

### ISSUE THREAD

**Issue by clstudio** [delight-im/PHP-Auth#60]
Hi, thank you. This system looks promising but it completely lacks a demonstration. Can you show me a working example somewhere?

**Comment by ocram** [comment]
Thank you!

> but it completely lacks a demonstration

No, it doesn't. There is one, but given the detailed documentation and the clear interface, a demonstration shouldn't even be necessary. The methods clearly describe what they do, and the result is known from elsewhere on the web.

> Can you show me a working example somewhere?

Sure, the manual tests in `tests/index.php` serve as a demonstration. Just place the project's source code on a web server and point your web browser to that `index.php` file. There should be a demonstration for every major feature.

Does that help?

**Comment by clstudio** [comment]
Allright, thanks. IMHO this project would still benefit from a quick visual example but that's just the constructive opinion from a guy who can't briefly imagine how to implement what's in the docs into a real world application 😃

**Comment by ocram** [comment]
Thanks, we definitely appreciate your feedback on this matter here. It's just that this would be some additional (albeit small) maintenance overhead for something we didn't see any value in so far, because we didn't know it would be something people needed. I really hope that the demonstration included in the `tests/` directory can be of use to you.
