### ISSUE TITLE
[NFR] Getter & setter for \Delight\Db\PdoDatabase::$attributes.

### ISSUE THREAD

**Issue by temuri416** [delight-im/PHP-Auth#7]
Hi,

Thanks for a nice auth library.

I need an ability to modify PDO attributes - MySQL does not support `PDO::ATTR_STRINGIFY_FETCHES`.

Please implement:

In `\Delight\Db\PdoDatabase`:

```php
/**
 * Set single PDO attribute.
 *
 * @param integer $key PDO attribute
 * @param integer $val PDO attribute value
 * @return $this
 */
public function setAttribute($key, $val)
{
    $this->attributes[$key] = $val;
    return $this;
}

/**
 * Set PDO attributes array.
 *
 * @param array $val PDO attributes in key/value format.
 * @return $this
 */
public function setAttributes(array $val = null)
{
    $this->attributes = $val;
    return $this;
}

/**
 * Get PDO attribute value.
 *
 * @param integer $key PDO attribute
 * @return mixed
 */
public function getAttribute($key)
{
    if (isset($this->attributes[$key])) {
        return $this->attributes[$key];
    }
}
/**
 * Get all PDO attributes.
 *
 * @return array|null
 */
public function getAttributes()
{
    return $this->attributes;
}

```

In `Delight\Auth\Auth`:

```php
/**
 * @return PdoDatabase
 */
public function getDb()
{
    return $this->db;
}
```

Thanks!

**Comment by ocram** [comment]
Thanks for your feedback!

Let's first talk about the problems that you're experiencing with this library.

> MySQL does not support `PDO::ATTR_STRINGIFY_FETCHES`

What does that mean? Do you get errors? Do results from the MySQL database come in the wrong format or data type? Can you make sure you're using the MySQL Native Driver (`mysqlnd`)?

This library does not encapsulate the database instance for no reason. We can't just get the backing database instance and modify it in any way we want. That's because this library needs to make certain assumptions.

When it queries the `verified` property of a user, for example, it expects an `int` result and not a `string` result. Only because we can make these assumptions, we can use strict comparisons (`===`) in code. There are other aspects that are even more dramatic, e.g. the result structure (array vs object).

**Comment by temuri416** [comment]
Hi,

I am getting PDO exception trying to set ATTR_STRINGIFY_FETCHES parameter. I may or may not use `mysqlnd`, and to give me that ability I'd expect the library to be flexible.

Thanks.

**Comment by ocram** [comment]
No, the library cannot do this for the reasons explained above. Sorry!

The `mysqlnd` driver has been available since PHP 5.3 and is a requirement for this library.

This is what the [PHP documentation](http://php.net/manual/de/mysqlinfo.library.choosing.php) says about the driver:

> using the built-in mysqlnd library is highly recommended

And [somewhere else](http://php.net/manual/de/ref.pdo-mysql.php):

> As of PHP 5.4, mysqlnd is the default library.

**Comment by temuri416** [comment]
It does not really matter to me. What I am trying to tell you is that by not insisting on === OR by casting strings as integers you can make your library work in the environments where `mysqlnd` is not used. That's all.

**Comment by ocram** [comment]
> you can make your library work in the environments where `mysqlnd` is not used

There shouldn't be any reason left for such environments to exist. The modern driver is both available to everyone and the default in all recent PHP versions.

> That's all.

No problem, I absolutely appreciate your feedback! And I'm sure some others will have the same problem as well and find this issue helpful.

**Comment by ocram** [comment]
See also https://github.com/delight-im/PHP-Auth/issues/18
