### ISSUE TITLE
Check auth state on client side

### ISSUE THREAD

**Issue by qawsqs** [delight-im/PHP-Auth#70]
I'm making a SPA and want to redirect user to index or login route depending on auth state.

How can I check in browser whether user is logged in?
I've tried to watch if `\session_name()` cookie is present, but the problem is, this cookie is created even if user tried to log in, but failed (due to wrong password, etc.)

Thank you.

**Comment by ocram** [comment]
The problem and the solution here are *not* related to this specific library but are a result of the fundamental properties of client-server communication and whom you can trust.

You can never trust the client when it comes to authentication, authorization, or security in general. That’s why we only store a session ID on the client – and all other information (e.g. whether the user is currently signed in or not) is only stored on the server.

That means you have to query the server whenever you want to know that. An AJAX/XHR request would probably be what you need here.

If you don’t care about security and trust, because all you want to do is enhance the UI, you can just duplicate the authentication state in JavaScript on the client if you want. You could do that whenever the state changes, for example, like on successful logins or on logouts. That gives you the same power (without security) that you would have if this library stored all authentication information on the client directly.
