### ISSUE TITLE
Not an issue, just a question regarding cookie stealing

### ISSUE THREAD

**Issue by ovisopa** [delight-im/PHP-Auth#72]
Hope it's ok to ask here, as this is not an actual issue, just that I'm not quite sure, if it's possible, if someone steals the cookie, after I was successfully logged in, would they be able to login (if they already have the selector and token) ?

Thank you.

**Comment by duurland** [comment]
Hey. I just stumbled across this library and am also curious how it handles cookie/session stealing.

I tried exporting both my session + rememberme cookie one at the time and successfully authed through another browser.

Is there a way to bind the cookies to the visitors user agent / IP?
Is there any callbacks so we can extend the auth logics with custom functions?

**Comment by ovisopa** [comment]
I don't think binding to IP is a good idea, if you click REMEMBER ME on  your mobile phone, while away, you will have one IP, when moving from place to place or when connecting to a wifi you will have a different IP.

**Comment by ocram** [comment]
Thanks for your question!

This is just the very nature of cookies. They may contain sensitive information, which must be protected – and which usually *is* well-protected. Chrome, for example, may additionally *encrypt* the cookies stored locally on your device.

So this is more or less a contrived scenario. In practice, you *shouldn’t* be able to intercept or steal anybody’s cookies. That’s really one of the fundamental assumptions that you make. If you could steal the cookies, that would already be a serious vulnerability. You could steal any other files from the victim’s device as well, couldn’t you? Browsers, websites and users *rely* on the fact that this is *not* easily possible.

Again, it would either require you to be able to intercept the victim’s communications – this is why we have SSL/TLS – or it would require you to steal the cookies directly from their device – which requires some other vulnerability for file system access. In any case, you need to compromise the victim’s device or session in some way in order to get the sensitive information that is stored in the cookie.

The same scenario does apply to millions of other websites. One could even say it applies to virtually *any* website. Cookies store sensitive information and there’s no way around this because the client must be able to read that information in order to submit it back to the server. If you encrypt it, the client must be able to decrypt it, and so would an attacker. If the client does not need to decrypt it (because it is sent back to the server as it is and only decrypted by the server), then the encrypted value becomes the actual secret.

Some high-profile sites, say Google or Dropbox, *may* employ additional measures to make stolen cookies useless. I have not checked these specific sites, though.

We could incorporate some additional measures as well. But as has already been said, restricting a cookie to a specific IP address is probably not such a good idea.

**Comment by ovisopa** [comment]
After googling a little more I seen that stealing cookies is even possible on facebook... so .. this is it, I won't worry too much about it.

One extra thing that I can think of, is to create an hash based on available  user informations in $_SERVER variable, browser, OS .. do you guys have any ideea what other unique identifier (if there are other ways) we can read using PHP or Javascript? Too bad MAC address is not available (I know MAC can be cloned quite easy) but I was thinking to create the hash in PHP, if someone has access to users PC, it can steal the cookie, but he doesn't know how that hash was created, so having the exact OS and browser version (BROWSER USER AGENT) would be another mandatory thing to make the cookie work on a different PC (this hash will be saved only in server database next to the cookie identifier hash )

I know the browser USER AGENT can  also  be changed easily, but if the check will be done on the server side, the "hacker" will not be logged in, unless he also cloned the browser user agent, but if this extra step was not made, on the first failed attempt to login with a valid cookie selector and token but with a invalid USER AGENT IDENTIFIER hash, on the server side we can delete the cookie token from servers db, so the user needs to login again.

**Comment by ocram** [comment]
As I said, and as you found out, this is really possible on most websites and it’s not necessarily something that you have to protect against. That’s why we’ll probably not build any protections against cookie stealing into this library anytime soon.

But if you really want to “fingerprint” the user’s browser, you could start with something like this:

 * PHP
   * user-agent string (including OS and browser information): `$_SERVER['HTTP_USER_AGENT']`
   * languages “understood” by client: `$_SERVER['HTTP_ACCEPT_LANGUAGE']`
   * compression algorithms supported by client: `$_SERVER['HTTP_ACCEPT_ENCODING']`
   * MIME types expected by client: `$_SERVER['HTTP_ACCEPT']`
 * JavaScript (then sent to PHP perhaps)
   * timezone (offset): `(new Date()).getTimezoneOffset()`
   * screen resolution: `window.screen.width + "x" + window.screen.height`
   * color depth: `window.screen.colorDepth`
   * whether “Do not track” is enabled: `window.navigator.doNotTrack`
   * list of installed plugins: `window.navigator.plugins`

You could combine any number of these values (on the server) and log the user out as soon as the value (or hash thereof) changes.

Alternatively, you could also retrieve such a value from a client-side library like [this one](https://github.com/Valve/fingerprintjs2) directly. Anyway, keep your users’ privacy in mind, especially if you don’t combine and then hash all those values.
