### ISSUE TITLE
Auth Between Multiple Apps/Databases?

### ISSUE THREAD

**Issue by nickian** [delight-im/PHP-Auth#76]
I'm wondering if it is possible to allow users to log into a separate app that is using this same auth library once they're already logged into another. Basically, I have users in the "client area" of my site and I want them to be able to use the same credentials to access their own site's backend by keeping the users table synced between the two separate databases. It would be nice if they didn't have to log in again when heading to the other domain. Is this even technically possible?

Something like?:

```
if ($app->auth->isLoggedIn()) {
   // Select user info manually from DB
   // cURL post to other app/domain with user email and pw hash
}
```

Then on the app we are posting to, auth by pw hash instead of pw?

`$app->auth->login($_POST['email'], $_POST['pw_hash'], $remember_duration);`

Or does this miss the point of password hashing altogether? Is there a way to securely do something like this?

Would it be better to simply keep the tables synced so the credentials are the same, but they still have to re-auth when going to the other domain?

Or would it make sense to use a central database for auth between multiple sites and have additional tables, rather than additional databases, for the separate apps?

Thanks!

**Comment by ocram** [comment]
Good question!

This is slightly out of scope of this library, which focuses on authentication and authorization for individual sites. But you don’t need much extra code to achieve what you want.

The fundamental problem is that when two sites are located at different registrable domains, e.g. `example.com` and `example.org`, browsers consider them different parties. Rightly so, in most cases. On the other hand, individual subdomains of your domain, e.g. `a.example.com` and `b.example.com`, can share information and may be considered *one* party.

This means that you cannot share cookies between your two domains, which are used to transfer and store the *session identifier*. You could use other means of transferring the session identifier, e.g. [via a URL parameter](http://php.net/manual/en/session.idpassing.php), though that’s not as secure.

Even if you were able to share your session identifiers with the other site, however, you’d need access to the underlying session. So the two sites must be on the same machine or must be able to share data privately, e.g. in a shared database.

If that’s not possible, you cannot share sessions. You need separate sessions on the individual sites. That may be your situation.

Then, the only thing you might do is trying to initiate the session on the second site automatically, logging the user in directly. That appears to be what you want. You want to share authentication and authorization information between unrelated parties, which can nevertheless trust each other. These trusting parties are your individual sites. This is called [single sign-on (SSO)](https://en.wikipedia.org/wiki/Single_sign-on).

Popular concepts and protocols for this purpose are [OAuth](https://en.wikipedia.org/wiki/OAuth), [OpenID](https://en.wikipedia.org/wiki/OpenID) and [SAML](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language), among others.

These are a slightly complex, however, and you may prefer to use something more modern and lightweight, such as [JSON Web Tokens (JWT)](https://en.wikipedia.org/wiki/JSON_Web_Token).

In practice, what you’d like to do is the following: When a user is logged in at site A and wants to switch to site B where they should be logged in as well, you’d like to simply pass the user ID from site A to site B and log the user in at site B. That doesn’t work, obviously, because anybody could pass *any* user ID. So you need some way to sign that information so that site B can trust the information it receives from site A.

With JWT in PHP, this is quite simple, e.g. using [this library](https://github.com/lcobucci/jwt/blob/3.2/README.md). You could do this manually in a few lines of code, but you’ll also need to decode and verify the tokens, so using that library is probably the best solution.

When the user leaves site A, i.e. when you redirect from site A to site B, you generate a JTW token and add it to the URL of site B as a parameter *once*. Or better use HTTP POST instead of GET. On site B, you process that token and verify it. If it’s valid, you can sign in the user with the provided ID automatically because you know you can trust the information you received.

For all tokens, the time “issued at” will usually be `\time()`, just as “not before”, because you want them to be valid immediately. The “expiration” should be as soon as possible but as late as practically necessary. With a redirect, the token may expire already after a few seconds, usually. The information that you set as the payload is what you want to transfer, usually the ID of the user to sign in. The critical part is signing (on site A) and verifying (on site B) the token with a shared key and an algorithm such as `HS256` (HMAC + SHA-256). This is built into the JWT protocol and the library.

If you want to further strengthen the security of this mechanism, check that the user’s IP address remains constant and that their referrer is either empty or correct, i.e. not from a wrong site. Later, you could of course fine-tune all this, e.g. using other mechanisms to transfer and store the tokens, such as `iframes` in HTML and `localStorage` in JavaScript, as [the Stack Exchange network did](https://meta.stackexchange.com/a/64274).

Finally, if you could share the user database directly between the two sites, that would free you from having to keep two versions of the database in sync. But then you may also be able to share the sessions directly. That, in turn, would require you to change PHP’s session handler from writing to the file system to writing to your database.

Hope that helps!

**Comment by nickian** [comment]
Thanks! This is very useful info. Maybe I will look more into sharing session info.

**Comment by ocram** [comment]
I’d like to add that the JWT approach is more scalable, and probably, it will even turn out to be easier to implement. If you really want to share session data directly, you’ll need [this](http://php.net/manual/en/session.customhandler.php) on *all* sites, plus a shared database (or other storage).

**Comment by scifinder** [comment]
Hello! I want to continue this discussion.

For example, let's take this situation: I have site _main.tld_, on which `PHP-Auth` is configured. I also have sites _id.main.tld_, _other.tld_, and _third.tld_ that a user registered on site _main.tld_ should have access to.

So, the algorithm.

- On _main.tld_: user enters an email and password and authenticates.

- On _id.main.tld_, _other.tld_, and _third.tld_: redirect to _main.tld_ while open.

- If the user is authenticated on _main.tld_, _main.tld_ generates a JWT-token containing the user's ID and redirects it back to the calling site.

- The calling site verifies the JWT-token, extracts the user ID from it, and makes a request for it (for example, to a shared database).

- The calling site optionally sets cookies. (The cookie lifetime may be obviously shorter than the cookie lifetime on _main.tld_)

- If the user is not authenticated on _main.tld_, a login form opens. After successful authentication, a JWT-token is generated and redirected to the calling site.

- If local cookies exist when opening _id.main.tld_, _other.tld_, and _third.tld_, then the information for recreating the session is taken from there. If the local cookies have expired, a redirect to the _main.tld_.

Do you think there are any potential security problems in this algorithm?
