### ISSUE TITLE
security bug

### ISSUE THREAD

**Issue by akwatra** [delight-im/PHP-Auth#82]
Hi,
with DB mysql test, I deleted user records in all tables, still your ```$auth->isLoggedIn()``` was working.
and returning all users details.

**Comment by ocram** [comment]
Thanks!

This is simply because user data for each signed-in user is stored in a PHP session, and you should know how PHP’s sessions work.

Deleting a user from the database does not immediately log them out, and neither are there any claims here that it would do so.

There is already an issue with a solution to account for this: https://github.com/delight-im/PHP-Auth/issues/67 It will let you decide how often (if at all) you want to synchronize the session data with the actual information in the database.
