### ISSUE TITLE
install without composer

### ISSUE THREAD

**Issue by flatsiedatsie** [delight-im/PHP-Auth#90]
The goal of this project is to help beginners get better security. But then the installation proces requires composer?

How can this be used without composer? Is it possible to also create a guide for those on shared hosting?

**Comment by ocram** [comment]
> The goal of this project is to help beginners get better security.

Exactly!

> But then the installation proces requires composer?

Yes. Although this may sound like a contradiction, it really is not.

> How can this be used without composer?

It can’t. We did experiment with this in the past, but at some point we decided it’s really not worth it and everybody should use Composer to install this. Don’t be afraid of Composer. It’s easy, really! Otherwise we wouldn’t have made that decision.

> Is it possible to also create a guide for those on shared hosting?

Just follow the same guide. It works for shared hosting as well.

One of the common misconceptions about Composer is that you have to install it on your server. You really shouldn’t! Composer is installed on your development machine only. It downloads all the required libraries and sets up your dependencies. Just as you would do manually. And then when deploying your application (to your shared hosting environment), e.g. via SFTP upload, you just upload the `vendor` directory as well, which should be inside your project directory.

Hope that helps a bit already. Feel free to ask any further questions here.

**Comment by flatsiedatsie** [comment]
You are still assuming that beginners
- Use terminals
- Set up local development servers
- Want to do any of the above
- That the above is worth the effort for the project involved.

I was hoping I has found a simple drop-in authentification system. It looked to promising!

Can you recommend any alternatives?

**Comment by rgvy** [comment]
@flatsiedatsie, this is a truly excellent authentication system that includes an extremely simple and powerful php framework. I highly recommend it even if it takes 20-40 minutes to figure out how to install it (see below). Using this framework (for tasks other than authentication) is easy and saves a massive amount of time. 

Like yourself, I dislike the terminal and composer. However, I do find that php class autoloading is necessary for any nontrivial project. I have written some very informal installation instructions here: https://github.com/delight-im/PHP-Auth/issues/14#issuecomment-313262040.

As for beginners, this is actually the ideal framework. It is extremely well written, easy to understand, and covers the major functionality of the popular frameworks (laravel, symphony, etc). Almost all modern php applications are completely tied to one of them, so this is a great way to learn similar architecture.

**Comment by ocram** [comment]
> Use terminals

You really don’t have to be a regular user of the terminal or be very comfortable with it. You only need to know how to open it. That’s all. After that, paste the command that is presented to you in the README in order to install the library. Again, we’re here to help.

> Set up local development servers

This is not necessary at all. In general it is recommended, yes. But that does not depend on Composer. It is recommended *with* Composer just as much as when working on a project *without* Composer. To put it differently, Composer does not add any need for a local development server. You can just fetch the libraries with Composer and upload.

> I was hoping I has found a simple drop-in authentification system. It looked to promising!

I think you have! Don’t easily turn down a library just because it wants you to use Composer. Again, you can regard Composer as merely a download manager that downloads libraries for you and puts them into your project directory so that you don’t have to do all this work manually.

> Can you recommend any alternatives?

There may certainly be some alternatives, but I rarely work with any, so I can’t recommend something here. Sorry! I still think this library might be worth the little effort of looking into Composer. Treat it as a download manager for this library (and others, as soon as you have learned to enjoy it).

**Comment by ocram** [comment]
@rgvy Thanks a lot! I hope this library alone is also a good fit if you need a standalone authentication library, which seems to be what @flatsiedatsie wants. By the way, I’m sure you can use the terminal even with MAMP. Excellent point about the autoloading. Almost forgot that.

So the autoloading may actually be the best argument for Composer at all. You think that looking into Composer for an hour is not worth the effort for your project? You surely don’t want to organize and write your own autoloader, which is the alternative, since any reasonably complex application or library (like this one) will require an autoloader, unless you want to figure about the correct list (and order) of dozens of `require` statements manually. So again, Composer is not required in order to annoy you, but because it is quite certainly the easiest and most convenient way to install a decent library.

**Comment by rgvy** [comment]
Actually, I once spent an hour trying to install Composer alongside MAMP and never got it to work. Writing my autoloader took me all of 5 minutes. Then I spent another 5 downloading all dependencies and organizing into directories. Sure it was somewhat tedious, but it was mindless and didn't require too much energy.

**Comment by ocram** [comment]
@rgvy Oh, I thought you had got it working in the end. Composer should definitely work on all the major platforms, i.e. Windows, macOS, Linux, and everything Unix-based. Mainly it requires PHP only, and the PHP executable must be in the path for it to work, I guess. So if you can run `php my-script.php` in the terminal, Composer should work.

While this is not reassuring with regard to the current issue we’re discussing here (😉), this at least proves that this library can be installed without Composer in a reasonable way, @flatsiedatsie. If you really don’t want Composer, try looking at the comment @rgvy linked to, where the approach without Composer is explained.

Basically, you have to do the following recursively, i.e. repeat it for every library you’ve found:

 1. Download the source on GitHub as a ZIP.
 2. Open the `composer.json` file, right in the root directory of this project here on GitHub.
 3. In that file, locate the `require` section.
 4. Repeat this process for every library you’ve found in that section, except for `ext-…` dependencies.

You put all this in a reasonable directory structure and write or copy an autoloader function. That’s all.

But as a last attempt to explain how awesome Composer is: As an alternative to the steps above, you only have to download Composer using the steps listed in the “Download” section on their website. Then you go into your project’s root directory, open a terminal there (you can look up how to do that), and paste the `composer require …` command from the README of this project. That’s all.

**Comment by flatsiedatsie** [comment]
I've already spent 3 days struggling with composer once. So I know what I don't want :-)

**Comment by ocram** [comment]
@flatsiedatsie We’re sure there cannot be any problem with Composer that cannot be solved within minutes, provided you get the right advice. But of course, it’s up to you. The only solution *without* Composer that we’ll ever support in the foreseeable future has now been documented above and requires a little bit of manual work.
