### ISSUE TITLE
logging in throws database error => throw new DatabaseError();

### ISSUE THREAD

**Issue by ftwebdesign** [delight-im/PHP-Auth#91]
I have had a lot of trouble with the login function, and finally tried it on test.php, and it fails their as well.  I really like the program and hope to be able to use it, but this is a showstopper.  http://drops.campfirepixels.info/qo1X.

I cloned the source, ran npm install, composer install and gulp.

**Comment by ocram** [comment]
Thanks for your appreciation and for the detailed information on this problem!

I’m sure there will be a simple solution, since this library should be working fine if the setup is correct. That means we need to know what your setup is exactly:

 * What database software are you using? MariaDB, MySQL, PostgreSQL or SQLite?
 * What version of the specific database software are you currently running?
 * (What PHP version are you executing this on?)
 * (What is the version of this library listed in `composer show` for your project?)

Thanks!

(By the way, running `npm` or `gulp` isn’t necessary, since they are not used in this project.)

**Comment by ftwebdesign** [comment]
I have determined it to be the database itself, but I don't know why.  I created a new database and it works with a limited program.  I replaced it with what we are using and it does not work.

We are using local by flywheel
- mysql  version 5.6.34
- php 7.1.4
- delight-im/auth   v8.0.0 Authentication for PHP. Simple, lightweight and secure.
- delight-im/base64 v1.0.0 Simple and convenient Base64 encoding and decoding for PHP
- delight-im/cookie v3.1.0 Modern cookie management for PHP
- delight-im/db     v1.2.0 Safe and convenient SQL database access in a driver-agnostic way
- delight-im/http   v2.0.0 Hypertext Transfer Protocol (HTTP) utilities for PHP
- filp/whoops       2.1.14 php error handling for cool kids
- kint-php/kint     2.2    Kint - debugging tool for PHP developers
- psr/log           1.0.2  Common interface for logging libraries

**Comment by ftwebdesign** [comment]
This was just testing data so it is not a big deal to reproduce.  That is nice to know about modifying the error to be more verbose.  I am the instructor and we are doing this as a class project.  The problem was found by adding the $e to Auth on line 164.  We can close this ticket, as it was not caused by the software, but by passing the database around and getting it corrupted.
