### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by kozuch** [delight-im/PHP-Auth#99]
Hi there,

I like this library a lot but it does not seem to support captcha. Would you have a recommendation how to solve it? Probably a third party solution like Google's reCaptcha etc? Thanks!

**Comment by maietta** [comment]
The external service you would use does not need to be implemented in this library but rather independently in your own application.

The recaptcha service is two part. It's a widget that load in your browser and is instructed to be attached to an HTML element, such as a form or input control. When the form is submitted, it's up to your server-side script to listen for the recaptcha parameter that is added to your form from that recaptcha widget. 

Your server-side script will need to grab that token, and "redeem" it with Google's recaptcha verification API endpoint. If good, then you know your visitor is human. If Google comes back with a "nope", then you know it's likely a bot.

This logic is outside the scope of this authentication library because it's a touring test, not an authentication and user management component or feature.

**Comment by ocram** [comment]
@kozuch Thanks for bringing this up! We have not considered any implementation for captchas so far. We have throttling built-in, as you may know, and for any other part of your application, you can easily add captchas yourself in a separate form. That was our reasoning. Sure, you might want captchas to unlock an account when it has been throttled. Is that what you want? We’re open to adding some small interface that would allow this library to communicate with the captcha library. But yes, captchas should be separate. Either reCaptcha or any other solution that works for you.

@maietta Thank you, couldn’t have explained this better! Still, we think there might be some legitimate use cases where you’d want to integrate the captcha implementation and this library. Perhaps this is what @kozuch had in mind.

**Comment by kozuch** [comment]
Thanks for comments. I would like to secure the user registration only so far but I forgot to specify this. I reviewed the competitive PHPAuth which has it. I do understand and agree that external solution like reCaptcha may probably be conveniently implemented in my custom code. I have not started my project yet though so have not really looked into it yet.

**Comment by ocram** [comment]
> I would like to secure the user registration only so far

Thanks for explaining the use case!

> I reviewed the competitive PHPAuth which has it

We actually think this library here is better, with one of the major reasons being that we don’t have *everything* built in, which does not even belong into the library, like SMTP, captchas, etc.

> I do understand and agree that external solution like reCaptcha may probably be conveniently implemented in my custom code

Yes, it sounds as if this was really the best thing you could do here. You should try it, and you will probably find that it’s super easy to implement alongside this library.

**Comment by maietta** [comment]
> Hi there,
> 
> I like this library a lot but it does not seem to support captcha. Would you have a recommendation how to solve it? Probably a third party solution like Google's reCaptcha etc? Thanks!

Keep in mind that Google has 3 versions of their API. The basic concept though the service will load via javascript, an embeded widget which generates a token associated with the IP of the visitor. They will generate a client-side unique string of text (the token) and then intercept an event on your page per your site's design, such as a form. The form payload will be intercepted on "submit" of the form, and the token from the javascript will be added to your existing form payload. Think of this like a double hidden input field. Your server-side script will need to capture this field and value along with your normal field but before you do anything like process the form, you should have your script ask the API if that token is valid. You will send both the token and the user's IP and Google's API will say yes/no. Version 3 of their API is nicer because it's out of the way and does not require any action by the user until the turing test is required

A shorter summary:

Any place you need the captcha, you will display the JS along with the HTML or JS action per their documentation, which includes your unique site public side version of the key.

Google will load up from their server on your page a captcha widget which they will generate a client-side token they track. This widget performs some tests to determine if a turing test is required before a form can be submitted. In either case the form will be modified to include a client-side generated token.

When the visitor of your site submits the form, the form is intercepted by javascript and modified to include that payload, in which you are required to take that payload and test against Google's API and do as you wish once you have your answer if they passed the bot test or not.

Be warned however, I have already found a way to beat all versions of the Google recaptcha and invisible captcha services, so don't trust this to be "proof" that it can detect the different between a bot and a human. However, i have not seen anyone in the wild solve Google's new recpatcha yet.
